REPORT Z_SAPDS_EXTRACT_VBAP message-id 26 line-size 255
no standard page heading.
* Z_SAPDS_Extract_VBAP.
PARAMETER DOWNLOAD(1) DEFAULT 'S' lower case. "N-svr,Y-clnt
PARAMETER EXECMODE(1) DEFAULT 'D' lower case. "D-dlg,B-btch
PARAMETER OUT_DIR(230) DEFAULT "output file dir
'\\chobisdv\' lower case.
PARAMETER IN_DIR(230) DEFAULT "input file dir
'\\chobisdv\' lower case.
PARAMETER P_DEST TYPE RFCDES-RFCDEST DEFAULT
'NONE'.
PARAMETER P_PROGID TYPE RFCOPT-RFCEXEC DEFAULT
SPACE.
PARAMETER P_GWHOST TYPE RFCOPT-RFCGWHOST DEFAULT
SPACE.
PARAMETER P_GWSERV TYPE RFCOPT-RFCGWSERV DEFAULT
SPACE.
PARAMETER P_SRVFM(30) DEFAULT "Server Callback function
SPACE.
PARAMETER P_PKGSZ TYPE I DEFAULT "Stream package size
5000.
PARAMETER P_SNC_ON(1) DEFAULT "X-on SPACE-off
SPACE.

PARAMETER $PARAM1 TYPE D.

PARAMETER $PARAM2 TYPE D.

PARAMETER P_DF_VK(40) DEFAULT "ABAP data flow object key
'' lower case.
PARAMETER P_DI_GEN(40) DEFAULT "DI version that generated ABAP
'' lower case.

*** Machine generated ABAP. Do not modify.            ***
*** (C)Copyright Business Objects S.A.  All rights reserved. ***
*
* Date Time:
*    08/18/23 10:02:59
* SAP used for generated this ABAP:
*    Release: 702
*    Host   : chobisdv
*
* ABAP Dataflow Name:
*    Z_SAPDS_Extract_VBAP
* ABAP program name in SAP:
*  Z_SAPDS_EXTRACT_VBAP
* Generated ABAP file name:
*    D:/temp/Z_SAPDS_Extract_VBAP
TABLES VBAK.
TABLES VBAP.

DATA: begin of ITAB3 occurs 0,
MANDT(3) TYPE C,
VBELN(10) TYPE C,
POSNR(6) TYPE N,
MATNR(18) TYPE C,
MATWA(18) TYPE C,
PMATN(18) TYPE C,
CHARG(10) TYPE C,
MATKL(9) TYPE C,
ARKTX(40) TYPE C,
PSTYV(4) TYPE C,
POSAR(1) TYPE C,
LFREL(1) TYPE C,
FKREL(1) TYPE C,
UEPOS(6) TYPE N,
GRPOS(6) TYPE N,
ABGRU(2) TYPE C,
PRODH(18) TYPE C,
ZWERT(16) TYPE P DECIMALS 2,
ZMENG(16) TYPE P DECIMALS 3,
ZIEME(3) TYPE C,
UMZIZ(16) TYPE P DECIMALS 0,
UMZIN(16) TYPE P DECIMALS 0,
MEINS(3) TYPE C,
SMENG(16) TYPE P DECIMALS 3,
ABLFZ(16) TYPE P DECIMALS 3,
ABDAT TYPE D,
ABSFZ(16) TYPE P DECIMALS 3,
POSEX(6) TYPE C,
KDMAT(35) TYPE C,
KBVER(16) TYPE P DECIMALS 0,
KEVER(16) TYPE P DECIMALS 0,
VKGRU(3) TYPE C,
VKAUS(3) TYPE C,
GRKOR(3) TYPE N,
FMENG(1) TYPE C,
UEBTK(1) TYPE C,
UEBTO(16) TYPE P DECIMALS 1,
UNTTO(16) TYPE P DECIMALS 1,
FAKSP(2) TYPE C,
ATPKZ(1) TYPE C,
RKFKF(1) TYPE C,
SPART(2) TYPE C,
GSBER(4) TYPE C,
NETWR(16) TYPE P DECIMALS 2,
WAERK(5) TYPE C,
ANTLF(16) TYPE P DECIMALS 0,
KZTLF(1) TYPE C,
CHSPL(1) TYPE C,
KWMENG(16) TYPE P DECIMALS 3,
LSMENG(16) TYPE P DECIMALS 3,
KBMENG(16) TYPE P DECIMALS 3,
KLMENG(16) TYPE P DECIMALS 3,
VRKME(3) TYPE C,
UMVKZ(16) TYPE P DECIMALS 0,
UMVKN(16) TYPE P DECIMALS 0,
BRGEW(16) TYPE P DECIMALS 3,
NTGEW(16) TYPE P DECIMALS 3,
GEWEI(3) TYPE C,
VOLUM(16) TYPE P DECIMALS 3,
VOLEH(3) TYPE C,
VBELV(10) TYPE C,
POSNV(6) TYPE N,
VGBEL(10) TYPE C,
VGPOS(6) TYPE N,
VOREF(1) TYPE C,
UPFLU(1) TYPE C,
ERLRE(1) TYPE C,
LPRIO(2) TYPE N,
WERKS(4) TYPE C,
LGORT(4) TYPE C,
VSTEL(4) TYPE C,
ROUTE(6) TYPE C,
STKEY(1) TYPE C,
STDAT TYPE D,
STLNR(8) TYPE C,
STPOS(16) TYPE P DECIMALS 0,
AWAHR(3) TYPE N,
ERDAT TYPE D,
ERNAM(12) TYPE C,
ERZET TYPE T,
TAXM1(1) TYPE C,
TAXM2(1) TYPE C,
TAXM3(1) TYPE C,
TAXM4(1) TYPE C,
TAXM5(1) TYPE C,
TAXM6(1) TYPE C,
TAXM7(1) TYPE C,
TAXM8(1) TYPE C,
TAXM9(1) TYPE C,
VBEAF(16) TYPE P DECIMALS 2,
VBEAV(16) TYPE P DECIMALS 2,
VGREF(1) TYPE C,
NETPR(16) TYPE P DECIMALS 2,
KPEIN(16) TYPE P DECIMALS 0,
KMEIN(3) TYPE C,
SHKZG(1) TYPE C,
SKTOF(1) TYPE C,
MTVFP(2) TYPE C,
SUMBD(1) TYPE C,
KONDM(2) TYPE C,
KTGRM(2) TYPE C,
BONUS(2) TYPE C,
PROVG(2) TYPE C,
EANNR(13) TYPE C,
PRSOK(1) TYPE C,
BWTAR(10) TYPE C,
BWTEX(1) TYPE C,
XCHPF(1) TYPE C,
XCHAR(1) TYPE C,
LFMNG(16) TYPE P DECIMALS 3,
STAFO(6) TYPE C,
WAVWR(16) TYPE P DECIMALS 2,
KZWI1(16) TYPE P DECIMALS 2,
KZWI2(16) TYPE P DECIMALS 2,
KZWI3(16) TYPE P DECIMALS 2,
KZWI4(16) TYPE P DECIMALS 2,
KZWI5(16) TYPE P DECIMALS 2,
KZWI6(16) TYPE P DECIMALS 2,
STCUR(16) TYPE P DECIMALS 5,
AEDAT TYPE D,
EAN11(18) TYPE C,
FIXMG(1) TYPE C,
PRCTR(10) TYPE C,
MVGR1(3) TYPE C,
MVGR2(3) TYPE C,
MVGR3(3) TYPE C,
MVGR4(3) TYPE C,
MVGR5(3) TYPE C,
KMPMG(16) TYPE P DECIMALS 3,
SUGRD(4) TYPE C,
SOBKZ(1) TYPE C,
VPZUO(1) TYPE C,
PAOBJNR(10) TYPE N,
PS_PSP_PNR(8) TYPE N,
AUFNR(12) TYPE C,
VPMAT(18) TYPE C,
VPWRK(4) TYPE C,
PRBME(3) TYPE C,
UMREF TYPE F,
KNTTP(1) TYPE C,
KZVBR(1) TYPE C,
SERNR(8) TYPE C,
OBJNR(22) TYPE C,
ABGRS(6) TYPE C,
BEDAE(4) TYPE C,
CMPRE(16) TYPE P DECIMALS 2,
CMTFG(1) TYPE C,
CMPNT(1) TYPE C,
CMKUA(16) TYPE P DECIMALS 5,
CUOBJ(18) TYPE N,
CUOBJ_CH(18) TYPE N,
CEPOK(1) TYPE C,
KOUPD(1) TYPE C,
SERAIL(4) TYPE C,
ANZSN TYPE I,
NACHL(1) TYPE C,
MAGRV(4) TYPE C,
MPROK(1) TYPE C,
VGTYP(1) TYPE C,
PROSA(1) TYPE C,
UEPVW(1) TYPE C,
KALNR(12) TYPE N,
KLVAR(4) TYPE C,
SPOSN(4) TYPE C,
KOWRR(1) TYPE C,
STADAT TYPE D,
EXART(2) TYPE C,
PREFE(1) TYPE C,
KNUMH(10) TYPE C,
CLINT(10) TYPE N,
CHMVS(3) TYPE N,
STLTY(1) TYPE C,
STLKN(8) TYPE N,
STPOZ(8) TYPE N,
STMAN(1) TYPE C,
ZSCHL_K(6) TYPE C,
KALSM_K(6) TYPE C,
KALVAR(4) TYPE C,
KOSCH(18) TYPE C,
UPMAT(18) TYPE C,
UKONM(2) TYPE C,
MFRGR(8) TYPE C,
PLAVO(4) TYPE C,
KANNR(35) TYPE C,
CMPRE_FLT TYPE F,
ABFOR(2) TYPE C,
ABGES TYPE F,
J_1BCFOP(10) TYPE C,
J_1BTAXLW1(3) TYPE C,
J_1BTAXLW2(3) TYPE C,
J_1BTXSDC(2) TYPE C,
WKTNR(10) TYPE C,
WKTPS(6) TYPE N,
SKOPF(18) TYPE C,
KZBWS(1) TYPE C,
WGRU1(18) TYPE C,
WGRU2(18) TYPE C,
KNUMA_PI(10) TYPE C,
KNUMA_AG(10) TYPE C,
KZFME(1) TYPE C,
LSTANR(1) TYPE C,
TECHS(12) TYPE C,
MWSBP(16) TYPE P DECIMALS 2,
BERID(10) TYPE C,
PCTRF(10) TYPE C,
LOGSYS_EXT(10) TYPE C,
J_1BTAXLW3(3) TYPE C,
J_1BTAXLW4(3) TYPE C,
J_1BTAXLW5(3) TYPE C,
STOCKLOC(20) TYPE C,
SLOCTYPE(4) TYPE C,
MSR_RET_REASON(3) TYPE C,
MSR_REFUND_CODE(3) TYPE C,
MSR_APPROV_BLOCK(1) TYPE C,
NRAB_KNUMH(10) TYPE C,
TC_AUT_DET(2) TYPE C,
MANUAL_TC_REASON(2) TYPE C,
FISCAL_INCENTIVE(4) TYPE C,
TAX_SUBJECT_ST(1) TYPE C,
FISCAL_INCENTIVE_ID(4) TYPE C,
SPCSTO(2) TYPE N,
REVACC_REFID(30) TYPE C,
REVACC_REFTYPE(3) TYPE C,
SESSION_CREATION_DATE TYPE D,
SESSION_CREATION_TIME TYPE T,
GLO_LOG_REF1_IT(25) TYPE C,
/BEV1/SRFUND(2) TYPE C,
AUFPL_OLC(10) TYPE N,
APLZL_OLC(8) TYPE N,
FERC_IND(4) TYPE C,
KOSTL(10) TYPE C,
FONDS(10) TYPE C,
FISTL(16) TYPE C,
FKBER(16) TYPE C,
GRANT_NBR(20) TYPE C,
BUDGET_PD(10) TYPE C,
IUID_RELEVANT(1) TYPE C,
MILL_SE_GPOSN(6) TYPE N,
PRS_OBJNR(22) TYPE C,
PRS_SD_SPSNR(8) TYPE N,
PRS_WORK_PERIOD(7) TYPE N,
TAS(30) TYPE C,
BETC(10) TYPE C,
MOD_ALLOW(1) TYPE C,
CANCEL_ALLOW(1) TYPE C,
PAY_METHOD(10) TYPE C,
BPN(6) TYPE C,
REP_FREQ(3) TYPE C,
FMFGUS_KEY(22) TYPE C,
PARGB(4) TYPE C,
AUFPL_OAA(10) TYPE N,
APLZL_OAA(8) TYPE N,
ARSNUM(10) TYPE N,
ARSPOS(4) TYPE N,
WTYSC_CLMITEM(16) TYPE C.
DATA: end of ITAB3.

data: append_flag(1) value ' ',
      cntbuf type i,
      delimleng type i,last_batch(1) value ' '.

CONSTANTS C_DF_VK(40) VALUE '529'.
CONSTANTS C_DI_GEN(40) VALUE '14.2.14.3160'.
DATA WARN_MSG(50).


start-of-selection.


  IF DOWNLOAD = 'S' OR
     DOWNLOAD = 'N' OR
     DOWNLOAD = 'Y'.
      .
  ELSE.
     DATA: m_xfer_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'data transfer method: ' DOWNLOAD
'. Regenerate the ABAP program and upload to this system.'
     INTO m_xfer_err_msg.
     MESSAGE  E240(S#) WITH m_xfer_err_msg.
  ENDIF.

  IF EXECMODE = 'B' OR
     EXECMODE = 'D'.
      .
  ELSE.
     DATA: m_exec_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'execution option: ' EXECMODE
'. Regenerate the ABAP program and upload to this system.'
     INTO m_exec_err_msg.
     MESSAGE  E240(S#) WITH m_exec_err_msg.
  ENDIF.

  IF DOWNLOAD = 'S'.
     PERFORM CONNECT_RFCDEST_TO_PROGID.
  ENDIF.



PERFORM FORM3.
last_batch = 'X'.
PERFORM FORM4.
FREE ITAB3.
  IF DOWNLOAD = 'S'.
     PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
  ENDIF.


end-of-selection.

CLEAR WARN_MSG.

IF NOT P_DF_VK IS INITIAL.
  IF P_DF_VK <> C_DF_VK.
     CONCATENATE '$$Warning$'
                 C_DF_VK
                 '$' INTO WARN_MSG.
  ENDIF.
ENDIF.
IF NOT P_DI_GEN IS INITIAL.
  IF P_DI_GEN <> C_DI_GEN.
     IF WARN_MSG IS INITIAL.
       CONCATENATE '$$Warning$$'
                   C_DI_GEN
                   INTO WARN_MSG.
     ELSE.
       CONCATENATE WARN_MSG
                   C_DI_GEN
                   INTO WARN_MSG.
     ENDIF.
  ENDIF.
ENDIF.

IF NOT WARN_MSG IS INITIAL.
  IF EXECMODE = 'D'.
    WRITE WARN_MSG.
    NEW-LINE.
  ELSE.
    MESSAGE S240(S#) with WARN_MSG.
  ENDIF.
ENDIF.


write  '* Program Complete *'.
write  '(C)Copyright Business Objects S.A.  All rights reserved.'.

FORM FORM3.
DATA ALTMP952(3) TYPE C.
DATA ALTMP953(10) TYPE C.
DATA ALTMP954(6) TYPE N.
DATA ALTMP955(18) TYPE C.
DATA ALTMP956(18) TYPE C.
DATA ALTMP957(18) TYPE C.
DATA ALTMP958(10) TYPE C.
DATA ALTMP959(9) TYPE C.
DATA ALTMP960(40) TYPE C.
DATA ALTMP961(4) TYPE C.
DATA ALTMP962(1) TYPE C.
DATA ALTMP963(1) TYPE C.
DATA ALTMP964(1) TYPE C.
DATA ALTMP965(6) TYPE N.
DATA ALTMP966(6) TYPE N.
DATA ALTMP967(2) TYPE C.
DATA ALTMP968(18) TYPE C.
DATA ALTMP969(16) TYPE P DECIMALS 2.
DATA ALTMP970(16) TYPE P DECIMALS 3.
DATA ALTMP971(3) TYPE C.
DATA ALTMP972(16) TYPE P DECIMALS 0.
DATA ALTMP973(16) TYPE P DECIMALS 0.
DATA ALTMP974(3) TYPE C.
DATA ALTMP975(16) TYPE P DECIMALS 3.
DATA ALTMP976(16) TYPE P DECIMALS 3.
DATA ALTMP977 TYPE D.
DATA ALTMP978(16) TYPE P DECIMALS 3.
DATA ALTMP979(6) TYPE C.
DATA ALTMP980(35) TYPE C.
DATA ALTMP981(16) TYPE P DECIMALS 0.
DATA ALTMP982(16) TYPE P DECIMALS 0.
DATA ALTMP983(3) TYPE C.
DATA ALTMP984(3) TYPE C.
DATA ALTMP985(3) TYPE N.
DATA ALTMP986(1) TYPE C.
DATA ALTMP987(1) TYPE C.
DATA ALTMP988(16) TYPE P DECIMALS 1.
DATA ALTMP989(16) TYPE P DECIMALS 1.
DATA ALTMP990(2) TYPE C.
DATA ALTMP991(1) TYPE C.
DATA ALTMP992(1) TYPE C.
DATA ALTMP993(2) TYPE C.
DATA ALTMP994(4) TYPE C.
DATA ALTMP995(16) TYPE P DECIMALS 2.
DATA ALTMP996(5) TYPE C.
DATA ALTMP997(16) TYPE P DECIMALS 0.
DATA ALTMP998(1) TYPE C.
DATA ALTMP999(1) TYPE C.
DATA ALTMP1000(16) TYPE P DECIMALS 3.
DATA ALTMP1001(16) TYPE P DECIMALS 3.
DATA ALTMP1002(16) TYPE P DECIMALS 3.
DATA ALTMP1003(16) TYPE P DECIMALS 3.
DATA ALTMP1004(3) TYPE C.
DATA ALTMP1005(16) TYPE P DECIMALS 0.
DATA ALTMP1006(16) TYPE P DECIMALS 0.
DATA ALTMP1007(16) TYPE P DECIMALS 3.
DATA ALTMP1008(16) TYPE P DECIMALS 3.
DATA ALTMP1009(3) TYPE C.
DATA ALTMP1010(16) TYPE P DECIMALS 3.
DATA ALTMP1011(3) TYPE C.
DATA ALTMP1012(10) TYPE C.
DATA ALTMP1013(6) TYPE N.
DATA ALTMP1014(10) TYPE C.
DATA ALTMP1015(6) TYPE N.
DATA ALTMP1016(1) TYPE C.
DATA ALTMP1017(1) TYPE C.
DATA ALTMP1018(1) TYPE C.
DATA ALTMP1019(2) TYPE N.
DATA ALTMP1020(4) TYPE C.
DATA ALTMP1021(4) TYPE C.
DATA ALTMP1022(4) TYPE C.
DATA ALTMP1023(6) TYPE C.
DATA ALTMP1024(1) TYPE C.
DATA ALTMP1025 TYPE D.
DATA ALTMP1026(8) TYPE C.
DATA ALTMP1027(16) TYPE P DECIMALS 0.
DATA ALTMP1028(3) TYPE N.
DATA ALTMP1029 TYPE D.
DATA ALTMP1030(12) TYPE C.
DATA ALTMP1031 TYPE T.
DATA ALTMP1032(1) TYPE C.
DATA ALTMP1033(1) TYPE C.
DATA ALTMP1034(1) TYPE C.
DATA ALTMP1035(1) TYPE C.
DATA ALTMP1036(1) TYPE C.
DATA ALTMP1037(1) TYPE C.
DATA ALTMP1038(1) TYPE C.
DATA ALTMP1039(1) TYPE C.
DATA ALTMP1040(1) TYPE C.
DATA ALTMP1041(16) TYPE P DECIMALS 2.
DATA ALTMP1042(16) TYPE P DECIMALS 2.
DATA ALTMP1043(1) TYPE C.
DATA ALTMP1044(16) TYPE P DECIMALS 2.
DATA ALTMP1045(16) TYPE P DECIMALS 0.
DATA ALTMP1046(3) TYPE C.
DATA ALTMP1047(1) TYPE C.
DATA ALTMP1048(1) TYPE C.
DATA ALTMP1049(2) TYPE C.
DATA ALTMP1050(1) TYPE C.
DATA ALTMP1051(2) TYPE C.
DATA ALTMP1052(2) TYPE C.
DATA ALTMP1053(2) TYPE C.
DATA ALTMP1054(2) TYPE C.
DATA ALTMP1055(13) TYPE C.
DATA ALTMP1056(1) TYPE C.
DATA ALTMP1057(10) TYPE C.
DATA ALTMP1058(1) TYPE C.
DATA ALTMP1059(1) TYPE C.
DATA ALTMP1060(1) TYPE C.
DATA ALTMP1061(16) TYPE P DECIMALS 3.
DATA ALTMP1062(6) TYPE C.
DATA ALTMP1063(16) TYPE P DECIMALS 2.
DATA ALTMP1064(16) TYPE P DECIMALS 2.
DATA ALTMP1065(16) TYPE P DECIMALS 2.
DATA ALTMP1066(16) TYPE P DECIMALS 2.
DATA ALTMP1067(16) TYPE P DECIMALS 2.
DATA ALTMP1068(16) TYPE P DECIMALS 2.
DATA ALTMP1069(16) TYPE P DECIMALS 2.
DATA ALTMP1070(16) TYPE P DECIMALS 5.
DATA ALTMP1071 TYPE D.
DATA ALTMP1072(18) TYPE C.
DATA ALTMP1073(1) TYPE C.
DATA ALTMP1074(10) TYPE C.
DATA ALTMP1075(3) TYPE C.
DATA ALTMP1076(3) TYPE C.
DATA ALTMP1077(3) TYPE C.
DATA ALTMP1078(3) TYPE C.
DATA ALTMP1079(3) TYPE C.
DATA ALTMP1080(16) TYPE P DECIMALS 3.
DATA ALTMP1081(4) TYPE C.
DATA ALTMP1082(1) TYPE C.
DATA ALTMP1083(1) TYPE C.
DATA ALTMP1084(10) TYPE N.
DATA ALTMP1085(8) TYPE N.
DATA ALTMP1086(12) TYPE C.
DATA ALTMP1087(18) TYPE C.
DATA ALTMP1088(4) TYPE C.
DATA ALTMP1089(3) TYPE C.
DATA ALTMP1090 TYPE F.
DATA ALTMP1091(1) TYPE C.
DATA ALTMP1092(1) TYPE C.
DATA ALTMP1093(8) TYPE C.
DATA ALTMP1094(22) TYPE C.
DATA ALTMP1095(6) TYPE C.
DATA ALTMP1096(4) TYPE C.
DATA ALTMP1097(16) TYPE P DECIMALS 2.
DATA ALTMP1098(1) TYPE C.
DATA ALTMP1099(1) TYPE C.
DATA ALTMP1100(16) TYPE P DECIMALS 5.
DATA ALTMP1101(18) TYPE N.
DATA ALTMP1102(18) TYPE N.
DATA ALTMP1103(1) TYPE C.
DATA ALTMP1104(1) TYPE C.
DATA ALTMP1105(4) TYPE C.
DATA ALTMP1106 TYPE I.
DATA ALTMP1107(1) TYPE C.
DATA ALTMP1108(4) TYPE C.
DATA ALTMP1109(1) TYPE C.
DATA ALTMP1110(1) TYPE C.
DATA ALTMP1111(1) TYPE C.
DATA ALTMP1112(1) TYPE C.
DATA ALTMP1113(12) TYPE N.
DATA ALTMP1114(4) TYPE C.
DATA ALTMP1115(4) TYPE C.
DATA ALTMP1116(1) TYPE C.
DATA ALTMP1117 TYPE D.
DATA ALTMP1118(2) TYPE C.
DATA ALTMP1119(1) TYPE C.
DATA ALTMP1120(10) TYPE C.
DATA ALTMP1121(10) TYPE N.
DATA ALTMP1122(3) TYPE N.
DATA ALTMP1123(1) TYPE C.
DATA ALTMP1124(8) TYPE N.
DATA ALTMP1125(8) TYPE N.
DATA ALTMP1126(1) TYPE C.
DATA ALTMP1127(6) TYPE C.
DATA ALTMP1128(6) TYPE C.
DATA ALTMP1129(4) TYPE C.
DATA ALTMP1130(18) TYPE C.
DATA ALTMP1131(18) TYPE C.
DATA ALTMP1132(2) TYPE C.
DATA ALTMP1133(8) TYPE C.
DATA ALTMP1134(4) TYPE C.
DATA ALTMP1135(35) TYPE C.
DATA ALTMP1136 TYPE F.
DATA ALTMP1137(2) TYPE C.
DATA ALTMP1138 TYPE F.
DATA ALTMP1139(10) TYPE C.
DATA ALTMP1140(3) TYPE C.
DATA ALTMP1141(3) TYPE C.
DATA ALTMP1142(2) TYPE C.
DATA ALTMP1143(10) TYPE C.
DATA ALTMP1144(6) TYPE N.
DATA ALTMP1145(18) TYPE C.
DATA ALTMP1146(1) TYPE C.
DATA ALTMP1147(18) TYPE C.
DATA ALTMP1148(18) TYPE C.
DATA ALTMP1149(10) TYPE C.
DATA ALTMP1150(10) TYPE C.
DATA ALTMP1151(1) TYPE C.
DATA ALTMP1152(1) TYPE C.
DATA ALTMP1153(12) TYPE C.
DATA ALTMP1154(16) TYPE P DECIMALS 2.
DATA ALTMP1155(10) TYPE C.
DATA ALTMP1156(10) TYPE C.
DATA ALTMP1157(10) TYPE C.
DATA ALTMP1158(3) TYPE C.
DATA ALTMP1159(3) TYPE C.
DATA ALTMP1160(3) TYPE C.
DATA ALTMP1161(20) TYPE C.
DATA ALTMP1162(4) TYPE C.
DATA ALTMP1163(3) TYPE C.
DATA ALTMP1164(3) TYPE C.
DATA ALTMP1165(1) TYPE C.
DATA ALTMP1166(10) TYPE C.
DATA ALTMP1167(2) TYPE C.
DATA ALTMP1168(2) TYPE C.
DATA ALTMP1169(4) TYPE C.
DATA ALTMP1170(1) TYPE C.
DATA ALTMP1171(4) TYPE C.
DATA ALTMP1172(2) TYPE N.
DATA ALTMP1173(30) TYPE C.
DATA ALTMP1174(3) TYPE C.
DATA ALTMP1175 TYPE D.
DATA ALTMP1176 TYPE T.
DATA ALTMP1177(25) TYPE C.
DATA ALTMP1178(2) TYPE C.
DATA ALTMP1179(10) TYPE N.
DATA ALTMP1180(8) TYPE N.
DATA ALTMP1181(4) TYPE C.
DATA ALTMP1182(10) TYPE C.
DATA ALTMP1183(10) TYPE C.
DATA ALTMP1184(16) TYPE C.
DATA ALTMP1185(16) TYPE C.
DATA ALTMP1186(20) TYPE C.
DATA ALTMP1187(10) TYPE C.
DATA ALTMP1188(1) TYPE C.
DATA ALTMP1189(6) TYPE N.
DATA ALTMP1190(22) TYPE C.
DATA ALTMP1191(8) TYPE N.
DATA ALTMP1192(7) TYPE N.
DATA ALTMP1193(30) TYPE C.
DATA ALTMP1194(10) TYPE C.
DATA ALTMP1195(1) TYPE C.
DATA ALTMP1196(1) TYPE C.
DATA ALTMP1197(10) TYPE C.
DATA ALTMP1198(6) TYPE C.
DATA ALTMP1199(3) TYPE C.
DATA ALTMP1200(22) TYPE C.
DATA ALTMP1201(4) TYPE C.
DATA ALTMP1202(10) TYPE N.
DATA ALTMP1203(8) TYPE N.
DATA ALTMP1204(10) TYPE N.
DATA ALTMP1205(4) TYPE N.
DATA ALTMP1206(16) TYPE C.

DATA VBAP9MANDT LIKE VBAP-MANDT.
DATA VBAP9VBELN LIKE VBAP-VBELN.
DATA VBAP9POSNR LIKE VBAP-POSNR.
DATA VBAP9MATNR LIKE VBAP-MATNR.
DATA VBAP9MATWA LIKE VBAP-MATWA.
DATA VBAP9PMATN LIKE VBAP-PMATN.
DATA VBAP9CHARG LIKE VBAP-CHARG.
DATA VBAP9MATKL LIKE VBAP-MATKL.
DATA VBAP9ARKTX LIKE VBAP-ARKTX.
DATA VBAP9PSTYV LIKE VBAP-PSTYV.
DATA VBAP9POSAR LIKE VBAP-POSAR.
DATA VBAP9LFREL LIKE VBAP-LFREL.
DATA VBAP9FKREL LIKE VBAP-FKREL.
DATA VBAP9UEPOS LIKE VBAP-UEPOS.
DATA VBAP9GRPOS LIKE VBAP-GRPOS.
DATA VBAP9ABGRU LIKE VBAP-ABGRU.
DATA VBAP9PRODH LIKE VBAP-PRODH.
DATA VBAP9ZWERT LIKE VBAP-ZWERT.
DATA VBAP9ZMENG LIKE VBAP-ZMENG.
DATA VBAP9ZIEME LIKE VBAP-ZIEME.
DATA VBAP9UMZIZ LIKE VBAP-UMZIZ.
DATA VBAP9UMZIN LIKE VBAP-UMZIN.
DATA VBAP9MEINS LIKE VBAP-MEINS.
DATA VBAP9SMENG LIKE VBAP-SMENG.
DATA VBAP9ABLFZ LIKE VBAP-ABLFZ.
DATA VBAP9ABDAT LIKE VBAP-ABDAT.
DATA VBAP9ABSFZ LIKE VBAP-ABSFZ.
DATA VBAP9POSEX LIKE VBAP-POSEX.
DATA VBAP9KDMAT LIKE VBAP-KDMAT.
DATA VBAP9KBVER LIKE VBAP-KBVER.
DATA VBAP9KEVER LIKE VBAP-KEVER.
DATA VBAP9VKGRU LIKE VBAP-VKGRU.
DATA VBAP9VKAUS LIKE VBAP-VKAUS.
DATA VBAP9GRKOR LIKE VBAP-GRKOR.
DATA VBAP9FMENG LIKE VBAP-FMENG.
DATA VBAP9UEBTK LIKE VBAP-UEBTK.
DATA VBAP9UEBTO LIKE VBAP-UEBTO.
DATA VBAP9UNTTO LIKE VBAP-UNTTO.
DATA VBAP9FAKSP LIKE VBAP-FAKSP.
DATA VBAP9ATPKZ LIKE VBAP-ATPKZ.
DATA VBAP9RKFKF LIKE VBAP-RKFKF.
DATA VBAP9SPART LIKE VBAP-SPART.
DATA VBAP9GSBER LIKE VBAP-GSBER.
DATA VBAP9NETWR LIKE VBAP-NETWR.
DATA VBAP9WAERK LIKE VBAP-WAERK.
DATA VBAP9ANTLF LIKE VBAP-ANTLF.
DATA VBAP9KZTLF LIKE VBAP-KZTLF.
DATA VBAP9CHSPL LIKE VBAP-CHSPL.
DATA VBAP9KWMENG LIKE VBAP-KWMENG.
DATA VBAP9LSMENG LIKE VBAP-LSMENG.
DATA VBAP9KBMENG LIKE VBAP-KBMENG.
DATA VBAP9KLMENG LIKE VBAP-KLMENG.
DATA VBAP9VRKME LIKE VBAP-VRKME.
DATA VBAP9UMVKZ LIKE VBAP-UMVKZ.
DATA VBAP9UMVKN LIKE VBAP-UMVKN.
DATA VBAP9BRGEW LIKE VBAP-BRGEW.
DATA VBAP9NTGEW LIKE VBAP-NTGEW.
DATA VBAP9GEWEI LIKE VBAP-GEWEI.
DATA VBAP9VOLUM LIKE VBAP-VOLUM.
DATA VBAP9VOLEH LIKE VBAP-VOLEH.
DATA VBAP9VBELV LIKE VBAP-VBELV.
DATA VBAP9POSNV LIKE VBAP-POSNV.
DATA VBAP9VGBEL LIKE VBAP-VGBEL.
DATA VBAP9VGPOS LIKE VBAP-VGPOS.
DATA VBAP9VOREF LIKE VBAP-VOREF.
DATA VBAP9UPFLU LIKE VBAP-UPFLU.
DATA VBAP9ERLRE LIKE VBAP-ERLRE.
DATA VBAP9LPRIO LIKE VBAP-LPRIO.
DATA VBAP9WERKS LIKE VBAP-WERKS.
DATA VBAP9LGORT LIKE VBAP-LGORT.
DATA VBAP9VSTEL LIKE VBAP-VSTEL.
DATA VBAP9ROUTE LIKE VBAP-ROUTE.
DATA VBAP9STKEY LIKE VBAP-STKEY.
DATA VBAP9STDAT LIKE VBAP-STDAT.
DATA VBAP9STLNR LIKE VBAP-STLNR.
DATA VBAP9STPOS LIKE VBAP-STPOS.
DATA VBAP9AWAHR LIKE VBAP-AWAHR.
DATA VBAP9ERDAT LIKE VBAP-ERDAT.
DATA VBAP9ERNAM LIKE VBAP-ERNAM.
DATA VBAP9ERZET LIKE VBAP-ERZET.
DATA VBAP9TAXM1 LIKE VBAP-TAXM1.
DATA VBAP9TAXM2 LIKE VBAP-TAXM2.
DATA VBAP9TAXM3 LIKE VBAP-TAXM3.
DATA VBAP9TAXM4 LIKE VBAP-TAXM4.
DATA VBAP9TAXM5 LIKE VBAP-TAXM5.
DATA VBAP9TAXM6 LIKE VBAP-TAXM6.
DATA VBAP9TAXM7 LIKE VBAP-TAXM7.
DATA VBAP9TAXM8 LIKE VBAP-TAXM8.
DATA VBAP9TAXM9 LIKE VBAP-TAXM9.
DATA VBAP9VBEAF LIKE VBAP-VBEAF.
DATA VBAP9VBEAV LIKE VBAP-VBEAV.
DATA VBAP9VGREF LIKE VBAP-VGREF.
DATA VBAP9NETPR LIKE VBAP-NETPR.
DATA VBAP9KPEIN LIKE VBAP-KPEIN.
DATA VBAP9KMEIN LIKE VBAP-KMEIN.
DATA VBAP9SHKZG LIKE VBAP-SHKZG.
DATA VBAP9SKTOF LIKE VBAP-SKTOF.
DATA VBAP9MTVFP LIKE VBAP-MTVFP.
DATA VBAP9SUMBD LIKE VBAP-SUMBD.
DATA VBAP9KONDM LIKE VBAP-KONDM.
DATA VBAP9KTGRM LIKE VBAP-KTGRM.
DATA VBAP9BONUS LIKE VBAP-BONUS.
DATA VBAP9PROVG LIKE VBAP-PROVG.
DATA VBAP9EANNR LIKE VBAP-EANNR.
DATA VBAP9PRSOK LIKE VBAP-PRSOK.
DATA VBAP9BWTAR LIKE VBAP-BWTAR.
DATA VBAP9BWTEX LIKE VBAP-BWTEX.
DATA VBAP9XCHPF LIKE VBAP-XCHPF.
DATA VBAP9XCHAR LIKE VBAP-XCHAR.
DATA VBAP9LFMNG LIKE VBAP-LFMNG.
DATA VBAP9STAFO LIKE VBAP-STAFO.
DATA VBAP9WAVWR LIKE VBAP-WAVWR.
DATA VBAP9KZWI1 LIKE VBAP-KZWI1.
DATA VBAP9KZWI2 LIKE VBAP-KZWI2.
DATA VBAP9KZWI3 LIKE VBAP-KZWI3.
DATA VBAP9KZWI4 LIKE VBAP-KZWI4.
DATA VBAP9KZWI5 LIKE VBAP-KZWI5.
DATA VBAP9KZWI6 LIKE VBAP-KZWI6.
DATA VBAP9STCUR LIKE VBAP-STCUR.
DATA VBAP9AEDAT LIKE VBAP-AEDAT.
DATA VBAP9EAN11 LIKE VBAP-EAN11.
DATA VBAP9FIXMG LIKE VBAP-FIXMG.
DATA VBAP9PRCTR LIKE VBAP-PRCTR.
DATA VBAP9MVGR1 LIKE VBAP-MVGR1.
DATA VBAP9MVGR2 LIKE VBAP-MVGR2.
DATA VBAP9MVGR3 LIKE VBAP-MVGR3.
DATA VBAP9MVGR4 LIKE VBAP-MVGR4.
DATA VBAP9MVGR5 LIKE VBAP-MVGR5.
DATA VBAP9KMPMG LIKE VBAP-KMPMG.
DATA VBAP9SUGRD LIKE VBAP-SUGRD.
DATA VBAP9SOBKZ LIKE VBAP-SOBKZ.
DATA VBAP9VPZUO LIKE VBAP-VPZUO.
DATA VBAP9PAOBJNR LIKE VBAP-PAOBJNR.
DATA VBAP9PS_PSP_PNR LIKE VBAP-PS_PSP_PNR.
DATA VBAP9AUFNR LIKE VBAP-AUFNR.
DATA VBAP9VPMAT LIKE VBAP-VPMAT.
DATA VBAP9VPWRK LIKE VBAP-VPWRK.
DATA VBAP9PRBME LIKE VBAP-PRBME.
DATA VBAP9UMREF LIKE VBAP-UMREF.
DATA VBAP9KNTTP LIKE VBAP-KNTTP.
DATA VBAP9KZVBR LIKE VBAP-KZVBR.
DATA VBAP9SERNR LIKE VBAP-SERNR.
DATA VBAP9OBJNR LIKE VBAP-OBJNR.
DATA VBAP9ABGRS LIKE VBAP-ABGRS.
DATA VBAP9BEDAE LIKE VBAP-BEDAE.
DATA VBAP9CMPRE LIKE VBAP-CMPRE.
DATA VBAP9CMTFG LIKE VBAP-CMTFG.
DATA VBAP9CMPNT LIKE VBAP-CMPNT.
DATA VBAP9CMKUA LIKE VBAP-CMKUA.
DATA VBAP9CUOBJ LIKE VBAP-CUOBJ.
DATA VBAP9CUOBJ_CH LIKE VBAP-CUOBJ_CH.
DATA VBAP9CEPOK LIKE VBAP-CEPOK.
DATA VBAP9KOUPD LIKE VBAP-KOUPD.
DATA VBAP9SERAIL LIKE VBAP-SERAIL.
DATA VBAP9ANZSN LIKE VBAP-ANZSN.
DATA VBAP9NACHL LIKE VBAP-NACHL.
DATA VBAP9MAGRV LIKE VBAP-MAGRV.
DATA VBAP9MPROK LIKE VBAP-MPROK.
DATA VBAP9VGTYP LIKE VBAP-VGTYP.
DATA VBAP9PROSA LIKE VBAP-PROSA.
DATA VBAP9UEPVW LIKE VBAP-UEPVW.
DATA VBAP9KALNR LIKE VBAP-KALNR.
DATA VBAP9KLVAR LIKE VBAP-KLVAR.
DATA VBAP9SPOSN LIKE VBAP-SPOSN.
DATA VBAP9KOWRR LIKE VBAP-KOWRR.
DATA VBAP9STADAT LIKE VBAP-STADAT.
DATA VBAP9EXART LIKE VBAP-EXART.
DATA VBAP9PREFE LIKE VBAP-PREFE.
DATA VBAP9KNUMH LIKE VBAP-KNUMH.
DATA VBAP9CLINT LIKE VBAP-CLINT.
DATA VBAP9CHMVS LIKE VBAP-CHMVS.
DATA VBAP9STLTY LIKE VBAP-STLTY.
DATA VBAP9STLKN LIKE VBAP-STLKN.
DATA VBAP9STPOZ LIKE VBAP-STPOZ.
DATA VBAP9STMAN LIKE VBAP-STMAN.
DATA VBAP9ZSCHL_K LIKE VBAP-ZSCHL_K.
DATA VBAP9KALSM_K LIKE VBAP-KALSM_K.
DATA VBAP9KALVAR LIKE VBAP-KALVAR.
DATA VBAP9KOSCH LIKE VBAP-KOSCH.
DATA VBAP9UPMAT LIKE VBAP-UPMAT.
DATA VBAP9UKONM LIKE VBAP-UKONM.
DATA VBAP9MFRGR LIKE VBAP-MFRGR.
DATA VBAP9PLAVO LIKE VBAP-PLAVO.
DATA VBAP9KANNR LIKE VBAP-KANNR.
DATA VBAP9CMPRE_FLT LIKE VBAP-CMPRE_FLT.
DATA VBAP9ABFOR LIKE VBAP-ABFOR.
DATA VBAP9ABGES LIKE VBAP-ABGES.
DATA VBAP9J_1BCFOP LIKE VBAP-J_1BCFOP.
DATA VBAP9J_1BTAXLW1 LIKE VBAP-J_1BTAXLW1.
DATA VBAP9J_1BTAXLW2 LIKE VBAP-J_1BTAXLW2.
DATA VBAP9J_1BTXSDC LIKE VBAP-J_1BTXSDC.
DATA VBAP9WKTNR LIKE VBAP-WKTNR.
DATA VBAP9WKTPS LIKE VBAP-WKTPS.
DATA VBAP9SKOPF LIKE VBAP-SKOPF.
DATA VBAP9KZBWS LIKE VBAP-KZBWS.
DATA VBAP9WGRU1 LIKE VBAP-WGRU1.
DATA VBAP9WGRU2 LIKE VBAP-WGRU2.
DATA VBAP9KNUMA_PI LIKE VBAP-KNUMA_PI.
DATA VBAP9KNUMA_AG LIKE VBAP-KNUMA_AG.
DATA VBAP9KZFME LIKE VBAP-KZFME.
DATA VBAP9LSTANR LIKE VBAP-LSTANR.
DATA VBAP9TECHS LIKE VBAP-TECHS.
DATA VBAP9MWSBP LIKE VBAP-MWSBP.
DATA VBAP9BERID LIKE VBAP-BERID.
DATA VBAP9PCTRF LIKE VBAP-PCTRF.
DATA VBAP9LOGSYS_EXT LIKE VBAP-LOGSYS_EXT.
DATA VBAP9J_1BTAXLW3 LIKE VBAP-J_1BTAXLW3.
DATA VBAP9J_1BTAXLW4 LIKE VBAP-J_1BTAXLW4.
DATA VBAP9J_1BTAXLW5 LIKE VBAP-J_1BTAXLW5.
DATA VBAP9STOCKLOC LIKE VBAP-STOCKLOC.
DATA VBAP9SLOCTYPE LIKE VBAP-SLOCTYPE.
DATA VBAP9MSR_RET_REASON LIKE VBAP-MSR_RET_REASON.
DATA VBAP9MSR_REFUND_CODE LIKE VBAP-MSR_REFUND_CODE.
DATA VBAP9MSR_APPROV_BLOCK LIKE VBAP-MSR_APPROV_BLOCK.
DATA VBAP9NRAB_KNUMH LIKE VBAP-NRAB_KNUMH.
DATA VBAP9TC_AUT_DET LIKE VBAP-TC_AUT_DET.
DATA VBAP9MANUAL_TC_REASON LIKE VBAP-MANUAL_TC_REASON.
DATA VBAP9FISCAL_INCENTIVE LIKE VBAP-FISCAL_INCENTIVE.
DATA VBAP9TAX_SUBJECT_ST LIKE VBAP-TAX_SUBJECT_ST.
DATA VBAP9FISCAL_INCENTIVE_ID LIKE VBAP-FISCAL_INCENTIVE_ID.
DATA VBAP9SPCSTO LIKE VBAP-SPCSTO.
DATA VBAP9REVACC_REFID LIKE VBAP-REVACC_REFID.
DATA VBAP9REVACC_REFTYPE LIKE VBAP-REVACC_REFTYPE.
DATA VBAP9SESSION_CREATION_DATE LIKE VBAP-SESSION_CREATION_DATE.
DATA VBAP9SESSION_CREATION_TIME LIKE VBAP-SESSION_CREATION_TIME.
DATA VBAP9GLO_LOG_REF1_IT LIKE VBAP-GLO_LOG_REF1_IT.
DATA VBAP9/BEV1/SRFUND LIKE VBAP-/BEV1/SRFUND.
DATA VBAP9AUFPL_OLC LIKE VBAP-AUFPL_OLC.
DATA VBAP9APLZL_OLC LIKE VBAP-APLZL_OLC.
DATA VBAP9FERC_IND LIKE VBAP-FERC_IND.
DATA VBAP9KOSTL LIKE VBAP-KOSTL.
DATA VBAP9FONDS LIKE VBAP-FONDS.
DATA VBAP9FISTL LIKE VBAP-FISTL.
DATA VBAP9FKBER LIKE VBAP-FKBER.
DATA VBAP9GRANT_NBR LIKE VBAP-GRANT_NBR.
DATA VBAP9BUDGET_PD LIKE VBAP-BUDGET_PD.
DATA VBAP9IUID_RELEVANT LIKE VBAP-IUID_RELEVANT.
DATA VBAP9MILL_SE_GPOSN LIKE VBAP-MILL_SE_GPOSN.
DATA VBAP9PRS_OBJNR LIKE VBAP-PRS_OBJNR.
DATA VBAP9PRS_SD_SPSNR LIKE VBAP-PRS_SD_SPSNR.
DATA VBAP9PRS_WORK_PERIOD LIKE VBAP-PRS_WORK_PERIOD.
DATA VBAP9TAS LIKE VBAP-TAS.
DATA VBAP9BETC LIKE VBAP-BETC.
DATA VBAP9MOD_ALLOW LIKE VBAP-MOD_ALLOW.
DATA VBAP9CANCEL_ALLOW LIKE VBAP-CANCEL_ALLOW.
DATA VBAP9PAY_METHOD LIKE VBAP-PAY_METHOD.
DATA VBAP9BPN LIKE VBAP-BPN.
DATA VBAP9REP_FREQ LIKE VBAP-REP_FREQ.
DATA VBAP9FMFGUS_KEY LIKE VBAP-FMFGUS_KEY.
DATA VBAP9PARGB LIKE VBAP-PARGB.
DATA VBAP9AUFPL_OAA LIKE VBAP-AUFPL_OAA.
DATA VBAP9APLZL_OAA LIKE VBAP-APLZL_OAA.
DATA VBAP9ARSNUM LIKE VBAP-ARSNUM.
DATA VBAP9ARSPOS LIKE VBAP-ARSPOS.
DATA VBAP9WTYSC_CLMITEM LIKE VBAP-WTYSC_CLMITEM.
DATA VBAK9AUDAT LIKE VBAK-AUDAT.
DATA VBAK9VBELN LIKE VBAK-VBELN.



SELECT
  VBAP9~MANDT
  VBAP9~VBELN
  VBAP9~POSNR
  VBAP9~MATNR
  VBAP9~MATWA
  VBAP9~PMATN
  VBAP9~CHARG
  VBAP9~MATKL
  VBAP9~ARKTX
  VBAP9~PSTYV
  VBAP9~POSAR
  VBAP9~LFREL
  VBAP9~FKREL
  VBAP9~UEPOS
  VBAP9~GRPOS
  VBAP9~ABGRU
  VBAP9~PRODH
  VBAP9~ZWERT
  VBAP9~ZMENG
  VBAP9~ZIEME
  VBAP9~UMZIZ
  VBAP9~UMZIN
  VBAP9~MEINS
  VBAP9~SMENG
  VBAP9~ABLFZ
  VBAP9~ABDAT
  VBAP9~ABSFZ
  VBAP9~POSEX
  VBAP9~KDMAT
  VBAP9~KBVER
  VBAP9~KEVER
  VBAP9~VKGRU
  VBAP9~VKAUS
  VBAP9~GRKOR
  VBAP9~FMENG
  VBAP9~UEBTK
  VBAP9~UEBTO
  VBAP9~UNTTO
  VBAP9~FAKSP
  VBAP9~ATPKZ
  VBAP9~RKFKF
  VBAP9~SPART
  VBAP9~GSBER
  VBAP9~NETWR
  VBAP9~WAERK
  VBAP9~ANTLF
  VBAP9~KZTLF
  VBAP9~CHSPL
  VBAP9~KWMENG
  VBAP9~LSMENG
  VBAP9~KBMENG
  VBAP9~KLMENG
  VBAP9~VRKME
  VBAP9~UMVKZ
  VBAP9~UMVKN
  VBAP9~BRGEW
  VBAP9~NTGEW
  VBAP9~GEWEI
  VBAP9~VOLUM
  VBAP9~VOLEH
  VBAP9~VBELV
  VBAP9~POSNV
  VBAP9~VGBEL
  VBAP9~VGPOS
  VBAP9~VOREF
  VBAP9~UPFLU
  VBAP9~ERLRE
  VBAP9~LPRIO
  VBAP9~WERKS
  VBAP9~LGORT
  VBAP9~VSTEL
  VBAP9~ROUTE
  VBAP9~STKEY
  VBAP9~STDAT
  VBAP9~STLNR
  VBAP9~STPOS
  VBAP9~AWAHR
  VBAP9~ERDAT
  VBAP9~ERNAM
  VBAP9~ERZET
  VBAP9~TAXM1
  VBAP9~TAXM2
  VBAP9~TAXM3
  VBAP9~TAXM4
  VBAP9~TAXM5
  VBAP9~TAXM6
  VBAP9~TAXM7
  VBAP9~TAXM8
  VBAP9~TAXM9
  VBAP9~VBEAF
  VBAP9~VBEAV
  VBAP9~VGREF
  VBAP9~NETPR
  VBAP9~KPEIN
  VBAP9~KMEIN
  VBAP9~SHKZG
  VBAP9~SKTOF
  VBAP9~MTVFP
  VBAP9~SUMBD
  VBAP9~KONDM
  VBAP9~KTGRM
  VBAP9~BONUS
  VBAP9~PROVG
  VBAP9~EANNR
  VBAP9~PRSOK
  VBAP9~BWTAR
  VBAP9~BWTEX
  VBAP9~XCHPF
  VBAP9~XCHAR
  VBAP9~LFMNG
  VBAP9~STAFO
  VBAP9~WAVWR
  VBAP9~KZWI1
  VBAP9~KZWI2
  VBAP9~KZWI3
  VBAP9~KZWI4
  VBAP9~KZWI5
  VBAP9~KZWI6
  VBAP9~STCUR
  VBAP9~AEDAT
  VBAP9~EAN11
  VBAP9~FIXMG
  VBAP9~PRCTR
  VBAP9~MVGR1
  VBAP9~MVGR2
  VBAP9~MVGR3
  VBAP9~MVGR4
  VBAP9~MVGR5
  VBAP9~KMPMG
  VBAP9~SUGRD
  VBAP9~SOBKZ
  VBAP9~VPZUO
  VBAP9~PAOBJNR
  VBAP9~PS_PSP_PNR
  VBAP9~AUFNR
  VBAP9~VPMAT
  VBAP9~VPWRK
  VBAP9~PRBME
  VBAP9~UMREF
  VBAP9~KNTTP
  VBAP9~KZVBR
  VBAP9~SERNR
  VBAP9~OBJNR
  VBAP9~ABGRS
  VBAP9~BEDAE
  VBAP9~CMPRE
  VBAP9~CMTFG
  VBAP9~CMPNT
  VBAP9~CMKUA
  VBAP9~CUOBJ
  VBAP9~CUOBJ_CH
  VBAP9~CEPOK
  VBAP9~KOUPD
  VBAP9~SERAIL
  VBAP9~ANZSN
  VBAP9~NACHL
  VBAP9~MAGRV
  VBAP9~MPROK
  VBAP9~VGTYP
  VBAP9~PROSA
  VBAP9~UEPVW
  VBAP9~KALNR
  VBAP9~KLVAR
  VBAP9~SPOSN
  VBAP9~KOWRR
  VBAP9~STADAT
  VBAP9~EXART
  VBAP9~PREFE
  VBAP9~KNUMH
  VBAP9~CLINT
  VBAP9~CHMVS
  VBAP9~STLTY
  VBAP9~STLKN
  VBAP9~STPOZ
  VBAP9~STMAN
  VBAP9~ZSCHL_K
  VBAP9~KALSM_K
  VBAP9~KALVAR
  VBAP9~KOSCH
  VBAP9~UPMAT
  VBAP9~UKONM
  VBAP9~MFRGR
  VBAP9~PLAVO
  VBAP9~KANNR
  VBAP9~CMPRE_FLT
  VBAP9~ABFOR
  VBAP9~ABGES
  VBAP9~J_1BCFOP
  VBAP9~J_1BTAXLW1
  VBAP9~J_1BTAXLW2
  VBAP9~J_1BTXSDC
  VBAP9~WKTNR
  VBAP9~WKTPS
  VBAP9~SKOPF
  VBAP9~KZBWS
  VBAP9~WGRU1
  VBAP9~WGRU2
  VBAP9~KNUMA_PI
  VBAP9~KNUMA_AG
  VBAP9~KZFME
  VBAP9~LSTANR
  VBAP9~TECHS
  VBAP9~MWSBP
  VBAP9~BERID
  VBAP9~PCTRF
  VBAP9~LOGSYS_EXT
  VBAP9~J_1BTAXLW3
  VBAP9~J_1BTAXLW4
  VBAP9~J_1BTAXLW5
  VBAP9~STOCKLOC
  VBAP9~SLOCTYPE
  VBAP9~MSR_RET_REASON
  VBAP9~MSR_REFUND_CODE
  VBAP9~MSR_APPROV_BLOCK
  VBAP9~NRAB_KNUMH
  VBAP9~TC_AUT_DET
  VBAP9~MANUAL_TC_REASON
  VBAP9~FISCAL_INCENTIVE
  VBAP9~TAX_SUBJECT_ST
  VBAP9~FISCAL_INCENTIVE_ID
  VBAP9~SPCSTO
  VBAP9~REVACC_REFID
  VBAP9~REVACC_REFTYPE
  VBAP9~SESSION_CREATION_DATE
  VBAP9~SESSION_CREATION_TIME
  VBAP9~GLO_LOG_REF1_IT
  VBAP9~/BEV1/SRFUND
  VBAP9~AUFPL_OLC
  VBAP9~APLZL_OLC
  VBAP9~FERC_IND
  VBAP9~KOSTL
  VBAP9~FONDS
  VBAP9~FISTL
  VBAP9~FKBER
  VBAP9~GRANT_NBR
  VBAP9~BUDGET_PD
  VBAP9~IUID_RELEVANT
  VBAP9~MILL_SE_GPOSN
  VBAP9~PRS_OBJNR
  VBAP9~PRS_SD_SPSNR
  VBAP9~PRS_WORK_PERIOD
  VBAP9~TAS
  VBAP9~BETC
  VBAP9~MOD_ALLOW
  VBAP9~CANCEL_ALLOW
  VBAP9~PAY_METHOD
  VBAP9~BPN
  VBAP9~REP_FREQ
  VBAP9~FMFGUS_KEY
  VBAP9~PARGB
  VBAP9~AUFPL_OAA
  VBAP9~APLZL_OAA
  VBAP9~ARSNUM
  VBAP9~ARSPOS
  VBAP9~WTYSC_CLMITEM
  VBAK9~AUDAT
  VBAK9~VBELN
into (VBAP9MANDT,
  VBAP9VBELN,
  VBAP9POSNR,
  VBAP9MATNR,
  VBAP9MATWA,
  VBAP9PMATN,
  VBAP9CHARG,
  VBAP9MATKL,
  VBAP9ARKTX,
  VBAP9PSTYV,
  VBAP9POSAR,
  VBAP9LFREL,
  VBAP9FKREL,
  VBAP9UEPOS,
  VBAP9GRPOS,
  VBAP9ABGRU,
  VBAP9PRODH,
  VBAP9ZWERT,
  VBAP9ZMENG,
  VBAP9ZIEME,
  VBAP9UMZIZ,
  VBAP9UMZIN,
  VBAP9MEINS,
  VBAP9SMENG,
  VBAP9ABLFZ,
  VBAP9ABDAT,
  VBAP9ABSFZ,
  VBAP9POSEX,
  VBAP9KDMAT,
  VBAP9KBVER,
  VBAP9KEVER,
  VBAP9VKGRU,
  VBAP9VKAUS,
  VBAP9GRKOR,
  VBAP9FMENG,
  VBAP9UEBTK,
  VBAP9UEBTO,
  VBAP9UNTTO,
  VBAP9FAKSP,
  VBAP9ATPKZ,
  VBAP9RKFKF,
  VBAP9SPART,
  VBAP9GSBER,
  VBAP9NETWR,
  VBAP9WAERK,
  VBAP9ANTLF,
  VBAP9KZTLF,
  VBAP9CHSPL,
  VBAP9KWMENG,
  VBAP9LSMENG,
  VBAP9KBMENG,
  VBAP9KLMENG,
  VBAP9VRKME,
  VBAP9UMVKZ,
  VBAP9UMVKN,
  VBAP9BRGEW,
  VBAP9NTGEW,
  VBAP9GEWEI,
  VBAP9VOLUM,
  VBAP9VOLEH,
  VBAP9VBELV,
  VBAP9POSNV,
  VBAP9VGBEL,
  VBAP9VGPOS,
  VBAP9VOREF,
  VBAP9UPFLU,
  VBAP9ERLRE,
  VBAP9LPRIO,
  VBAP9WERKS,
  VBAP9LGORT,
  VBAP9VSTEL,
  VBAP9ROUTE,
  VBAP9STKEY,
  VBAP9STDAT,
  VBAP9STLNR,
  VBAP9STPOS,
  VBAP9AWAHR,
  VBAP9ERDAT,
  VBAP9ERNAM,
  VBAP9ERZET,
  VBAP9TAXM1,
  VBAP9TAXM2,
  VBAP9TAXM3,
  VBAP9TAXM4,
  VBAP9TAXM5,
  VBAP9TAXM6,
  VBAP9TAXM7,
  VBAP9TAXM8,
  VBAP9TAXM9,
  VBAP9VBEAF,
  VBAP9VBEAV,
  VBAP9VGREF,
  VBAP9NETPR,
  VBAP9KPEIN,
  VBAP9KMEIN,
  VBAP9SHKZG,
  VBAP9SKTOF,
  VBAP9MTVFP,
  VBAP9SUMBD,
  VBAP9KONDM,
  VBAP9KTGRM,
  VBAP9BONUS,
  VBAP9PROVG,
  VBAP9EANNR,
  VBAP9PRSOK,
  VBAP9BWTAR,
  VBAP9BWTEX,
  VBAP9XCHPF,
  VBAP9XCHAR,
  VBAP9LFMNG,
  VBAP9STAFO,
  VBAP9WAVWR,
  VBAP9KZWI1,
  VBAP9KZWI2,
  VBAP9KZWI3,
  VBAP9KZWI4,
  VBAP9KZWI5,
  VBAP9KZWI6,
  VBAP9STCUR,
  VBAP9AEDAT,
  VBAP9EAN11,
  VBAP9FIXMG,
  VBAP9PRCTR,
  VBAP9MVGR1,
  VBAP9MVGR2,
  VBAP9MVGR3,
  VBAP9MVGR4,
  VBAP9MVGR5,
  VBAP9KMPMG,
  VBAP9SUGRD,
  VBAP9SOBKZ,
  VBAP9VPZUO,
  VBAP9PAOBJNR,
  VBAP9PS_PSP_PNR,
  VBAP9AUFNR,
  VBAP9VPMAT,
  VBAP9VPWRK,
  VBAP9PRBME,
  VBAP9UMREF,
  VBAP9KNTTP,
  VBAP9KZVBR,
  VBAP9SERNR,
  VBAP9OBJNR,
  VBAP9ABGRS,
  VBAP9BEDAE,
  VBAP9CMPRE,
  VBAP9CMTFG,
  VBAP9CMPNT,
  VBAP9CMKUA,
  VBAP9CUOBJ,
  VBAP9CUOBJ_CH,
  VBAP9CEPOK,
  VBAP9KOUPD,
  VBAP9SERAIL,
  VBAP9ANZSN,
  VBAP9NACHL,
  VBAP9MAGRV,
  VBAP9MPROK,
  VBAP9VGTYP,
  VBAP9PROSA,
  VBAP9UEPVW,
  VBAP9KALNR,
  VBAP9KLVAR,
  VBAP9SPOSN,
  VBAP9KOWRR,
  VBAP9STADAT,
  VBAP9EXART,
  VBAP9PREFE,
  VBAP9KNUMH,
  VBAP9CLINT,
  VBAP9CHMVS,
  VBAP9STLTY,
  VBAP9STLKN,
  VBAP9STPOZ,
  VBAP9STMAN,
  VBAP9ZSCHL_K,
  VBAP9KALSM_K,
  VBAP9KALVAR,
  VBAP9KOSCH,
  VBAP9UPMAT,
  VBAP9UKONM,
  VBAP9MFRGR,
  VBAP9PLAVO,
  VBAP9KANNR,
  VBAP9CMPRE_FLT,
  VBAP9ABFOR,
  VBAP9ABGES,
  VBAP9J_1BCFOP,
  VBAP9J_1BTAXLW1,
  VBAP9J_1BTAXLW2,
  VBAP9J_1BTXSDC,
  VBAP9WKTNR,
  VBAP9WKTPS,
  VBAP9SKOPF,
  VBAP9KZBWS,
  VBAP9WGRU1,
  VBAP9WGRU2,
  VBAP9KNUMA_PI,
  VBAP9KNUMA_AG,
  VBAP9KZFME,
  VBAP9LSTANR,
  VBAP9TECHS,
  VBAP9MWSBP,
  VBAP9BERID,
  VBAP9PCTRF,
  VBAP9LOGSYS_EXT,
  VBAP9J_1BTAXLW3,
  VBAP9J_1BTAXLW4,
  VBAP9J_1BTAXLW5,
  VBAP9STOCKLOC,
  VBAP9SLOCTYPE,
  VBAP9MSR_RET_REASON,
  VBAP9MSR_REFUND_CODE,
  VBAP9MSR_APPROV_BLOCK,
  VBAP9NRAB_KNUMH,
  VBAP9TC_AUT_DET,
  VBAP9MANUAL_TC_REASON,
  VBAP9FISCAL_INCENTIVE,
  VBAP9TAX_SUBJECT_ST,
  VBAP9FISCAL_INCENTIVE_ID,
  VBAP9SPCSTO,
  VBAP9REVACC_REFID,
  VBAP9REVACC_REFTYPE,
  VBAP9SESSION_CREATION_DATE,
  VBAP9SESSION_CREATION_TIME,
  VBAP9GLO_LOG_REF1_IT,
  VBAP9/BEV1/SRFUND,
  VBAP9AUFPL_OLC,
  VBAP9APLZL_OLC,
  VBAP9FERC_IND,
  VBAP9KOSTL,
  VBAP9FONDS,
  VBAP9FISTL,
  VBAP9FKBER,
  VBAP9GRANT_NBR,
  VBAP9BUDGET_PD,
  VBAP9IUID_RELEVANT,
  VBAP9MILL_SE_GPOSN,
  VBAP9PRS_OBJNR,
  VBAP9PRS_SD_SPSNR,
  VBAP9PRS_WORK_PERIOD,
  VBAP9TAS,
  VBAP9BETC,
  VBAP9MOD_ALLOW,
  VBAP9CANCEL_ALLOW,
  VBAP9PAY_METHOD,
  VBAP9BPN,
  VBAP9REP_FREQ,
  VBAP9FMFGUS_KEY,
  VBAP9PARGB,
  VBAP9AUFPL_OAA,
  VBAP9APLZL_OAA,
  VBAP9ARSNUM,
  VBAP9ARSPOS,
  VBAP9WTYSC_CLMITEM,
  VBAK9AUDAT,
  VBAK9VBELN)
FROM VBAP AS VBAP9
 INNER JOIN VBAK AS VBAK9
 ON ( VBAP9~VBELN = VBAK9~VBELN )
WHERE ( ( VBAK9~AUDAT < $PARAM2 )
 AND ( VBAK9~AUDAT >= $PARAM1 ) ).
ALTMP952 = VBAP9MANDT.
ALTMP953 = VBAP9VBELN.
ALTMP954 = VBAP9POSNR.
ALTMP955 = VBAP9MATNR.
ALTMP956 = VBAP9MATWA.
ALTMP957 = VBAP9PMATN.
ALTMP958 = VBAP9CHARG.
ALTMP959 = VBAP9MATKL.
ALTMP960 = VBAP9ARKTX.
ALTMP961 = VBAP9PSTYV.
ALTMP962 = VBAP9POSAR.
ALTMP963 = VBAP9LFREL.
ALTMP964 = VBAP9FKREL.
ALTMP965 = VBAP9UEPOS.
ALTMP966 = VBAP9GRPOS.
ALTMP967 = VBAP9ABGRU.
ALTMP968 = VBAP9PRODH.
ALTMP969 = VBAP9ZWERT.
ALTMP970 = VBAP9ZMENG.
ALTMP971 = VBAP9ZIEME.
ALTMP972 = VBAP9UMZIZ.
ALTMP973 = VBAP9UMZIN.
ALTMP974 = VBAP9MEINS.
ALTMP975 = VBAP9SMENG.
ALTMP976 = VBAP9ABLFZ.
ALTMP977 = VBAP9ABDAT.
ALTMP978 = VBAP9ABSFZ.
ALTMP979 = VBAP9POSEX.
ALTMP980 = VBAP9KDMAT.
ALTMP981 = VBAP9KBVER.
ALTMP982 = VBAP9KEVER.
ALTMP983 = VBAP9VKGRU.
ALTMP984 = VBAP9VKAUS.
ALTMP985 = VBAP9GRKOR.
ALTMP986 = VBAP9FMENG.
ALTMP987 = VBAP9UEBTK.
ALTMP988 = VBAP9UEBTO.
ALTMP989 = VBAP9UNTTO.
ALTMP990 = VBAP9FAKSP.
ALTMP991 = VBAP9ATPKZ.
ALTMP992 = VBAP9RKFKF.
ALTMP993 = VBAP9SPART.
ALTMP994 = VBAP9GSBER.
ALTMP995 = VBAP9NETWR.
ALTMP996 = VBAP9WAERK.
ALTMP997 = VBAP9ANTLF.
ALTMP998 = VBAP9KZTLF.
ALTMP999 = VBAP9CHSPL.
ALTMP1000 = VBAP9KWMENG.
ALTMP1001 = VBAP9LSMENG.
ALTMP1002 = VBAP9KBMENG.
ALTMP1003 = VBAP9KLMENG.
ALTMP1004 = VBAP9VRKME.
ALTMP1005 = VBAP9UMVKZ.
ALTMP1006 = VBAP9UMVKN.
ALTMP1007 = VBAP9BRGEW.
ALTMP1008 = VBAP9NTGEW.
ALTMP1009 = VBAP9GEWEI.
ALTMP1010 = VBAP9VOLUM.
ALTMP1011 = VBAP9VOLEH.
ALTMP1012 = VBAP9VBELV.
ALTMP1013 = VBAP9POSNV.
ALTMP1014 = VBAP9VGBEL.
ALTMP1015 = VBAP9VGPOS.
ALTMP1016 = VBAP9VOREF.
ALTMP1017 = VBAP9UPFLU.
ALTMP1018 = VBAP9ERLRE.
ALTMP1019 = VBAP9LPRIO.
ALTMP1020 = VBAP9WERKS.
ALTMP1021 = VBAP9LGORT.
ALTMP1022 = VBAP9VSTEL.
ALTMP1023 = VBAP9ROUTE.
ALTMP1024 = VBAP9STKEY.
ALTMP1025 = VBAP9STDAT.
ALTMP1026 = VBAP9STLNR.
ALTMP1027 = VBAP9STPOS.
ALTMP1028 = VBAP9AWAHR.
ALTMP1029 = VBAP9ERDAT.
ALTMP1030 = VBAP9ERNAM.
ALTMP1031 = VBAP9ERZET.
ALTMP1032 = VBAP9TAXM1.
ALTMP1033 = VBAP9TAXM2.
ALTMP1034 = VBAP9TAXM3.
ALTMP1035 = VBAP9TAXM4.
ALTMP1036 = VBAP9TAXM5.
ALTMP1037 = VBAP9TAXM6.
ALTMP1038 = VBAP9TAXM7.
ALTMP1039 = VBAP9TAXM8.
ALTMP1040 = VBAP9TAXM9.
ALTMP1041 = VBAP9VBEAF.
ALTMP1042 = VBAP9VBEAV.
ALTMP1043 = VBAP9VGREF.
ALTMP1044 = VBAP9NETPR.
ALTMP1045 = VBAP9KPEIN.
ALTMP1046 = VBAP9KMEIN.
ALTMP1047 = VBAP9SHKZG.
ALTMP1048 = VBAP9SKTOF.
ALTMP1049 = VBAP9MTVFP.
ALTMP1050 = VBAP9SUMBD.
ALTMP1051 = VBAP9KONDM.
ALTMP1052 = VBAP9KTGRM.
ALTMP1053 = VBAP9BONUS.
ALTMP1054 = VBAP9PROVG.
ALTMP1055 = VBAP9EANNR.
ALTMP1056 = VBAP9PRSOK.
ALTMP1057 = VBAP9BWTAR.
ALTMP1058 = VBAP9BWTEX.
ALTMP1059 = VBAP9XCHPF.
ALTMP1060 = VBAP9XCHAR.
ALTMP1061 = VBAP9LFMNG.
ALTMP1062 = VBAP9STAFO.
ALTMP1063 = VBAP9WAVWR.
ALTMP1064 = VBAP9KZWI1.
ALTMP1065 = VBAP9KZWI2.
ALTMP1066 = VBAP9KZWI3.
ALTMP1067 = VBAP9KZWI4.
ALTMP1068 = VBAP9KZWI5.
ALTMP1069 = VBAP9KZWI6.
ALTMP1070 = VBAP9STCUR.
ALTMP1071 = VBAP9AEDAT.
ALTMP1072 = VBAP9EAN11.
ALTMP1073 = VBAP9FIXMG.
ALTMP1074 = VBAP9PRCTR.
ALTMP1075 = VBAP9MVGR1.
ALTMP1076 = VBAP9MVGR2.
ALTMP1077 = VBAP9MVGR3.
ALTMP1078 = VBAP9MVGR4.
ALTMP1079 = VBAP9MVGR5.
ALTMP1080 = VBAP9KMPMG.
ALTMP1081 = VBAP9SUGRD.
ALTMP1082 = VBAP9SOBKZ.
ALTMP1083 = VBAP9VPZUO.
ALTMP1084 = VBAP9PAOBJNR.
ALTMP1085 = VBAP9PS_PSP_PNR.
ALTMP1086 = VBAP9AUFNR.
ALTMP1087 = VBAP9VPMAT.
ALTMP1088 = VBAP9VPWRK.
ALTMP1089 = VBAP9PRBME.
ALTMP1090 = VBAP9UMREF.
ALTMP1091 = VBAP9KNTTP.
ALTMP1092 = VBAP9KZVBR.
ALTMP1093 = VBAP9SERNR.
ALTMP1094 = VBAP9OBJNR.
ALTMP1095 = VBAP9ABGRS.
ALTMP1096 = VBAP9BEDAE.
ALTMP1097 = VBAP9CMPRE.
ALTMP1098 = VBAP9CMTFG.
ALTMP1099 = VBAP9CMPNT.
ALTMP1100 = VBAP9CMKUA.
ALTMP1101 = VBAP9CUOBJ.
ALTMP1102 = VBAP9CUOBJ_CH.
ALTMP1103 = VBAP9CEPOK.
ALTMP1104 = VBAP9KOUPD.
ALTMP1105 = VBAP9SERAIL.
ALTMP1106 = VBAP9ANZSN.
ALTMP1107 = VBAP9NACHL.
ALTMP1108 = VBAP9MAGRV.
ALTMP1109 = VBAP9MPROK.
ALTMP1110 = VBAP9VGTYP.
ALTMP1111 = VBAP9PROSA.
ALTMP1112 = VBAP9UEPVW.
ALTMP1113 = VBAP9KALNR.
ALTMP1114 = VBAP9KLVAR.
ALTMP1115 = VBAP9SPOSN.
ALTMP1116 = VBAP9KOWRR.
ALTMP1117 = VBAP9STADAT.
ALTMP1118 = VBAP9EXART.
ALTMP1119 = VBAP9PREFE.
ALTMP1120 = VBAP9KNUMH.
ALTMP1121 = VBAP9CLINT.
ALTMP1122 = VBAP9CHMVS.
ALTMP1123 = VBAP9STLTY.
ALTMP1124 = VBAP9STLKN.
ALTMP1125 = VBAP9STPOZ.
ALTMP1126 = VBAP9STMAN.
ALTMP1127 = VBAP9ZSCHL_K.
ALTMP1128 = VBAP9KALSM_K.
ALTMP1129 = VBAP9KALVAR.
ALTMP1130 = VBAP9KOSCH.
ALTMP1131 = VBAP9UPMAT.
ALTMP1132 = VBAP9UKONM.
ALTMP1133 = VBAP9MFRGR.
ALTMP1134 = VBAP9PLAVO.
ALTMP1135 = VBAP9KANNR.
ALTMP1136 = VBAP9CMPRE_FLT.
ALTMP1137 = VBAP9ABFOR.
ALTMP1138 = VBAP9ABGES.
ALTMP1139 = VBAP9J_1BCFOP.
ALTMP1140 = VBAP9J_1BTAXLW1.
ALTMP1141 = VBAP9J_1BTAXLW2.
ALTMP1142 = VBAP9J_1BTXSDC.
ALTMP1143 = VBAP9WKTNR.
ALTMP1144 = VBAP9WKTPS.
ALTMP1145 = VBAP9SKOPF.
ALTMP1146 = VBAP9KZBWS.
ALTMP1147 = VBAP9WGRU1.
ALTMP1148 = VBAP9WGRU2.
ALTMP1149 = VBAP9KNUMA_PI.
ALTMP1150 = VBAP9KNUMA_AG.
ALTMP1151 = VBAP9KZFME.
ALTMP1152 = VBAP9LSTANR.
ALTMP1153 = VBAP9TECHS.
ALTMP1154 = VBAP9MWSBP.
ALTMP1155 = VBAP9BERID.
ALTMP1156 = VBAP9PCTRF.
ALTMP1157 = VBAP9LOGSYS_EXT.
ALTMP1158 = VBAP9J_1BTAXLW3.
ALTMP1159 = VBAP9J_1BTAXLW4.
ALTMP1160 = VBAP9J_1BTAXLW5.
ALTMP1161 = VBAP9STOCKLOC.
ALTMP1162 = VBAP9SLOCTYPE.
ALTMP1163 = VBAP9MSR_RET_REASON.
ALTMP1164 = VBAP9MSR_REFUND_CODE.
ALTMP1165 = VBAP9MSR_APPROV_BLOCK.
ALTMP1166 = VBAP9NRAB_KNUMH.
ALTMP1167 = VBAP9TC_AUT_DET.
ALTMP1168 = VBAP9MANUAL_TC_REASON.
ALTMP1169 = VBAP9FISCAL_INCENTIVE.
ALTMP1170 = VBAP9TAX_SUBJECT_ST.
ALTMP1171 = VBAP9FISCAL_INCENTIVE_ID.
ALTMP1172 = VBAP9SPCSTO.
ALTMP1173 = VBAP9REVACC_REFID.
ALTMP1174 = VBAP9REVACC_REFTYPE.
ALTMP1175 = VBAP9SESSION_CREATION_DATE.
ALTMP1176 = VBAP9SESSION_CREATION_TIME.
ALTMP1177 = VBAP9GLO_LOG_REF1_IT.
ALTMP1178 = VBAP9/BEV1/SRFUND.
ALTMP1179 = VBAP9AUFPL_OLC.
ALTMP1180 = VBAP9APLZL_OLC.
ALTMP1181 = VBAP9FERC_IND.
ALTMP1182 = VBAP9KOSTL.
ALTMP1183 = VBAP9FONDS.
ALTMP1184 = VBAP9FISTL.
ALTMP1185 = VBAP9FKBER.
ALTMP1186 = VBAP9GRANT_NBR.
ALTMP1187 = VBAP9BUDGET_PD.
ALTMP1188 = VBAP9IUID_RELEVANT.
ALTMP1189 = VBAP9MILL_SE_GPOSN.
ALTMP1190 = VBAP9PRS_OBJNR.
ALTMP1191 = VBAP9PRS_SD_SPSNR.
ALTMP1192 = VBAP9PRS_WORK_PERIOD.
ALTMP1193 = VBAP9TAS.
ALTMP1194 = VBAP9BETC.
ALTMP1195 = VBAP9MOD_ALLOW.
ALTMP1196 = VBAP9CANCEL_ALLOW.
ALTMP1197 = VBAP9PAY_METHOD.
ALTMP1198 = VBAP9BPN.
ALTMP1199 = VBAP9REP_FREQ.
ALTMP1200 = VBAP9FMFGUS_KEY.
ALTMP1201 = VBAP9PARGB.
ALTMP1202 = VBAP9AUFPL_OAA.
ALTMP1203 = VBAP9APLZL_OAA.
ALTMP1204 = VBAP9ARSNUM.
ALTMP1205 = VBAP9ARSPOS.
ALTMP1206 = VBAP9WTYSC_CLMITEM.
 move ALTMP952 to ITAB3-MANDT.
 move ALTMP953 to ITAB3-VBELN.
 move ALTMP954 to ITAB3-POSNR.
 move ALTMP955 to ITAB3-MATNR.
 move ALTMP956 to ITAB3-MATWA.
 move ALTMP957 to ITAB3-PMATN.
 move ALTMP958 to ITAB3-CHARG.
 move ALTMP959 to ITAB3-MATKL.
 move ALTMP960 to ITAB3-ARKTX.
 move ALTMP961 to ITAB3-PSTYV.
 move ALTMP962 to ITAB3-POSAR.
 move ALTMP963 to ITAB3-LFREL.
 move ALTMP964 to ITAB3-FKREL.
 move ALTMP965 to ITAB3-UEPOS.
 move ALTMP966 to ITAB3-GRPOS.
 move ALTMP967 to ITAB3-ABGRU.
 move ALTMP968 to ITAB3-PRODH.
 move ALTMP969 to ITAB3-ZWERT.
 move ALTMP970 to ITAB3-ZMENG.
 move ALTMP971 to ITAB3-ZIEME.
 move ALTMP972 to ITAB3-UMZIZ.
 move ALTMP973 to ITAB3-UMZIN.
 move ALTMP974 to ITAB3-MEINS.
 move ALTMP975 to ITAB3-SMENG.
 move ALTMP976 to ITAB3-ABLFZ.
 move ALTMP977 to ITAB3-ABDAT.
 move ALTMP978 to ITAB3-ABSFZ.
 move ALTMP979 to ITAB3-POSEX.
 move ALTMP980 to ITAB3-KDMAT.
 move ALTMP981 to ITAB3-KBVER.
 move ALTMP982 to ITAB3-KEVER.
 move ALTMP983 to ITAB3-VKGRU.
 move ALTMP984 to ITAB3-VKAUS.
 move ALTMP985 to ITAB3-GRKOR.
 move ALTMP986 to ITAB3-FMENG.
 move ALTMP987 to ITAB3-UEBTK.
 move ALTMP988 to ITAB3-UEBTO.
 move ALTMP989 to ITAB3-UNTTO.
 move ALTMP990 to ITAB3-FAKSP.
 move ALTMP991 to ITAB3-ATPKZ.
 move ALTMP992 to ITAB3-RKFKF.
 move ALTMP993 to ITAB3-SPART.
 move ALTMP994 to ITAB3-GSBER.
 move ALTMP995 to ITAB3-NETWR.
 move ALTMP996 to ITAB3-WAERK.
 move ALTMP997 to ITAB3-ANTLF.
 move ALTMP998 to ITAB3-KZTLF.
 move ALTMP999 to ITAB3-CHSPL.
 move ALTMP1000 to ITAB3-KWMENG.
 move ALTMP1001 to ITAB3-LSMENG.
 move ALTMP1002 to ITAB3-KBMENG.
 move ALTMP1003 to ITAB3-KLMENG.
 move ALTMP1004 to ITAB3-VRKME.
 move ALTMP1005 to ITAB3-UMVKZ.
 move ALTMP1006 to ITAB3-UMVKN.
 move ALTMP1007 to ITAB3-BRGEW.
 move ALTMP1008 to ITAB3-NTGEW.
 move ALTMP1009 to ITAB3-GEWEI.
 move ALTMP1010 to ITAB3-VOLUM.
 move ALTMP1011 to ITAB3-VOLEH.
 move ALTMP1012 to ITAB3-VBELV.
 move ALTMP1013 to ITAB3-POSNV.
 move ALTMP1014 to ITAB3-VGBEL.
 move ALTMP1015 to ITAB3-VGPOS.
 move ALTMP1016 to ITAB3-VOREF.
 move ALTMP1017 to ITAB3-UPFLU.
 move ALTMP1018 to ITAB3-ERLRE.
 move ALTMP1019 to ITAB3-LPRIO.
 move ALTMP1020 to ITAB3-WERKS.
 move ALTMP1021 to ITAB3-LGORT.
 move ALTMP1022 to ITAB3-VSTEL.
 move ALTMP1023 to ITAB3-ROUTE.
 move ALTMP1024 to ITAB3-STKEY.
 move ALTMP1025 to ITAB3-STDAT.
 move ALTMP1026 to ITAB3-STLNR.
 move ALTMP1027 to ITAB3-STPOS.
 move ALTMP1028 to ITAB3-AWAHR.
 move ALTMP1029 to ITAB3-ERDAT.
 move ALTMP1030 to ITAB3-ERNAM.
 move ALTMP1031 to ITAB3-ERZET.
 move ALTMP1032 to ITAB3-TAXM1.
 move ALTMP1033 to ITAB3-TAXM2.
 move ALTMP1034 to ITAB3-TAXM3.
 move ALTMP1035 to ITAB3-TAXM4.
 move ALTMP1036 to ITAB3-TAXM5.
 move ALTMP1037 to ITAB3-TAXM6.
 move ALTMP1038 to ITAB3-TAXM7.
 move ALTMP1039 to ITAB3-TAXM8.
 move ALTMP1040 to ITAB3-TAXM9.
 move ALTMP1041 to ITAB3-VBEAF.
 move ALTMP1042 to ITAB3-VBEAV.
 move ALTMP1043 to ITAB3-VGREF.
 move ALTMP1044 to ITAB3-NETPR.
 move ALTMP1045 to ITAB3-KPEIN.
 move ALTMP1046 to ITAB3-KMEIN.
 move ALTMP1047 to ITAB3-SHKZG.
 move ALTMP1048 to ITAB3-SKTOF.
 move ALTMP1049 to ITAB3-MTVFP.
 move ALTMP1050 to ITAB3-SUMBD.
 move ALTMP1051 to ITAB3-KONDM.
 move ALTMP1052 to ITAB3-KTGRM.
 move ALTMP1053 to ITAB3-BONUS.
 move ALTMP1054 to ITAB3-PROVG.
 move ALTMP1055 to ITAB3-EANNR.
 move ALTMP1056 to ITAB3-PRSOK.
 move ALTMP1057 to ITAB3-BWTAR.
 move ALTMP1058 to ITAB3-BWTEX.
 move ALTMP1059 to ITAB3-XCHPF.
 move ALTMP1060 to ITAB3-XCHAR.
 move ALTMP1061 to ITAB3-LFMNG.
 move ALTMP1062 to ITAB3-STAFO.
 move ALTMP1063 to ITAB3-WAVWR.
 move ALTMP1064 to ITAB3-KZWI1.
 move ALTMP1065 to ITAB3-KZWI2.
 move ALTMP1066 to ITAB3-KZWI3.
 move ALTMP1067 to ITAB3-KZWI4.
 move ALTMP1068 to ITAB3-KZWI5.
 move ALTMP1069 to ITAB3-KZWI6.
 move ALTMP1070 to ITAB3-STCUR.
 move ALTMP1071 to ITAB3-AEDAT.
 move ALTMP1072 to ITAB3-EAN11.
 move ALTMP1073 to ITAB3-FIXMG.
 move ALTMP1074 to ITAB3-PRCTR.
 move ALTMP1075 to ITAB3-MVGR1.
 move ALTMP1076 to ITAB3-MVGR2.
 move ALTMP1077 to ITAB3-MVGR3.
 move ALTMP1078 to ITAB3-MVGR4.
 move ALTMP1079 to ITAB3-MVGR5.
 move ALTMP1080 to ITAB3-KMPMG.
 move ALTMP1081 to ITAB3-SUGRD.
 move ALTMP1082 to ITAB3-SOBKZ.
 move ALTMP1083 to ITAB3-VPZUO.
 move ALTMP1084 to ITAB3-PAOBJNR.
 move ALTMP1085 to ITAB3-PS_PSP_PNR.
 move ALTMP1086 to ITAB3-AUFNR.
 move ALTMP1087 to ITAB3-VPMAT.
 move ALTMP1088 to ITAB3-VPWRK.
 move ALTMP1089 to ITAB3-PRBME.
 move ALTMP1090 to ITAB3-UMREF.
 move ALTMP1091 to ITAB3-KNTTP.
 move ALTMP1092 to ITAB3-KZVBR.
 move ALTMP1093 to ITAB3-SERNR.
 move ALTMP1094 to ITAB3-OBJNR.
 move ALTMP1095 to ITAB3-ABGRS.
 move ALTMP1096 to ITAB3-BEDAE.
 move ALTMP1097 to ITAB3-CMPRE.
 move ALTMP1098 to ITAB3-CMTFG.
 move ALTMP1099 to ITAB3-CMPNT.
 move ALTMP1100 to ITAB3-CMKUA.
 move ALTMP1101 to ITAB3-CUOBJ.
 move ALTMP1102 to ITAB3-CUOBJ_CH.
 move ALTMP1103 to ITAB3-CEPOK.
 move ALTMP1104 to ITAB3-KOUPD.
 move ALTMP1105 to ITAB3-SERAIL.
 move ALTMP1106 to ITAB3-ANZSN.
 move ALTMP1107 to ITAB3-NACHL.
 move ALTMP1108 to ITAB3-MAGRV.
 move ALTMP1109 to ITAB3-MPROK.
 move ALTMP1110 to ITAB3-VGTYP.
 move ALTMP1111 to ITAB3-PROSA.
 move ALTMP1112 to ITAB3-UEPVW.
 move ALTMP1113 to ITAB3-KALNR.
 move ALTMP1114 to ITAB3-KLVAR.
 move ALTMP1115 to ITAB3-SPOSN.
 move ALTMP1116 to ITAB3-KOWRR.
 move ALTMP1117 to ITAB3-STADAT.
 move ALTMP1118 to ITAB3-EXART.
 move ALTMP1119 to ITAB3-PREFE.
 move ALTMP1120 to ITAB3-KNUMH.
 move ALTMP1121 to ITAB3-CLINT.
 move ALTMP1122 to ITAB3-CHMVS.
 move ALTMP1123 to ITAB3-STLTY.
 move ALTMP1124 to ITAB3-STLKN.
 move ALTMP1125 to ITAB3-STPOZ.
 move ALTMP1126 to ITAB3-STMAN.
 move ALTMP1127 to ITAB3-ZSCHL_K.
 move ALTMP1128 to ITAB3-KALSM_K.
 move ALTMP1129 to ITAB3-KALVAR.
 move ALTMP1130 to ITAB3-KOSCH.
 move ALTMP1131 to ITAB3-UPMAT.
 move ALTMP1132 to ITAB3-UKONM.
 move ALTMP1133 to ITAB3-MFRGR.
 move ALTMP1134 to ITAB3-PLAVO.
 move ALTMP1135 to ITAB3-KANNR.
 move ALTMP1136 to ITAB3-CMPRE_FLT.
 move ALTMP1137 to ITAB3-ABFOR.
 move ALTMP1138 to ITAB3-ABGES.
 move ALTMP1139 to ITAB3-J_1BCFOP.
 move ALTMP1140 to ITAB3-J_1BTAXLW1.
 move ALTMP1141 to ITAB3-J_1BTAXLW2.
 move ALTMP1142 to ITAB3-J_1BTXSDC.
 move ALTMP1143 to ITAB3-WKTNR.
 move ALTMP1144 to ITAB3-WKTPS.
 move ALTMP1145 to ITAB3-SKOPF.
 move ALTMP1146 to ITAB3-KZBWS.
 move ALTMP1147 to ITAB3-WGRU1.
 move ALTMP1148 to ITAB3-WGRU2.
 move ALTMP1149 to ITAB3-KNUMA_PI.
 move ALTMP1150 to ITAB3-KNUMA_AG.
 move ALTMP1151 to ITAB3-KZFME.
 move ALTMP1152 to ITAB3-LSTANR.
 move ALTMP1153 to ITAB3-TECHS.
 move ALTMP1154 to ITAB3-MWSBP.
 move ALTMP1155 to ITAB3-BERID.
 move ALTMP1156 to ITAB3-PCTRF.
 move ALTMP1157 to ITAB3-LOGSYS_EXT.
 move ALTMP1158 to ITAB3-J_1BTAXLW3.
 move ALTMP1159 to ITAB3-J_1BTAXLW4.
 move ALTMP1160 to ITAB3-J_1BTAXLW5.
 move ALTMP1161 to ITAB3-STOCKLOC.
 move ALTMP1162 to ITAB3-SLOCTYPE.
 move ALTMP1163 to ITAB3-MSR_RET_REASON.
 move ALTMP1164 to ITAB3-MSR_REFUND_CODE.
 move ALTMP1165 to ITAB3-MSR_APPROV_BLOCK.
 move ALTMP1166 to ITAB3-NRAB_KNUMH.
 move ALTMP1167 to ITAB3-TC_AUT_DET.
 move ALTMP1168 to ITAB3-MANUAL_TC_REASON.
 move ALTMP1169 to ITAB3-FISCAL_INCENTIVE.
 move ALTMP1170 to ITAB3-TAX_SUBJECT_ST.
 move ALTMP1171 to ITAB3-FISCAL_INCENTIVE_ID.
 move ALTMP1172 to ITAB3-SPCSTO.
 move ALTMP1173 to ITAB3-REVACC_REFID.
 move ALTMP1174 to ITAB3-REVACC_REFTYPE.
 move ALTMP1175 to ITAB3-SESSION_CREATION_DATE.
 move ALTMP1176 to ITAB3-SESSION_CREATION_TIME.
 move ALTMP1177 to ITAB3-GLO_LOG_REF1_IT.
 move ALTMP1178 to ITAB3-/BEV1/SRFUND.
 move ALTMP1179 to ITAB3-AUFPL_OLC.
 move ALTMP1180 to ITAB3-APLZL_OLC.
 move ALTMP1181 to ITAB3-FERC_IND.
 move ALTMP1182 to ITAB3-KOSTL.
 move ALTMP1183 to ITAB3-FONDS.
 move ALTMP1184 to ITAB3-FISTL.
 move ALTMP1185 to ITAB3-FKBER.
 move ALTMP1186 to ITAB3-GRANT_NBR.
 move ALTMP1187 to ITAB3-BUDGET_PD.
 move ALTMP1188 to ITAB3-IUID_RELEVANT.
 move ALTMP1189 to ITAB3-MILL_SE_GPOSN.
 move ALTMP1190 to ITAB3-PRS_OBJNR.
 move ALTMP1191 to ITAB3-PRS_SD_SPSNR.
 move ALTMP1192 to ITAB3-PRS_WORK_PERIOD.
 move ALTMP1193 to ITAB3-TAS.
 move ALTMP1194 to ITAB3-BETC.
 move ALTMP1195 to ITAB3-MOD_ALLOW.
 move ALTMP1196 to ITAB3-CANCEL_ALLOW.
 move ALTMP1197 to ITAB3-PAY_METHOD.
 move ALTMP1198 to ITAB3-BPN.
 move ALTMP1199 to ITAB3-REP_FREQ.
 move ALTMP1200 to ITAB3-FMFGUS_KEY.
 move ALTMP1201 to ITAB3-PARGB.
 move ALTMP1202 to ITAB3-AUFPL_OAA.
 move ALTMP1203 to ITAB3-APLZL_OAA.
 move ALTMP1204 to ITAB3-ARSNUM.
 move ALTMP1205 to ITAB3-ARSPOS.
 move ALTMP1206 to ITAB3-WTYSC_CLMITEM.
 append ITAB3.
 cntbuf = cntbuf + 1.
 if download = 'N'.
  if cntbuf > 5000.
    perform FORM4.
    clear cntbuf.
    refresh ITAB3.
    append_flag = 'A'.
  endif.
 endif.
 if download = 'S'.
  if cntbuf > P_PKGSZ.
    perform FORM4.
    clear cntbuf.
    refresh ITAB3.
  endif.
 endif.
ENDSELECT.
ENDFORM.

FORM FORM4.
data: outfile(512), ldfile(50).
ldfile = 'Z_SAPDS_Extract_VBAP'.
concatenate out_dir ldfile into outfile
  separated by '/'.
  IF DOWNLOAD = 'S'.
     DATA: error_message(700),mtext(800),iEOP(1).
     CALL FUNCTION P_SRVFM
          DESTINATION P_DEST
          KEEPING LOGICAL UNIT OF WORK
          EXPORTING
            EOS = last_batch
          IMPORTING
            EOP = iEOP
          TABLES
            E_TABLE = ITAB3
          EXCEPTIONS
            READ_ERROR = 1
            SYSTEM_FAILURE = 2
            MESSAGE error_message
            COMMUNICATION_FAILURE = 3
            MESSAGE error_message
            OTHERS = 4.

     IF sy-subrc ne 0.
        Case sy-subrc.
        when 1.
        CONCATENATE
        'Data Services read error. '
        'Check Data Services error log.'
        INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 2.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 3.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 4.
        MESSAGE  E240(S#) WITH
'Other SAP System Failure while calling DS remote function.'.
        endcase.
      ENDIF.
      IF iEOP = 'X'.
         PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
         LEAVE PROGRAM.
       ENDIF.
  ELSE.
data  dlmtlen type i value '1'.
data xdlmtlen type i value '1'.
data:
  ht(1) type c,
  xht(1) type x,
  conv type ref to cl_abap_conv_in_ce.
xht = '7F'.
conv = cl_abap_conv_in_ce=>create(
  encoding = '1100'
  input = xht
).
call method conv->read(
  exporting n    = xdlmtlen
  importing data = ht
            len = dlmtlen
).
data return_code type i.
 perform write_delimited_file
           tables   ITAB3
           using    outfile
                    append_flag
                    ht
                    dlmtlen
                    download
           changing return_code.

  case return_code.
    when 1.
      IF EXECMODE = 'D'.
        WRITE: /5 'No line selected'.
      ELSE.
        MESSAGE E047(S#).
      ENDIF.
    when 2.
      IF EXECMODE = 'D'.
        WRITE: /5 'Open File Error -- ', 25 OUTFILE.
      ELSE.
        MESSAGE  E084(E0) WITH OUTFILE.
      ENDIF.
    when 3.
      IF EXECMODE = 'D'.
        WRITE: /5 'Data exceed length limit (8192) '.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Data exceed length limit (8192) '.
      ENDIF.
    when 4.
      IF EXECMODE = 'D'.
        WRITE: /5 'Call function WS_DOWNLOAD error'.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Call function WS_DOWNLOAD error'.
      ENDIF.
  endcase.
 ENDIF.
ENDFORM.

FORM SUBSTRING USING SRC BEG LEN CHANGING RET.

DATA: VA1 TYPE I.
DATA: VA2 TYPE I.
DATA: VA3 TYPE I.

VA3 = STRLEN( SRC ).

IF  BEG = 0.   VA1 = 0.
ELSE.
  IF  BEG < 0.
    VA1 = VA3 + BEG.
    IF  VA1 < 0.   VA1 = 0.
    ENDIF.
  ELSE.          VA1 = BEG - 1.
  ENDIF.
ENDIF.

IF  LEN < 0.   VA2 = 0.
ELSE.          VA2 = VA3 - VA1.
ENDIF.

IF  VA2 > LEN. VA2 = LEN.
ENDIF.

IF  VA2 < 1.   MOVE ''           TO RET.
ELSE.          MOVE SRC+VA1(VA2) TO RET.
ENDIF.

ENDFORM.

form write_delimited_file
           tables   datatab
           using    file
                    append
                    delimit
                    dlength
                    dwnload
          changing rc.

  data: type1,
        appd(1),
        temp(32),
        time1(8),
        date1(10),
        output(8192),
        rcount type i,
        offset type i,
        tablen type i,
        maxlen type i value '8192'.

  data: begin of clientab occurs 0,
             output(8192),
          end of clientab.

  field-symbols: <f>.
  field-symbols <delim1>.
  data delim2(16).
  data l_filename type string.

  appd = append.
  if appd is not initial.
     appd = 'X'.
  endif.
  move file to l_filename.
  describe table datatab lines tablen.


  if dwnload = 'Y'.
     clear clientab. refresh clientab.
     rcount = 0.
  else.
     if appd = space.
   open dataset file for output in text mode ENCODING UTF-8.
     else.
    open dataset file for appending in text mode ENCODING UTF-8.
     endif.
     if sy-subrc <> 0.
         rc = 2. exit.
     endif.
  endif.

  loop at datatab.
    clear: tablen, offset, output.
    do.
      assign component sy-index of
         structure datatab to <f>.
      if sy-subrc <> 0. exit. endif.
      if sy-index > 1.
         assign delimit(dlength) TO <delim1> CASTING TYPE C.
         delim2 = <delim1>.
         write delim2(dlength) to output+offset(dlength).
         add dlength to offset.
      endif.

      describe field <f> type type1.

      if type1 = 'I' or type1 = 'N'.
          type1 = 'P'.
      endif.

      case type1.
        when 'D'.
          if <f> = '00000000'.
             <f> = ' '.
          else.
             move <f> to time1.
             assign time1 to <f>.
          endif.
        when 'F'.
          if <f> = '0.0'.
            temp = '0.0'.
          else.
             write <f> to temp exponent 0.
          endif.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
        when 'P'.
          if <f> < 0.
             write '-' to output+offset(1).
             add 1 to offset.
             <f> = <f> * ( -1 ).
          endif.
          move <f> to temp.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
      endcase.

      sy-fdpos = strlen( <f> ).

      tablen = offset + sy-fdpos.
      if tablen > maxlen.
         rc = 3. exit.
      endif.
      write <f> to output+offset(sy-fdpos).
      add sy-fdpos to offset.
    enddo.

    if dwnload = 'Y'.
       clientab-output = output.
       append clientab.
       rcount = rcount + 1.
       if rcount >= 50.
          SY-BATCH = SPACE.
          CALL FUNCTION 'GUI_DOWNLOAD'
            EXPORTING
              FILENAME = l_filename
              FILETYPE = 'ASC'
              CODEPAGE = '4110'
              APPEND   = appd
              WRITE_FIELD_SEPARATOR = 'X'
*            IMPORTING
*              FILELENGTH =
            TABLES
              DATA_TAB = clientab
            EXCEPTIONS
              OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
          clear clientab. refresh clientab.
          rcount = 0. appd = 'A'.
       endif.
    else.
       transfer output to file.
    endif.
  endloop.

  if dwnload = 'Y'.
       SY-BATCH = SPACE.
       CALL FUNCTION 'GUI_DOWNLOAD'
         EXPORTING
           FILENAME = l_filename
           FILETYPE = 'ASC'
              CODEPAGE = '4110'
           APPEND   = appd
           WRITE_FIELD_SEPARATOR = 'X'
*         IMPORTING
*           FILELENGTH =
         TABLES
           DATA_TAB = clientab
         EXCEPTIONS
           OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
  else.
       close dataset file.
  endif.
endform.

FORM CONNECT_RFCDEST_TO_PROGID.
 INCLUDE rfctypes.

 DATA: len     type i,
       R3NAME(4),
       SYSTNR(2),
       uid     LIKE SYS_UID,
       options LIKE RFCOPT,
       isunicode  TYPE n.

 DATA: NTOTAL     LIKE GWY_STRUCT-NOREG,
       GWY_GWHOST LIKE GWY_STRUCT-GWHOST,
       GWY_GWSERV LIKE GWY_STRUCT-GWSERV,
       GWY_TPNAME LIKE GWY_SYSTEM-TPNAME.

 TABLES: RFCSI.

* Check program ID
 IF P_PROGID = SPACE.
    RAISE INVALID_PROGRAM_ID.
 ENDIF.

* determine if the RFC destination authority
  CALL FUNCTION 'RFC_READ_TCPIP_DESTINATION'
       EXPORTING destination = P_DEST
                 authority_check = 'X'
  IMPORTING rfcunicode = isunicode.

* Use current gateway if no info exits
 IF P_GWHOST = SPACE OR P_GWSERV = SPACE.
  CALL FUNCTION 'RFC_SYSTEM_INFO'
      IMPORTING
          RFCSI_EXPORT = RFCSI.

  len = strlen( rfcsi-rfcdest ) - 2.
  systnr = rfcsi-rfcdest+len.
  len = len - 1 - 3.
  r3name = rfcsi-rfcdest+len(3).
  len = len - 1.
  options-rfcgwhost = rfcsi-rfcdest(len).
  CONCATENATE 'sapgw' SYSTNR INTO options-rfcgwserv.
 ELSE.
   options-rfcgwhost = P_GWHOST.
   options-rfcgwserv = P_GWSERV.
 ENDIF.

* Parameters for GWY function call
  GWY_GWHOST = OPTIONS-RFCGWHOST.
  GWY_GWSERV = OPTIONS-RFCGWSERV.
  GWY_TPNAME = P_PROGID.

  DO 10 TIMES.

* Check gateway and server program registered
  CALL FUNCTION 'GWY_GET_NO_REG_PROGRAMS'
     EXPORTING
        GWHOST      = GWY_GWHOST
        GWSERV      = GWY_GWSERV
        TPNAME      = GWY_TPNAME
     IMPORTING
        NOREG_TOTAL = NTOTAL
     EXCEPTIONS
        OTHERS      = 1.

  IF sy-subrc NE 0.
     raise CONNECT_TO_GATEWAY_FAILED.
  ENDIF.

  IF NTOTAL GT 0.
     EXIT.
  ENDIF.

  CALL FUNCTION 'ENQUE_SLEEP'
     EXPORTING
        SECONDS     = 15.

  ENDDO.

  IF NTOTAL = 0.
     raise SERVER_NOT_REGISTERED.
  ENDIF.

  IF NTOTAL GT 1.
     raise DUPLICATE_REG_PROGRAMS.
  ENDIF.

* build new connection to a registered server
  options-rfcexec   = gwy_tpname.
  options-rfcgwhost = gwy_gwhost.
  options-rfcgwserv = gwy_gwserv.
  options-rfchost   = '%%RFCSERVER%%'.
  IF P_SNC_ON = 'X'.
    options-rfcsnc  = 'X'.
  ENDIF.

  CALL 'RFCControl' ID 'CODE' FIELD 'O'
                    ID 'DESTINATION' FIELD P_DEST
                    ID 'TYPE' FIELD rfctype_external_tcp
                    ID 'OPTIONS' FIELD options.

  IF sy-subrc NE 0.
     RAISE CONNECT_TO_REG_SERVER_FAILED.
   ENDIF.

* and set exclusive mode to keep server owned
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
      EXPORTING  destination = P_DEST
                 exclusiv    = 'Y'
      EXCEPTIONS connect_to_reg_server_failed = 1
                 exclusiv_not_supported       = 2.

  IF SY-SUBRC NE 0.
     CASE SY-SUBRC.
          WHEN 1.
              RAISE CONNECT_TO_REG_SERVER_FAILED.
          WHEN 2.
              RAISE EXCLUSIV_NOT_SUPPORTED.
     ENDCASE.
  ENDIF.

ENDFORM.

FORM DISCONNECT_RFCDEST_FROM_PROGID.
* set exclusive mode to E to end the session
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
     EXPORTING
         destination = P_DEST
         exclusiv    = 'E'
     EXCEPTIONS
         connect_to_reg_server_failed = 1
         exclusiv_not_supported       = 2.
ENDFORM.
