REPORT Z_SAPDS_EXTRACT_LIPS message-id 26 line-size 255
no standard page heading.
* Z_SAPDS_Extract_LIPS.
PARAMETER DOWNLOAD(1) DEFAULT 'S' lower case. "N-svr,Y-clnt
PARAMETER EXECMODE(1) DEFAULT 'D' lower case. "D-dlg,B-btch
PARAMETER OUT_DIR(230) DEFAULT "output file dir
'\\chobisdv\' lower case.
PARAMETER IN_DIR(230) DEFAULT "input file dir
'\\chobisdv\' lower case.
PARAMETER P_DEST TYPE RFCDES-RFCDEST DEFAULT
'NONE'.
PARAMETER P_PROGID TYPE RFCOPT-RFCEXEC DEFAULT
SPACE.
PARAMETER P_GWHOST TYPE RFCOPT-RFCGWHOST DEFAULT
SPACE.
PARAMETER P_GWSERV TYPE RFCOPT-RFCGWSERV DEFAULT
SPACE.
PARAMETER P_SRVFM(30) DEFAULT "Server Callback function
SPACE.
PARAMETER P_PKGSZ TYPE I DEFAULT "Stream package size
5000.
PARAMETER P_SNC_ON(1) DEFAULT "X-on SPACE-off
SPACE.

PARAMETER $PARAM1 TYPE D.

PARAMETER $PARAM2 TYPE D.

PARAMETER P_DF_VK(40) DEFAULT "ABAP data flow object key
'' lower case.
PARAMETER P_DI_GEN(40) DEFAULT "DI version that generated ABAP
'' lower case.

*** Machine generated ABAP. Do not modify.            ***
*** (C)Copyright Business Objects S.A.  All rights reserved. ***
*
* Date Time:
*    08/18/23 10:02:46
* SAP used for generated this ABAP:
*    Release: 702
*    Host   : chobisdv
*
* ABAP Dataflow Name:
*    Z_SAPDS_Extract_LIPS
* ABAP program name in SAP:
*  Z_SAPDS_EXTRACT_LIPS
* Generated ABAP file name:
*    D:/temp/Z_SAPDS_Extract_LIPS
TABLES LIKP.
TABLES LIPS.

DATA: begin of ITAB3 occurs 0,
MANDT(3) TYPE C,
VBELN(10) TYPE C,
POSNR(6) TYPE N,
PSTYV(4) TYPE C,
ERNAM(12) TYPE C,
ERZET TYPE T,
ERDAT TYPE D,
MATNR(18) TYPE C,
MATWA(18) TYPE C,
MATKL(9) TYPE C,
WERKS(4) TYPE C,
LGORT(4) TYPE C,
CHARG(10) TYPE C,
LICHN(15) TYPE C,
KDMAT(35) TYPE C,
PRODH(18) TYPE C,
LFIMG(16) TYPE P DECIMALS 3,
MEINS(3) TYPE C,
VRKME(3) TYPE C,
UMVKZ(16) TYPE P DECIMALS 0,
UMVKN(16) TYPE P DECIMALS 0,
NTGEW(16) TYPE P DECIMALS 3,
BRGEW(16) TYPE P DECIMALS 3,
GEWEI(3) TYPE C,
VOLUM(16) TYPE P DECIMALS 3,
VOLEH(3) TYPE C,
KZTLF(1) TYPE C,
UEBTK(1) TYPE C,
UEBTO(16) TYPE P DECIMALS 1,
UNTTO(16) TYPE P DECIMALS 1,
CHSPL(1) TYPE C,
FAKSP(2) TYPE C,
MBDAT TYPE D,
LGMNG(16) TYPE P DECIMALS 3,
ARKTX(40) TYPE C,
LGPBE(10) TYPE C,
VBELV(10) TYPE C,
POSNV(6) TYPE N,
VBTYV(1) TYPE C,
VGSYS(10) TYPE C,
VGBEL(10) TYPE C,
VGPOS(6) TYPE N,
UPFLU(1) TYPE C,
UEPOS(6) TYPE N,
FKREL(1) TYPE C,
LADGR(4) TYPE C,
TRAGR(4) TYPE C,
KOMKZ(1) TYPE C,
LGNUM(3) TYPE C,
LISPL(1) TYPE C,
LGTYP(3) TYPE C,
LGPLA(10) TYPE C,
BWTEX(1) TYPE C,
BWART(3) TYPE C,
BWLVS(3) TYPE N,
KZDLG(1) TYPE C,
BDART(2) TYPE C,
PLART(1) TYPE C,
MTART(4) TYPE C,
XCHPF(1) TYPE C,
XCHAR(1) TYPE C,
VGREF(1) TYPE C,
POSAR(1) TYPE C,
BWTAR(10) TYPE C,
SUMBD(1) TYPE C,
MTVFP(2) TYPE C,
EANNR(13) TYPE C,
GSBER(4) TYPE C,
VKBUR(4) TYPE C,
VKGRP(3) TYPE C,
VTWEG(2) TYPE C,
SPART(2) TYPE C,
GRKOR(3) TYPE N,
FMENG(1) TYPE C,
ANTLF(16) TYPE P DECIMALS 0,
VBEAF(16) TYPE P DECIMALS 2,
VBEAV(16) TYPE P DECIMALS 2,
STAFO(6) TYPE C,
WAVWR(16) TYPE P DECIMALS 2,
KZWI1(16) TYPE P DECIMALS 2,
KZWI2(16) TYPE P DECIMALS 2,
KZWI3(16) TYPE P DECIMALS 2,
KZWI4(16) TYPE P DECIMALS 2,
KZWI5(16) TYPE P DECIMALS 2,
KZWI6(16) TYPE P DECIMALS 2,
SOBKZ(1) TYPE C,
AEDAT TYPE D,
EAN11(18) TYPE C,
KVGR1(3) TYPE C,
KVGR2(3) TYPE C,
KVGR3(3) TYPE C,
KVGR4(3) TYPE C,
KVGR5(3) TYPE C,
MVGR1(3) TYPE C,
MVGR2(3) TYPE C,
MVGR3(3) TYPE C,
MVGR4(3) TYPE C,
MVGR5(3) TYPE C,
VPZUO(1) TYPE C,
VGTYP(1) TYPE C,
RFVGTYP(1) TYPE C,
KOSTL(10) TYPE C,
KOKRS(4) TYPE C,
PAOBJNR(10) TYPE N,
PRCTR(10) TYPE C,
PS_PSP_PNR(8) TYPE N,
AUFNR(12) TYPE C,
POSNR_PP(4) TYPE N,
KDAUF(10) TYPE C,
KDPOS(6) TYPE N,
VPMAT(18) TYPE C,
VPWRK(4) TYPE C,
PRBME(3) TYPE C,
UMREF TYPE F,
KNTTP(1) TYPE C,
KZVBR(1) TYPE C,
FIPOS(14) TYPE C,
FISTL(16) TYPE C,
GEBER(10) TYPE C,
PCKPF(1) TYPE C,
BEDAR_LF(3) TYPE C,
CMPNT(1) TYPE C,
KCMENG(16) TYPE P DECIMALS 3,
KCBRGEW(16) TYPE P DECIMALS 3,
KCNTGEW(16) TYPE P DECIMALS 3,
KCVOLUM(16) TYPE P DECIMALS 3,
UECHA(6) TYPE N,
CUOBJ(18) TYPE N,
CUOBJ_CH(18) TYPE N,
ANZSN TYPE I,
SERAIL(4) TYPE C,
KCGEWEI(3) TYPE C,
KCVOLEH(3) TYPE C,
SERNR(8) TYPE C,
ABRLI(4) TYPE N,
ABART(1) TYPE C,
ABRVW(3) TYPE C,
QPLOS(12) TYPE N,
QTLOS(6) TYPE N,
NACHL(1) TYPE C,
MAGRV(4) TYPE C,
OBJKO(22) TYPE C,
OBJPO(22) TYPE C,
AESKD(17) TYPE C,
SHKZG(1) TYPE C,
PROSA(1) TYPE C,
UEPVW(1) TYPE C,
EMPST(25) TYPE C,
ABTNR(4) TYPE C,
KOQUI(1) TYPE C,
STADAT TYPE D,
AKTNR(10) TYPE C,
KNUMH_CH(10) TYPE C,
PREFE(1) TYPE C,
EXART(2) TYPE C,
CLINT(10) TYPE N,
CHMVS(3) TYPE N,
ABELN(10) TYPE C,
ABELP(5) TYPE N,
LFIMG_FLO TYPE F,
LGMNG_FLO TYPE F,
KCMENG_FLO TYPE F,
KZUMW(1) TYPE C,
KMPMG(16) TYPE P DECIMALS 3,
AUREL(1) TYPE C,
KPEIN(16) TYPE P DECIMALS 0,
KMEIN(3) TYPE C,
NETPR(16) TYPE P DECIMALS 2,
NETWR(16) TYPE P DECIMALS 2,
KOWRR(1) TYPE C,
KZBEW(1) TYPE C,
MFRGR(8) TYPE C,
CHHPV(1) TYPE C,
ABFOR(2) TYPE C,
ABGES TYPE F,
MBUHR TYPE T,
WKTNR(10) TYPE C,
WKTPS(6) TYPE N,
J_1BCFOP(10) TYPE C,
J_1BTAXLW1(3) TYPE C,
J_1BTAXLW2(3) TYPE C,
J_1BTXSDC(2) TYPE C,
SITUA(2) TYPE C,
RSNUM(10) TYPE N,
RSPOS(4) TYPE N,
RSART(1) TYPE C,
KANNR(35) TYPE C,
KZFME(1) TYPE C,
PROFL(3) TYPE C,
KCMENGVME(16) TYPE P DECIMALS 3,
KCMENGVMEF TYPE F,
KZBWS(1) TYPE C,
PSPNR(8) TYPE N,
EPRIO(4) TYPE C,
RULES(4) TYPE C,
KZBEF(1) TYPE C,
MPROF(4) TYPE C,
EMATN(18) TYPE C,
LGBZO(10) TYPE C,
HANDLE(22) TYPE C,
VERURPOS(6) TYPE N,
LIFEXPOS(6) TYPE N,
NOATP(1) TYPE C,
NOPCK(1) TYPE C,
RBLVS(3) TYPE N,
BERID(10) TYPE C,
BESTQ(1) TYPE C,
UMBSQ(1) TYPE C,
UMMAT(18) TYPE C,
UMWRK(4) TYPE C,
UMLGO(4) TYPE C,
UMCHA(10) TYPE C,
UMBAR(10) TYPE C,
UMSOK(1) TYPE C,
SONUM(16) TYPE C,
USONU(16) TYPE C,
AKKUR(16) TYPE P DECIMALS 5,
AKMNG(1) TYPE C,
VKGRU(3) TYPE C,
SHKZG_UM(1) TYPE C,
INSMK(1) TYPE C,
KZECH(1) TYPE C,
FLGWM(1) TYPE C,
BERKZ(1) TYPE C,
HUPOS(1) TYPE C,
NOWAB(1) TYPE C,
KONTO(10) TYPE C,
KZEAR(1) TYPE C,
HSDAT TYPE D,
VFDAT TYPE D,
LFGJA(4) TYPE N,
LFBNR(10) TYPE C,
LFPOS(4) TYPE N,
GRUND(4) TYPE N,
FOBWA(3) TYPE C,
DLVTP(2) TYPE C,
EXBWR(16) TYPE P DECIMALS 2,
BPMNG(16) TYPE P DECIMALS 3,
EXVKW(16) TYPE P DECIMALS 2,
CMPRE_FLT TYPE F,
KZPOD(1) TYPE C,
LFDEZ(1) TYPE C,
UMREV TYPE F,
PODREL(1) TYPE C,
KZUML(1) TYPE C,
FKBER(16) TYPE C,
GRANT_NBR(20) TYPE C,
KZWSO(1) TYPE C,
GMCONTROL(1) TYPE C,
POSTING_CHANGE(1) TYPE C,
UM_PS_PSP_PNR(8) TYPE N,
PRE_VL_ETENS(4) TYPE N,
SPE_GEN_ELIKZ(1) TYPE C,
SPE_SCRAP_IND(1) TYPE C,
SPE_AUTH_NUMBER(20) TYPE C,
SPE_INSPOUT_GUID(32) TYPE C,
SPE_FOLLOW_UP(4) TYPE C,
SPE_EXP_DATE_EXT(16) TYPE P DECIMALS 0,
SPE_EXP_DATE_INT(16) TYPE P DECIMALS 0,
SPE_AUTH_COMPLET(1) TYPE C,
ORMNG(16) TYPE P DECIMALS 3,
SPE_ATP_TMSTMP(16) TYPE P DECIMALS 0,
SPE_ORIG_SYS(1) TYPE C,
SPE_LIEFFZ(16) TYPE P DECIMALS 3,
SPE_IMWRK(1) TYPE C,
SPE_LIFEXPOS2(35) TYPE C,
SPE_EXCEPT_CODE(4) TYPE C,
SPE_KEEP_QTY(16) TYPE P DECIMALS 3,
SPE_ALTERNATE(40) TYPE C,
SPE_MAT_SUBST(1) TYPE C,
SPE_STRUC(3) TYPE N,
SPE_APO_QNTYFAC(16) TYPE P DECIMALS 0,
SPE_APO_QNTYDIV(16) TYPE P DECIMALS 0,
SPE_HERKL(3) TYPE C,
SPE_BXP_DATE_EXT(16) TYPE P DECIMALS 0,
SPE_VERSION(4) TYPE N,
SPE_COMPL_MVT(1) TYPE C,
J_1BTAXLW4(3) TYPE C,
J_1BTAXLW5(3) TYPE C,
J_1BTAXLW3(3) TYPE C,
BUDGET_PD(10) TYPE C,
KBNKZ(1) TYPE C,
FARR_RELTYPE(10) TYPE C,
SITKZ(1) TYPE C,
CONS_ORDER(1) TYPE C.
DATA: end of ITAB3.

data: append_flag(1) value ' ',
      cntbuf type i,
      delimleng type i,last_batch(1) value ' '.

CONSTANTS C_DF_VK(40) VALUE '530'.
CONSTANTS C_DI_GEN(40) VALUE '14.2.14.3160'.
DATA WARN_MSG(50).


start-of-selection.


  IF DOWNLOAD = 'S' OR
     DOWNLOAD = 'N' OR
     DOWNLOAD = 'Y'.
      .
  ELSE.
     DATA: m_xfer_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'data transfer method: ' DOWNLOAD
'. Regenerate the ABAP program and upload to this system.'
     INTO m_xfer_err_msg.
     MESSAGE  E240(S#) WITH m_xfer_err_msg.
  ENDIF.

  IF EXECMODE = 'B' OR
     EXECMODE = 'D'.
      .
  ELSE.
     DATA: m_exec_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'execution option: ' EXECMODE
'. Regenerate the ABAP program and upload to this system.'
     INTO m_exec_err_msg.
     MESSAGE  E240(S#) WITH m_exec_err_msg.
  ENDIF.

  IF DOWNLOAD = 'S'.
     PERFORM CONNECT_RFCDEST_TO_PROGID.
  ENDIF.



PERFORM FORM3.
last_batch = 'X'.
PERFORM FORM4.
FREE ITAB3.
  IF DOWNLOAD = 'S'.
     PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
  ENDIF.


end-of-selection.

CLEAR WARN_MSG.

IF NOT P_DF_VK IS INITIAL.
  IF P_DF_VK <> C_DF_VK.
     CONCATENATE '$$Warning$'
                 C_DF_VK
                 '$' INTO WARN_MSG.
  ENDIF.
ENDIF.
IF NOT P_DI_GEN IS INITIAL.
  IF P_DI_GEN <> C_DI_GEN.
     IF WARN_MSG IS INITIAL.
       CONCATENATE '$$Warning$$'
                   C_DI_GEN
                   INTO WARN_MSG.
     ELSE.
       CONCATENATE WARN_MSG
                   C_DI_GEN
                   INTO WARN_MSG.
     ENDIF.
  ENDIF.
ENDIF.

IF NOT WARN_MSG IS INITIAL.
  IF EXECMODE = 'D'.
    WRITE WARN_MSG.
    NEW-LINE.
  ELSE.
    MESSAGE S240(S#) with WARN_MSG.
  ENDIF.
ENDIF.


write  '* Program Complete *'.
write  '(C)Copyright Business Objects S.A.  All rights reserved.'.

FORM FORM3.
DATA ALTMP667(3) TYPE C.
DATA ALTMP668(10) TYPE C.
DATA ALTMP669(6) TYPE N.
DATA ALTMP670(4) TYPE C.
DATA ALTMP671(12) TYPE C.
DATA ALTMP672 TYPE T.
DATA ALTMP673 TYPE D.
DATA ALTMP674(18) TYPE C.
DATA ALTMP675(18) TYPE C.
DATA ALTMP676(9) TYPE C.
DATA ALTMP677(4) TYPE C.
DATA ALTMP678(4) TYPE C.
DATA ALTMP679(10) TYPE C.
DATA ALTMP680(15) TYPE C.
DATA ALTMP681(35) TYPE C.
DATA ALTMP682(18) TYPE C.
DATA ALTMP683(16) TYPE P DECIMALS 3.
DATA ALTMP684(3) TYPE C.
DATA ALTMP685(3) TYPE C.
DATA ALTMP686(16) TYPE P DECIMALS 0.
DATA ALTMP687(16) TYPE P DECIMALS 0.
DATA ALTMP688(16) TYPE P DECIMALS 3.
DATA ALTMP689(16) TYPE P DECIMALS 3.
DATA ALTMP690(3) TYPE C.
DATA ALTMP691(16) TYPE P DECIMALS 3.
DATA ALTMP692(3) TYPE C.
DATA ALTMP693(1) TYPE C.
DATA ALTMP694(1) TYPE C.
DATA ALTMP695(16) TYPE P DECIMALS 1.
DATA ALTMP696(16) TYPE P DECIMALS 1.
DATA ALTMP697(1) TYPE C.
DATA ALTMP698(2) TYPE C.
DATA ALTMP699 TYPE D.
DATA ALTMP700(16) TYPE P DECIMALS 3.
DATA ALTMP701(40) TYPE C.
DATA ALTMP702(10) TYPE C.
DATA ALTMP703(10) TYPE C.
DATA ALTMP704(6) TYPE N.
DATA ALTMP705(1) TYPE C.
DATA ALTMP706(10) TYPE C.
DATA ALTMP707(10) TYPE C.
DATA ALTMP708(6) TYPE N.
DATA ALTMP709(1) TYPE C.
DATA ALTMP710(6) TYPE N.
DATA ALTMP711(1) TYPE C.
DATA ALTMP712(4) TYPE C.
DATA ALTMP713(4) TYPE C.
DATA ALTMP714(1) TYPE C.
DATA ALTMP715(3) TYPE C.
DATA ALTMP716(1) TYPE C.
DATA ALTMP717(3) TYPE C.
DATA ALTMP718(10) TYPE C.
DATA ALTMP719(1) TYPE C.
DATA ALTMP720(3) TYPE C.
DATA ALTMP721(3) TYPE N.
DATA ALTMP722(1) TYPE C.
DATA ALTMP723(2) TYPE C.
DATA ALTMP724(1) TYPE C.
DATA ALTMP725(4) TYPE C.
DATA ALTMP726(1) TYPE C.
DATA ALTMP727(1) TYPE C.
DATA ALTMP728(1) TYPE C.
DATA ALTMP729(1) TYPE C.
DATA ALTMP730(10) TYPE C.
DATA ALTMP731(1) TYPE C.
DATA ALTMP732(2) TYPE C.
DATA ALTMP733(13) TYPE C.
DATA ALTMP734(4) TYPE C.
DATA ALTMP735(4) TYPE C.
DATA ALTMP736(3) TYPE C.
DATA ALTMP737(2) TYPE C.
DATA ALTMP738(2) TYPE C.
DATA ALTMP739(3) TYPE N.
DATA ALTMP740(1) TYPE C.
DATA ALTMP741(16) TYPE P DECIMALS 0.
DATA ALTMP742(16) TYPE P DECIMALS 2.
DATA ALTMP743(16) TYPE P DECIMALS 2.
DATA ALTMP744(6) TYPE C.
DATA ALTMP745(16) TYPE P DECIMALS 2.
DATA ALTMP746(16) TYPE P DECIMALS 2.
DATA ALTMP747(16) TYPE P DECIMALS 2.
DATA ALTMP748(16) TYPE P DECIMALS 2.
DATA ALTMP749(16) TYPE P DECIMALS 2.
DATA ALTMP750(16) TYPE P DECIMALS 2.
DATA ALTMP751(16) TYPE P DECIMALS 2.
DATA ALTMP752(1) TYPE C.
DATA ALTMP753 TYPE D.
DATA ALTMP754(18) TYPE C.
DATA ALTMP755(3) TYPE C.
DATA ALTMP756(3) TYPE C.
DATA ALTMP757(3) TYPE C.
DATA ALTMP758(3) TYPE C.
DATA ALTMP759(3) TYPE C.
DATA ALTMP760(3) TYPE C.
DATA ALTMP761(3) TYPE C.
DATA ALTMP762(3) TYPE C.
DATA ALTMP763(3) TYPE C.
DATA ALTMP764(3) TYPE C.
DATA ALTMP765(1) TYPE C.
DATA ALTMP766(1) TYPE C.
DATA ALTMP767(1) TYPE C.
DATA ALTMP768(10) TYPE C.
DATA ALTMP769(4) TYPE C.
DATA ALTMP770(10) TYPE N.
DATA ALTMP771(10) TYPE C.
DATA ALTMP772(8) TYPE N.
DATA ALTMP773(12) TYPE C.
DATA ALTMP774(4) TYPE N.
DATA ALTMP775(10) TYPE C.
DATA ALTMP776(6) TYPE N.
DATA ALTMP777(18) TYPE C.
DATA ALTMP778(4) TYPE C.
DATA ALTMP779(3) TYPE C.
DATA ALTMP780 TYPE F.
DATA ALTMP781(1) TYPE C.
DATA ALTMP782(1) TYPE C.
DATA ALTMP783(14) TYPE C.
DATA ALTMP784(16) TYPE C.
DATA ALTMP785(10) TYPE C.
DATA ALTMP786(1) TYPE C.
DATA ALTMP787(3) TYPE C.
DATA ALTMP788(1) TYPE C.
DATA ALTMP789(16) TYPE P DECIMALS 3.
DATA ALTMP790(16) TYPE P DECIMALS 3.
DATA ALTMP791(16) TYPE P DECIMALS 3.
DATA ALTMP792(16) TYPE P DECIMALS 3.
DATA ALTMP793(6) TYPE N.
DATA ALTMP794(18) TYPE N.
DATA ALTMP795(18) TYPE N.
DATA ALTMP796 TYPE I.
DATA ALTMP797(4) TYPE C.
DATA ALTMP798(3) TYPE C.
DATA ALTMP799(3) TYPE C.
DATA ALTMP800(8) TYPE C.
DATA ALTMP801(4) TYPE N.
DATA ALTMP802(1) TYPE C.
DATA ALTMP803(3) TYPE C.
DATA ALTMP804(12) TYPE N.
DATA ALTMP805(6) TYPE N.
DATA ALTMP806(1) TYPE C.
DATA ALTMP807(4) TYPE C.
DATA ALTMP808(22) TYPE C.
DATA ALTMP809(22) TYPE C.
DATA ALTMP810(17) TYPE C.
DATA ALTMP811(1) TYPE C.
DATA ALTMP812(1) TYPE C.
DATA ALTMP813(1) TYPE C.
DATA ALTMP814(25) TYPE C.
DATA ALTMP815(4) TYPE C.
DATA ALTMP816(1) TYPE C.
DATA ALTMP817 TYPE D.
DATA ALTMP818(10) TYPE C.
DATA ALTMP819(10) TYPE C.
DATA ALTMP820(1) TYPE C.
DATA ALTMP821(2) TYPE C.
DATA ALTMP822(10) TYPE N.
DATA ALTMP823(3) TYPE N.
DATA ALTMP824(10) TYPE C.
DATA ALTMP825(5) TYPE N.
DATA ALTMP826 TYPE F.
DATA ALTMP827 TYPE F.
DATA ALTMP828 TYPE F.
DATA ALTMP829(1) TYPE C.
DATA ALTMP830(16) TYPE P DECIMALS 3.
DATA ALTMP831(1) TYPE C.
DATA ALTMP832(16) TYPE P DECIMALS 0.
DATA ALTMP833(3) TYPE C.
DATA ALTMP834(16) TYPE P DECIMALS 2.
DATA ALTMP835(16) TYPE P DECIMALS 2.
DATA ALTMP836(1) TYPE C.
DATA ALTMP837(1) TYPE C.
DATA ALTMP838(8) TYPE C.
DATA ALTMP839(1) TYPE C.
DATA ALTMP840(2) TYPE C.
DATA ALTMP841 TYPE F.
DATA ALTMP842 TYPE T.
DATA ALTMP843(10) TYPE C.
DATA ALTMP844(6) TYPE N.
DATA ALTMP845(10) TYPE C.
DATA ALTMP846(3) TYPE C.
DATA ALTMP847(3) TYPE C.
DATA ALTMP848(2) TYPE C.
DATA ALTMP849(2) TYPE C.
DATA ALTMP850(10) TYPE N.
DATA ALTMP851(4) TYPE N.
DATA ALTMP852(1) TYPE C.
DATA ALTMP853(35) TYPE C.
DATA ALTMP854(1) TYPE C.
DATA ALTMP855(3) TYPE C.
DATA ALTMP856(16) TYPE P DECIMALS 3.
DATA ALTMP857 TYPE F.
DATA ALTMP858(1) TYPE C.
DATA ALTMP859(8) TYPE N.
DATA ALTMP860(4) TYPE C.
DATA ALTMP861(4) TYPE C.
DATA ALTMP862(1) TYPE C.
DATA ALTMP863(4) TYPE C.
DATA ALTMP864(18) TYPE C.
DATA ALTMP865(10) TYPE C.
DATA ALTMP866(22) TYPE C.
DATA ALTMP867(6) TYPE N.
DATA ALTMP868(6) TYPE N.
DATA ALTMP869(1) TYPE C.
DATA ALTMP870(1) TYPE C.
DATA ALTMP871(3) TYPE N.
DATA ALTMP872(10) TYPE C.
DATA ALTMP873(1) TYPE C.
DATA ALTMP874(1) TYPE C.
DATA ALTMP875(18) TYPE C.
DATA ALTMP876(4) TYPE C.
DATA ALTMP877(4) TYPE C.
DATA ALTMP878(10) TYPE C.
DATA ALTMP879(10) TYPE C.
DATA ALTMP880(1) TYPE C.
DATA ALTMP881(16) TYPE C.
DATA ALTMP882(16) TYPE C.
DATA ALTMP883(16) TYPE P DECIMALS 5.
DATA ALTMP884(1) TYPE C.
DATA ALTMP885(3) TYPE C.
DATA ALTMP886(1) TYPE C.
DATA ALTMP887(1) TYPE C.
DATA ALTMP888(1) TYPE C.
DATA ALTMP889(1) TYPE C.
DATA ALTMP890(1) TYPE C.
DATA ALTMP891(1) TYPE C.
DATA ALTMP892(1) TYPE C.
DATA ALTMP893(10) TYPE C.
DATA ALTMP894(1) TYPE C.
DATA ALTMP895 TYPE D.
DATA ALTMP896 TYPE D.
DATA ALTMP897(4) TYPE N.
DATA ALTMP898(10) TYPE C.
DATA ALTMP899(4) TYPE N.
DATA ALTMP900(4) TYPE N.
DATA ALTMP901(3) TYPE C.
DATA ALTMP902(2) TYPE C.
DATA ALTMP903(16) TYPE P DECIMALS 2.
DATA ALTMP904(16) TYPE P DECIMALS 3.
DATA ALTMP905(16) TYPE P DECIMALS 2.
DATA ALTMP906 TYPE F.
DATA ALTMP907(1) TYPE C.
DATA ALTMP908(1) TYPE C.
DATA ALTMP909 TYPE F.
DATA ALTMP910(1) TYPE C.
DATA ALTMP911(1) TYPE C.
DATA ALTMP912(16) TYPE C.
DATA ALTMP913(20) TYPE C.
DATA ALTMP914(1) TYPE C.
DATA ALTMP915(1) TYPE C.
DATA ALTMP916(1) TYPE C.
DATA ALTMP917(8) TYPE N.
DATA ALTMP918(4) TYPE N.
DATA ALTMP919(1) TYPE C.
DATA ALTMP920(1) TYPE C.
DATA ALTMP921(20) TYPE C.
DATA ALTMP922(32) TYPE C.
DATA ALTMP923(4) TYPE C.
DATA ALTMP924(16) TYPE P DECIMALS 0.
DATA ALTMP925(16) TYPE P DECIMALS 0.
DATA ALTMP926(1) TYPE C.
DATA ALTMP927(16) TYPE P DECIMALS 3.
DATA ALTMP928(16) TYPE P DECIMALS 0.
DATA ALTMP929(1) TYPE C.
DATA ALTMP930(16) TYPE P DECIMALS 3.
DATA ALTMP931(1) TYPE C.
DATA ALTMP932(35) TYPE C.
DATA ALTMP933(4) TYPE C.
DATA ALTMP934(16) TYPE P DECIMALS 3.
DATA ALTMP935(40) TYPE C.
DATA ALTMP936(1) TYPE C.
DATA ALTMP937(3) TYPE N.
DATA ALTMP938(16) TYPE P DECIMALS 0.
DATA ALTMP939(16) TYPE P DECIMALS 0.
DATA ALTMP940(3) TYPE C.
DATA ALTMP941(16) TYPE P DECIMALS 0.
DATA ALTMP942(4) TYPE N.
DATA ALTMP943(1) TYPE C.
DATA ALTMP944(3) TYPE C.
DATA ALTMP945(3) TYPE C.
DATA ALTMP946(3) TYPE C.
DATA ALTMP947(10) TYPE C.
DATA ALTMP948(1) TYPE C.
DATA ALTMP949(10) TYPE C.
DATA ALTMP950(1) TYPE C.
DATA ALTMP951(1) TYPE C.

DATA LIPS9MANDT LIKE LIPS-MANDT.
DATA LIPS9VBELN LIKE LIPS-VBELN.
DATA LIPS9POSNR LIKE LIPS-POSNR.
DATA LIPS9PSTYV LIKE LIPS-PSTYV.
DATA LIPS9ERNAM LIKE LIPS-ERNAM.
DATA LIPS9ERZET LIKE LIPS-ERZET.
DATA LIPS9ERDAT LIKE LIPS-ERDAT.
DATA LIPS9MATNR LIKE LIPS-MATNR.
DATA LIPS9MATWA LIKE LIPS-MATWA.
DATA LIPS9MATKL LIKE LIPS-MATKL.
DATA LIPS9WERKS LIKE LIPS-WERKS.
DATA LIPS9LGORT LIKE LIPS-LGORT.
DATA LIPS9CHARG LIKE LIPS-CHARG.
DATA LIPS9LICHN LIKE LIPS-LICHN.
DATA LIPS9KDMAT LIKE LIPS-KDMAT.
DATA LIPS9PRODH LIKE LIPS-PRODH.
DATA LIPS9LFIMG LIKE LIPS-LFIMG.
DATA LIPS9MEINS LIKE LIPS-MEINS.
DATA LIPS9VRKME LIKE LIPS-VRKME.
DATA LIPS9UMVKZ LIKE LIPS-UMVKZ.
DATA LIPS9UMVKN LIKE LIPS-UMVKN.
DATA LIPS9NTGEW LIKE LIPS-NTGEW.
DATA LIPS9BRGEW LIKE LIPS-BRGEW.
DATA LIPS9GEWEI LIKE LIPS-GEWEI.
DATA LIPS9VOLUM LIKE LIPS-VOLUM.
DATA LIPS9VOLEH LIKE LIPS-VOLEH.
DATA LIPS9KZTLF LIKE LIPS-KZTLF.
DATA LIPS9UEBTK LIKE LIPS-UEBTK.
DATA LIPS9UEBTO LIKE LIPS-UEBTO.
DATA LIPS9UNTTO LIKE LIPS-UNTTO.
DATA LIPS9CHSPL LIKE LIPS-CHSPL.
DATA LIPS9FAKSP LIKE LIPS-FAKSP.
DATA LIPS9MBDAT LIKE LIPS-MBDAT.
DATA LIPS9LGMNG LIKE LIPS-LGMNG.
DATA LIPS9ARKTX LIKE LIPS-ARKTX.
DATA LIPS9LGPBE LIKE LIPS-LGPBE.
DATA LIPS9VBELV LIKE LIPS-VBELV.
DATA LIPS9POSNV LIKE LIPS-POSNV.
DATA LIPS9VBTYV LIKE LIPS-VBTYV.
DATA LIPS9VGSYS LIKE LIPS-VGSYS.
DATA LIPS9VGBEL LIKE LIPS-VGBEL.
DATA LIPS9VGPOS LIKE LIPS-VGPOS.
DATA LIPS9UPFLU LIKE LIPS-UPFLU.
DATA LIPS9UEPOS LIKE LIPS-UEPOS.
DATA LIPS9FKREL LIKE LIPS-FKREL.
DATA LIPS9LADGR LIKE LIPS-LADGR.
DATA LIPS9TRAGR LIKE LIPS-TRAGR.
DATA LIPS9KOMKZ LIKE LIPS-KOMKZ.
DATA LIPS9LGNUM LIKE LIPS-LGNUM.
DATA LIPS9LISPL LIKE LIPS-LISPL.
DATA LIPS9LGTYP LIKE LIPS-LGTYP.
DATA LIPS9LGPLA LIKE LIPS-LGPLA.
DATA LIPS9BWTEX LIKE LIPS-BWTEX.
DATA LIPS9BWART LIKE LIPS-BWART.
DATA LIPS9BWLVS LIKE LIPS-BWLVS.
DATA LIPS9KZDLG LIKE LIPS-KZDLG.
DATA LIPS9BDART LIKE LIPS-BDART.
DATA LIPS9PLART LIKE LIPS-PLART.
DATA LIPS9MTART LIKE LIPS-MTART.
DATA LIPS9XCHPF LIKE LIPS-XCHPF.
DATA LIPS9XCHAR LIKE LIPS-XCHAR.
DATA LIPS9VGREF LIKE LIPS-VGREF.
DATA LIPS9POSAR LIKE LIPS-POSAR.
DATA LIPS9BWTAR LIKE LIPS-BWTAR.
DATA LIPS9SUMBD LIKE LIPS-SUMBD.
DATA LIPS9MTVFP LIKE LIPS-MTVFP.
DATA LIPS9EANNR LIKE LIPS-EANNR.
DATA LIPS9GSBER LIKE LIPS-GSBER.
DATA LIPS9VKBUR LIKE LIPS-VKBUR.
DATA LIPS9VKGRP LIKE LIPS-VKGRP.
DATA LIPS9VTWEG LIKE LIPS-VTWEG.
DATA LIPS9SPART LIKE LIPS-SPART.
DATA LIPS9GRKOR LIKE LIPS-GRKOR.
DATA LIPS9FMENG LIKE LIPS-FMENG.
DATA LIPS9ANTLF LIKE LIPS-ANTLF.
DATA LIPS9VBEAF LIKE LIPS-VBEAF.
DATA LIPS9VBEAV LIKE LIPS-VBEAV.
DATA LIPS9STAFO LIKE LIPS-STAFO.
DATA LIPS9WAVWR LIKE LIPS-WAVWR.
DATA LIPS9KZWI1 LIKE LIPS-KZWI1.
DATA LIPS9KZWI2 LIKE LIPS-KZWI2.
DATA LIPS9KZWI3 LIKE LIPS-KZWI3.
DATA LIPS9KZWI4 LIKE LIPS-KZWI4.
DATA LIPS9KZWI5 LIKE LIPS-KZWI5.
DATA LIPS9KZWI6 LIKE LIPS-KZWI6.
DATA LIPS9SOBKZ LIKE LIPS-SOBKZ.
DATA LIPS9AEDAT LIKE LIPS-AEDAT.
DATA LIPS9EAN11 LIKE LIPS-EAN11.
DATA LIPS9KVGR1 LIKE LIPS-KVGR1.
DATA LIPS9KVGR2 LIKE LIPS-KVGR2.
DATA LIPS9KVGR3 LIKE LIPS-KVGR3.
DATA LIPS9KVGR4 LIKE LIPS-KVGR4.
DATA LIPS9KVGR5 LIKE LIPS-KVGR5.
DATA LIPS9MVGR1 LIKE LIPS-MVGR1.
DATA LIPS9MVGR2 LIKE LIPS-MVGR2.
DATA LIPS9MVGR3 LIKE LIPS-MVGR3.
DATA LIPS9MVGR4 LIKE LIPS-MVGR4.
DATA LIPS9MVGR5 LIKE LIPS-MVGR5.
DATA LIPS9VPZUO LIKE LIPS-VPZUO.
DATA LIPS9VGTYP LIKE LIPS-VGTYP.
DATA LIPS9RFVGTYP LIKE LIPS-RFVGTYP.
DATA LIPS9KOSTL LIKE LIPS-KOSTL.
DATA LIPS9KOKRS LIKE LIPS-KOKRS.
DATA LIPS9PAOBJNR LIKE LIPS-PAOBJNR.
DATA LIPS9PRCTR LIKE LIPS-PRCTR.
DATA LIPS9PS_PSP_PNR LIKE LIPS-PS_PSP_PNR.
DATA LIPS9AUFNR LIKE LIPS-AUFNR.
DATA LIPS9POSNR_PP LIKE LIPS-POSNR_PP.
DATA LIPS9KDAUF LIKE LIPS-KDAUF.
DATA LIPS9KDPOS LIKE LIPS-KDPOS.
DATA LIPS9VPMAT LIKE LIPS-VPMAT.
DATA LIPS9VPWRK LIKE LIPS-VPWRK.
DATA LIPS9PRBME LIKE LIPS-PRBME.
DATA LIPS9UMREF LIKE LIPS-UMREF.
DATA LIPS9KNTTP LIKE LIPS-KNTTP.
DATA LIPS9KZVBR LIKE LIPS-KZVBR.
DATA LIPS9FIPOS LIKE LIPS-FIPOS.
DATA LIPS9FISTL LIKE LIPS-FISTL.
DATA LIPS9GEBER LIKE LIPS-GEBER.
DATA LIPS9PCKPF LIKE LIPS-PCKPF.
DATA LIPS9BEDAR_LF LIKE LIPS-BEDAR_LF.
DATA LIPS9CMPNT LIKE LIPS-CMPNT.
DATA LIPS9KCMENG LIKE LIPS-KCMENG.
DATA LIPS9KCBRGEW LIKE LIPS-KCBRGEW.
DATA LIPS9KCNTGEW LIKE LIPS-KCNTGEW.
DATA LIPS9KCVOLUM LIKE LIPS-KCVOLUM.
DATA LIPS9UECHA LIKE LIPS-UECHA.
DATA LIPS9CUOBJ LIKE LIPS-CUOBJ.
DATA LIPS9CUOBJ_CH LIKE LIPS-CUOBJ_CH.
DATA LIPS9ANZSN LIKE LIPS-ANZSN.
DATA LIPS9SERAIL LIKE LIPS-SERAIL.
DATA LIPS9KCGEWEI LIKE LIPS-KCGEWEI.
DATA LIPS9KCVOLEH LIKE LIPS-KCVOLEH.
DATA LIPS9SERNR LIKE LIPS-SERNR.
DATA LIPS9ABRLI LIKE LIPS-ABRLI.
DATA LIPS9ABART LIKE LIPS-ABART.
DATA LIPS9ABRVW LIKE LIPS-ABRVW.
DATA LIPS9QPLOS LIKE LIPS-QPLOS.
DATA LIPS9QTLOS LIKE LIPS-QTLOS.
DATA LIPS9NACHL LIKE LIPS-NACHL.
DATA LIPS9MAGRV LIKE LIPS-MAGRV.
DATA LIPS9OBJKO LIKE LIPS-OBJKO.
DATA LIPS9OBJPO LIKE LIPS-OBJPO.
DATA LIPS9AESKD LIKE LIPS-AESKD.
DATA LIPS9SHKZG LIKE LIPS-SHKZG.
DATA LIPS9PROSA LIKE LIPS-PROSA.
DATA LIPS9UEPVW LIKE LIPS-UEPVW.
DATA LIPS9EMPST LIKE LIPS-EMPST.
DATA LIPS9ABTNR LIKE LIPS-ABTNR.
DATA LIPS9KOQUI LIKE LIPS-KOQUI.
DATA LIPS9STADAT LIKE LIPS-STADAT.
DATA LIPS9AKTNR LIKE LIPS-AKTNR.
DATA LIPS9KNUMH_CH LIKE LIPS-KNUMH_CH.
DATA LIPS9PREFE LIKE LIPS-PREFE.
DATA LIPS9EXART LIKE LIPS-EXART.
DATA LIPS9CLINT LIKE LIPS-CLINT.
DATA LIPS9CHMVS LIKE LIPS-CHMVS.
DATA LIPS9ABELN LIKE LIPS-ABELN.
DATA LIPS9ABELP LIKE LIPS-ABELP.
DATA LIPS9LFIMG_FLO LIKE LIPS-LFIMG_FLO.
DATA LIPS9LGMNG_FLO LIKE LIPS-LGMNG_FLO.
DATA LIPS9KCMENG_FLO LIKE LIPS-KCMENG_FLO.
DATA LIPS9KZUMW LIKE LIPS-KZUMW.
DATA LIPS9KMPMG LIKE LIPS-KMPMG.
DATA LIPS9AUREL LIKE LIPS-AUREL.
DATA LIPS9KPEIN LIKE LIPS-KPEIN.
DATA LIPS9KMEIN LIKE LIPS-KMEIN.
DATA LIPS9NETPR LIKE LIPS-NETPR.
DATA LIPS9NETWR LIKE LIPS-NETWR.
DATA LIPS9KOWRR LIKE LIPS-KOWRR.
DATA LIPS9KZBEW LIKE LIPS-KZBEW.
DATA LIPS9MFRGR LIKE LIPS-MFRGR.
DATA LIPS9CHHPV LIKE LIPS-CHHPV.
DATA LIPS9ABFOR LIKE LIPS-ABFOR.
DATA LIPS9ABGES LIKE LIPS-ABGES.
DATA LIPS9MBUHR LIKE LIPS-MBUHR.
DATA LIPS9WKTNR LIKE LIPS-WKTNR.
DATA LIPS9WKTPS LIKE LIPS-WKTPS.
DATA LIPS9J_1BCFOP LIKE LIPS-J_1BCFOP.
DATA LIPS9J_1BTAXLW1 LIKE LIPS-J_1BTAXLW1.
DATA LIPS9J_1BTAXLW2 LIKE LIPS-J_1BTAXLW2.
DATA LIPS9J_1BTXSDC LIKE LIPS-J_1BTXSDC.
DATA LIPS9SITUA LIKE LIPS-SITUA.
DATA LIPS9RSNUM LIKE LIPS-RSNUM.
DATA LIPS9RSPOS LIKE LIPS-RSPOS.
DATA LIPS9RSART LIKE LIPS-RSART.
DATA LIPS9KANNR LIKE LIPS-KANNR.
DATA LIPS9KZFME LIKE LIPS-KZFME.
DATA LIPS9PROFL LIKE LIPS-PROFL.
DATA LIPS9KCMENGVME LIKE LIPS-KCMENGVME.
DATA LIPS9KCMENGVMEF LIKE LIPS-KCMENGVMEF.
DATA LIPS9KZBWS LIKE LIPS-KZBWS.
DATA LIPS9PSPNR LIKE LIPS-PSPNR.
DATA LIPS9EPRIO LIKE LIPS-EPRIO.
DATA LIPS9RULES LIKE LIPS-RULES.
DATA LIPS9KZBEF LIKE LIPS-KZBEF.
DATA LIPS9MPROF LIKE LIPS-MPROF.
DATA LIPS9EMATN LIKE LIPS-EMATN.
DATA LIPS9LGBZO LIKE LIPS-LGBZO.
DATA LIPS9HANDLE LIKE LIPS-HANDLE.
DATA LIPS9VERURPOS LIKE LIPS-VERURPOS.
DATA LIPS9LIFEXPOS LIKE LIPS-LIFEXPOS.
DATA LIPS9NOATP LIKE LIPS-NOATP.
DATA LIPS9NOPCK LIKE LIPS-NOPCK.
DATA LIPS9RBLVS LIKE LIPS-RBLVS.
DATA LIPS9BERID LIKE LIPS-BERID.
DATA LIPS9BESTQ LIKE LIPS-BESTQ.
DATA LIPS9UMBSQ LIKE LIPS-UMBSQ.
DATA LIPS9UMMAT LIKE LIPS-UMMAT.
DATA LIPS9UMWRK LIKE LIPS-UMWRK.
DATA LIPS9UMLGO LIKE LIPS-UMLGO.
DATA LIPS9UMCHA LIKE LIPS-UMCHA.
DATA LIPS9UMBAR LIKE LIPS-UMBAR.
DATA LIPS9UMSOK LIKE LIPS-UMSOK.
DATA LIPS9SONUM LIKE LIPS-SONUM.
DATA LIPS9USONU LIKE LIPS-USONU.
DATA LIPS9AKKUR LIKE LIPS-AKKUR.
DATA LIPS9AKMNG LIKE LIPS-AKMNG.
DATA LIPS9VKGRU LIKE LIPS-VKGRU.
DATA LIPS9SHKZG_UM LIKE LIPS-SHKZG_UM.
DATA LIPS9INSMK LIKE LIPS-INSMK.
DATA LIPS9KZECH LIKE LIPS-KZECH.
DATA LIPS9FLGWM LIKE LIPS-FLGWM.
DATA LIPS9BERKZ LIKE LIPS-BERKZ.
DATA LIPS9HUPOS LIKE LIPS-HUPOS.
DATA LIPS9NOWAB LIKE LIPS-NOWAB.
DATA LIPS9KONTO LIKE LIPS-KONTO.
DATA LIPS9KZEAR LIKE LIPS-KZEAR.
DATA LIPS9HSDAT LIKE LIPS-HSDAT.
DATA LIPS9VFDAT LIKE LIPS-VFDAT.
DATA LIPS9LFGJA LIKE LIPS-LFGJA.
DATA LIPS9LFBNR LIKE LIPS-LFBNR.
DATA LIPS9LFPOS LIKE LIPS-LFPOS.
DATA LIPS9GRUND LIKE LIPS-GRUND.
DATA LIPS9FOBWA LIKE LIPS-FOBWA.
DATA LIPS9DLVTP LIKE LIPS-DLVTP.
DATA LIPS9EXBWR LIKE LIPS-EXBWR.
DATA LIPS9BPMNG LIKE LIPS-BPMNG.
DATA LIPS9EXVKW LIKE LIPS-EXVKW.
DATA LIPS9CMPRE_FLT LIKE LIPS-CMPRE_FLT.
DATA LIPS9KZPOD LIKE LIPS-KZPOD.
DATA LIPS9LFDEZ LIKE LIPS-LFDEZ.
DATA LIPS9UMREV LIKE LIPS-UMREV.
DATA LIPS9PODREL LIKE LIPS-PODREL.
DATA LIPS9KZUML LIKE LIPS-KZUML.
DATA LIPS9FKBER LIKE LIPS-FKBER.
DATA LIPS9GRANT_NBR LIKE LIPS-GRANT_NBR.
DATA LIPS9KZWSO LIKE LIPS-KZWSO.
DATA LIPS9GMCONTROL LIKE LIPS-GMCONTROL.
DATA LIPS9POSTING_CHANGE LIKE LIPS-POSTING_CHANGE.
DATA LIPS9UM_PS_PSP_PNR LIKE LIPS-UM_PS_PSP_PNR.
DATA LIPS9PRE_VL_ETENS LIKE LIPS-PRE_VL_ETENS.
DATA LIPS9SPE_GEN_ELIKZ LIKE LIPS-SPE_GEN_ELIKZ.
DATA LIPS9SPE_SCRAP_IND LIKE LIPS-SPE_SCRAP_IND.
DATA LIPS9SPE_AUTH_NUMBER LIKE LIPS-SPE_AUTH_NUMBER.
DATA LIPS9SPE_INSPOUT_GUID LIKE LIPS-SPE_INSPOUT_GUID.
DATA LIPS9SPE_FOLLOW_UP LIKE LIPS-SPE_FOLLOW_UP.
DATA LIPS9SPE_EXP_DATE_EXT LIKE LIPS-SPE_EXP_DATE_EXT.
DATA LIPS9SPE_EXP_DATE_INT LIKE LIPS-SPE_EXP_DATE_INT.
DATA LIPS9SPE_AUTH_COMPLET LIKE LIPS-SPE_AUTH_COMPLET.
DATA LIPS9ORMNG LIKE LIPS-ORMNG.
DATA LIPS9SPE_ATP_TMSTMP LIKE LIPS-SPE_ATP_TMSTMP.
DATA LIPS9SPE_ORIG_SYS LIKE LIPS-SPE_ORIG_SYS.
DATA LIPS9SPE_LIEFFZ LIKE LIPS-SPE_LIEFFZ.
DATA LIPS9SPE_IMWRK LIKE LIPS-SPE_IMWRK.
DATA LIPS9SPE_LIFEXPOS2 LIKE LIPS-SPE_LIFEXPOS2.
DATA LIPS9SPE_EXCEPT_CODE LIKE LIPS-SPE_EXCEPT_CODE.
DATA LIPS9SPE_KEEP_QTY LIKE LIPS-SPE_KEEP_QTY.
DATA LIPS9SPE_ALTERNATE LIKE LIPS-SPE_ALTERNATE.
DATA LIPS9SPE_MAT_SUBST LIKE LIPS-SPE_MAT_SUBST.
DATA LIPS9SPE_STRUC LIKE LIPS-SPE_STRUC.
DATA LIPS9SPE_APO_QNTYFAC LIKE LIPS-SPE_APO_QNTYFAC.
DATA LIPS9SPE_APO_QNTYDIV LIKE LIPS-SPE_APO_QNTYDIV.
DATA LIPS9SPE_HERKL LIKE LIPS-SPE_HERKL.
DATA LIPS9SPE_BXP_DATE_EXT LIKE LIPS-SPE_BXP_DATE_EXT.
DATA LIPS9SPE_VERSION LIKE LIPS-SPE_VERSION.
DATA LIPS9SPE_COMPL_MVT LIKE LIPS-SPE_COMPL_MVT.
DATA LIPS9J_1BTAXLW4 LIKE LIPS-J_1BTAXLW4.
DATA LIPS9J_1BTAXLW5 LIKE LIPS-J_1BTAXLW5.
DATA LIPS9J_1BTAXLW3 LIKE LIPS-J_1BTAXLW3.
DATA LIPS9BUDGET_PD LIKE LIPS-BUDGET_PD.
DATA LIPS9KBNKZ LIKE LIPS-KBNKZ.
DATA LIPS9FARR_RELTYPE LIKE LIPS-FARR_RELTYPE.
DATA LIPS9SITKZ LIKE LIPS-SITKZ.
DATA LIPS9CONS_ORDER LIKE LIPS-CONS_ORDER.
DATA LIKP9ERDAT LIKE LIKP-ERDAT.
DATA LIKP9VBELN LIKE LIKP-VBELN.



SELECT
  LIPS9~MANDT
  LIPS9~VBELN
  LIPS9~POSNR
  LIPS9~PSTYV
  LIPS9~ERNAM
  LIPS9~ERZET
  LIPS9~ERDAT
  LIPS9~MATNR
  LIPS9~MATWA
  LIPS9~MATKL
  LIPS9~WERKS
  LIPS9~LGORT
  LIPS9~CHARG
  LIPS9~LICHN
  LIPS9~KDMAT
  LIPS9~PRODH
  LIPS9~LFIMG
  LIPS9~MEINS
  LIPS9~VRKME
  LIPS9~UMVKZ
  LIPS9~UMVKN
  LIPS9~NTGEW
  LIPS9~BRGEW
  LIPS9~GEWEI
  LIPS9~VOLUM
  LIPS9~VOLEH
  LIPS9~KZTLF
  LIPS9~UEBTK
  LIPS9~UEBTO
  LIPS9~UNTTO
  LIPS9~CHSPL
  LIPS9~FAKSP
  LIPS9~MBDAT
  LIPS9~LGMNG
  LIPS9~ARKTX
  LIPS9~LGPBE
  LIPS9~VBELV
  LIPS9~POSNV
  LIPS9~VBTYV
  LIPS9~VGSYS
  LIPS9~VGBEL
  LIPS9~VGPOS
  LIPS9~UPFLU
  LIPS9~UEPOS
  LIPS9~FKREL
  LIPS9~LADGR
  LIPS9~TRAGR
  LIPS9~KOMKZ
  LIPS9~LGNUM
  LIPS9~LISPL
  LIPS9~LGTYP
  LIPS9~LGPLA
  LIPS9~BWTEX
  LIPS9~BWART
  LIPS9~BWLVS
  LIPS9~KZDLG
  LIPS9~BDART
  LIPS9~PLART
  LIPS9~MTART
  LIPS9~XCHPF
  LIPS9~XCHAR
  LIPS9~VGREF
  LIPS9~POSAR
  LIPS9~BWTAR
  LIPS9~SUMBD
  LIPS9~MTVFP
  LIPS9~EANNR
  LIPS9~GSBER
  LIPS9~VKBUR
  LIPS9~VKGRP
  LIPS9~VTWEG
  LIPS9~SPART
  LIPS9~GRKOR
  LIPS9~FMENG
  LIPS9~ANTLF
  LIPS9~VBEAF
  LIPS9~VBEAV
  LIPS9~STAFO
  LIPS9~WAVWR
  LIPS9~KZWI1
  LIPS9~KZWI2
  LIPS9~KZWI3
  LIPS9~KZWI4
  LIPS9~KZWI5
  LIPS9~KZWI6
  LIPS9~SOBKZ
  LIPS9~AEDAT
  LIPS9~EAN11
  LIPS9~KVGR1
  LIPS9~KVGR2
  LIPS9~KVGR3
  LIPS9~KVGR4
  LIPS9~KVGR5
  LIPS9~MVGR1
  LIPS9~MVGR2
  LIPS9~MVGR3
  LIPS9~MVGR4
  LIPS9~MVGR5
  LIPS9~VPZUO
  LIPS9~VGTYP
  LIPS9~RFVGTYP
  LIPS9~KOSTL
  LIPS9~KOKRS
  LIPS9~PAOBJNR
  LIPS9~PRCTR
  LIPS9~PS_PSP_PNR
  LIPS9~AUFNR
  LIPS9~POSNR_PP
  LIPS9~KDAUF
  LIPS9~KDPOS
  LIPS9~VPMAT
  LIPS9~VPWRK
  LIPS9~PRBME
  LIPS9~UMREF
  LIPS9~KNTTP
  LIPS9~KZVBR
  LIPS9~FIPOS
  LIPS9~FISTL
  LIPS9~GEBER
  LIPS9~PCKPF
  LIPS9~BEDAR_LF
  LIPS9~CMPNT
  LIPS9~KCMENG
  LIPS9~KCBRGEW
  LIPS9~KCNTGEW
  LIPS9~KCVOLUM
  LIPS9~UECHA
  LIPS9~CUOBJ
  LIPS9~CUOBJ_CH
  LIPS9~ANZSN
  LIPS9~SERAIL
  LIPS9~KCGEWEI
  LIPS9~KCVOLEH
  LIPS9~SERNR
  LIPS9~ABRLI
  LIPS9~ABART
  LIPS9~ABRVW
  LIPS9~QPLOS
  LIPS9~QTLOS
  LIPS9~NACHL
  LIPS9~MAGRV
  LIPS9~OBJKO
  LIPS9~OBJPO
  LIPS9~AESKD
  LIPS9~SHKZG
  LIPS9~PROSA
  LIPS9~UEPVW
  LIPS9~EMPST
  LIPS9~ABTNR
  LIPS9~KOQUI
  LIPS9~STADAT
  LIPS9~AKTNR
  LIPS9~KNUMH_CH
  LIPS9~PREFE
  LIPS9~EXART
  LIPS9~CLINT
  LIPS9~CHMVS
  LIPS9~ABELN
  LIPS9~ABELP
  LIPS9~LFIMG_FLO
  LIPS9~LGMNG_FLO
  LIPS9~KCMENG_FLO
  LIPS9~KZUMW
  LIPS9~KMPMG
  LIPS9~AUREL
  LIPS9~KPEIN
  LIPS9~KMEIN
  LIPS9~NETPR
  LIPS9~NETWR
  LIPS9~KOWRR
  LIPS9~KZBEW
  LIPS9~MFRGR
  LIPS9~CHHPV
  LIPS9~ABFOR
  LIPS9~ABGES
  LIPS9~MBUHR
  LIPS9~WKTNR
  LIPS9~WKTPS
  LIPS9~J_1BCFOP
  LIPS9~J_1BTAXLW1
  LIPS9~J_1BTAXLW2
  LIPS9~J_1BTXSDC
  LIPS9~SITUA
  LIPS9~RSNUM
  LIPS9~RSPOS
  LIPS9~RSART
  LIPS9~KANNR
  LIPS9~KZFME
  LIPS9~PROFL
  LIPS9~KCMENGVME
  LIPS9~KCMENGVMEF
  LIPS9~KZBWS
  LIPS9~PSPNR
  LIPS9~EPRIO
  LIPS9~RULES
  LIPS9~KZBEF
  LIPS9~MPROF
  LIPS9~EMATN
  LIPS9~LGBZO
  LIPS9~HANDLE
  LIPS9~VERURPOS
  LIPS9~LIFEXPOS
  LIPS9~NOATP
  LIPS9~NOPCK
  LIPS9~RBLVS
  LIPS9~BERID
  LIPS9~BESTQ
  LIPS9~UMBSQ
  LIPS9~UMMAT
  LIPS9~UMWRK
  LIPS9~UMLGO
  LIPS9~UMCHA
  LIPS9~UMBAR
  LIPS9~UMSOK
  LIPS9~SONUM
  LIPS9~USONU
  LIPS9~AKKUR
  LIPS9~AKMNG
  LIPS9~VKGRU
  LIPS9~SHKZG_UM
  LIPS9~INSMK
  LIPS9~KZECH
  LIPS9~FLGWM
  LIPS9~BERKZ
  LIPS9~HUPOS
  LIPS9~NOWAB
  LIPS9~KONTO
  LIPS9~KZEAR
  LIPS9~HSDAT
  LIPS9~VFDAT
  LIPS9~LFGJA
  LIPS9~LFBNR
  LIPS9~LFPOS
  LIPS9~GRUND
  LIPS9~FOBWA
  LIPS9~DLVTP
  LIPS9~EXBWR
  LIPS9~BPMNG
  LIPS9~EXVKW
  LIPS9~CMPRE_FLT
  LIPS9~KZPOD
  LIPS9~LFDEZ
  LIPS9~UMREV
  LIPS9~PODREL
  LIPS9~KZUML
  LIPS9~FKBER
  LIPS9~GRANT_NBR
  LIPS9~KZWSO
  LIPS9~GMCONTROL
  LIPS9~POSTING_CHANGE
  LIPS9~UM_PS_PSP_PNR
  LIPS9~PRE_VL_ETENS
  LIPS9~SPE_GEN_ELIKZ
  LIPS9~SPE_SCRAP_IND
  LIPS9~SPE_AUTH_NUMBER
  LIPS9~SPE_INSPOUT_GUID
  LIPS9~SPE_FOLLOW_UP
  LIPS9~SPE_EXP_DATE_EXT
  LIPS9~SPE_EXP_DATE_INT
  LIPS9~SPE_AUTH_COMPLET
  LIPS9~ORMNG
  LIPS9~SPE_ATP_TMSTMP
  LIPS9~SPE_ORIG_SYS
  LIPS9~SPE_LIEFFZ
  LIPS9~SPE_IMWRK
  LIPS9~SPE_LIFEXPOS2
  LIPS9~SPE_EXCEPT_CODE
  LIPS9~SPE_KEEP_QTY
  LIPS9~SPE_ALTERNATE
  LIPS9~SPE_MAT_SUBST
  LIPS9~SPE_STRUC
  LIPS9~SPE_APO_QNTYFAC
  LIPS9~SPE_APO_QNTYDIV
  LIPS9~SPE_HERKL
  LIPS9~SPE_BXP_DATE_EXT
  LIPS9~SPE_VERSION
  LIPS9~SPE_COMPL_MVT
  LIPS9~J_1BTAXLW4
  LIPS9~J_1BTAXLW5
  LIPS9~J_1BTAXLW3
  LIPS9~BUDGET_PD
  LIPS9~KBNKZ
  LIPS9~FARR_RELTYPE
  LIPS9~SITKZ
  LIPS9~CONS_ORDER
  LIKP9~ERDAT
  LIKP9~VBELN
into (LIPS9MANDT,
  LIPS9VBELN,
  LIPS9POSNR,
  LIPS9PSTYV,
  LIPS9ERNAM,
  LIPS9ERZET,
  LIPS9ERDAT,
  LIPS9MATNR,
  LIPS9MATWA,
  LIPS9MATKL,
  LIPS9WERKS,
  LIPS9LGORT,
  LIPS9CHARG,
  LIPS9LICHN,
  LIPS9KDMAT,
  LIPS9PRODH,
  LIPS9LFIMG,
  LIPS9MEINS,
  LIPS9VRKME,
  LIPS9UMVKZ,
  LIPS9UMVKN,
  LIPS9NTGEW,
  LIPS9BRGEW,
  LIPS9GEWEI,
  LIPS9VOLUM,
  LIPS9VOLEH,
  LIPS9KZTLF,
  LIPS9UEBTK,
  LIPS9UEBTO,
  LIPS9UNTTO,
  LIPS9CHSPL,
  LIPS9FAKSP,
  LIPS9MBDAT,
  LIPS9LGMNG,
  LIPS9ARKTX,
  LIPS9LGPBE,
  LIPS9VBELV,
  LIPS9POSNV,
  LIPS9VBTYV,
  LIPS9VGSYS,
  LIPS9VGBEL,
  LIPS9VGPOS,
  LIPS9UPFLU,
  LIPS9UEPOS,
  LIPS9FKREL,
  LIPS9LADGR,
  LIPS9TRAGR,
  LIPS9KOMKZ,
  LIPS9LGNUM,
  LIPS9LISPL,
  LIPS9LGTYP,
  LIPS9LGPLA,
  LIPS9BWTEX,
  LIPS9BWART,
  LIPS9BWLVS,
  LIPS9KZDLG,
  LIPS9BDART,
  LIPS9PLART,
  LIPS9MTART,
  LIPS9XCHPF,
  LIPS9XCHAR,
  LIPS9VGREF,
  LIPS9POSAR,
  LIPS9BWTAR,
  LIPS9SUMBD,
  LIPS9MTVFP,
  LIPS9EANNR,
  LIPS9GSBER,
  LIPS9VKBUR,
  LIPS9VKGRP,
  LIPS9VTWEG,
  LIPS9SPART,
  LIPS9GRKOR,
  LIPS9FMENG,
  LIPS9ANTLF,
  LIPS9VBEAF,
  LIPS9VBEAV,
  LIPS9STAFO,
  LIPS9WAVWR,
  LIPS9KZWI1,
  LIPS9KZWI2,
  LIPS9KZWI3,
  LIPS9KZWI4,
  LIPS9KZWI5,
  LIPS9KZWI6,
  LIPS9SOBKZ,
  LIPS9AEDAT,
  LIPS9EAN11,
  LIPS9KVGR1,
  LIPS9KVGR2,
  LIPS9KVGR3,
  LIPS9KVGR4,
  LIPS9KVGR5,
  LIPS9MVGR1,
  LIPS9MVGR2,
  LIPS9MVGR3,
  LIPS9MVGR4,
  LIPS9MVGR5,
  LIPS9VPZUO,
  LIPS9VGTYP,
  LIPS9RFVGTYP,
  LIPS9KOSTL,
  LIPS9KOKRS,
  LIPS9PAOBJNR,
  LIPS9PRCTR,
  LIPS9PS_PSP_PNR,
  LIPS9AUFNR,
  LIPS9POSNR_PP,
  LIPS9KDAUF,
  LIPS9KDPOS,
  LIPS9VPMAT,
  LIPS9VPWRK,
  LIPS9PRBME,
  LIPS9UMREF,
  LIPS9KNTTP,
  LIPS9KZVBR,
  LIPS9FIPOS,
  LIPS9FISTL,
  LIPS9GEBER,
  LIPS9PCKPF,
  LIPS9BEDAR_LF,
  LIPS9CMPNT,
  LIPS9KCMENG,
  LIPS9KCBRGEW,
  LIPS9KCNTGEW,
  LIPS9KCVOLUM,
  LIPS9UECHA,
  LIPS9CUOBJ,
  LIPS9CUOBJ_CH,
  LIPS9ANZSN,
  LIPS9SERAIL,
  LIPS9KCGEWEI,
  LIPS9KCVOLEH,
  LIPS9SERNR,
  LIPS9ABRLI,
  LIPS9ABART,
  LIPS9ABRVW,
  LIPS9QPLOS,
  LIPS9QTLOS,
  LIPS9NACHL,
  LIPS9MAGRV,
  LIPS9OBJKO,
  LIPS9OBJPO,
  LIPS9AESKD,
  LIPS9SHKZG,
  LIPS9PROSA,
  LIPS9UEPVW,
  LIPS9EMPST,
  LIPS9ABTNR,
  LIPS9KOQUI,
  LIPS9STADAT,
  LIPS9AKTNR,
  LIPS9KNUMH_CH,
  LIPS9PREFE,
  LIPS9EXART,
  LIPS9CLINT,
  LIPS9CHMVS,
  LIPS9ABELN,
  LIPS9ABELP,
  LIPS9LFIMG_FLO,
  LIPS9LGMNG_FLO,
  LIPS9KCMENG_FLO,
  LIPS9KZUMW,
  LIPS9KMPMG,
  LIPS9AUREL,
  LIPS9KPEIN,
  LIPS9KMEIN,
  LIPS9NETPR,
  LIPS9NETWR,
  LIPS9KOWRR,
  LIPS9KZBEW,
  LIPS9MFRGR,
  LIPS9CHHPV,
  LIPS9ABFOR,
  LIPS9ABGES,
  LIPS9MBUHR,
  LIPS9WKTNR,
  LIPS9WKTPS,
  LIPS9J_1BCFOP,
  LIPS9J_1BTAXLW1,
  LIPS9J_1BTAXLW2,
  LIPS9J_1BTXSDC,
  LIPS9SITUA,
  LIPS9RSNUM,
  LIPS9RSPOS,
  LIPS9RSART,
  LIPS9KANNR,
  LIPS9KZFME,
  LIPS9PROFL,
  LIPS9KCMENGVME,
  LIPS9KCMENGVMEF,
  LIPS9KZBWS,
  LIPS9PSPNR,
  LIPS9EPRIO,
  LIPS9RULES,
  LIPS9KZBEF,
  LIPS9MPROF,
  LIPS9EMATN,
  LIPS9LGBZO,
  LIPS9HANDLE,
  LIPS9VERURPOS,
  LIPS9LIFEXPOS,
  LIPS9NOATP,
  LIPS9NOPCK,
  LIPS9RBLVS,
  LIPS9BERID,
  LIPS9BESTQ,
  LIPS9UMBSQ,
  LIPS9UMMAT,
  LIPS9UMWRK,
  LIPS9UMLGO,
  LIPS9UMCHA,
  LIPS9UMBAR,
  LIPS9UMSOK,
  LIPS9SONUM,
  LIPS9USONU,
  LIPS9AKKUR,
  LIPS9AKMNG,
  LIPS9VKGRU,
  LIPS9SHKZG_UM,
  LIPS9INSMK,
  LIPS9KZECH,
  LIPS9FLGWM,
  LIPS9BERKZ,
  LIPS9HUPOS,
  LIPS9NOWAB,
  LIPS9KONTO,
  LIPS9KZEAR,
  LIPS9HSDAT,
  LIPS9VFDAT,
  LIPS9LFGJA,
  LIPS9LFBNR,
  LIPS9LFPOS,
  LIPS9GRUND,
  LIPS9FOBWA,
  LIPS9DLVTP,
  LIPS9EXBWR,
  LIPS9BPMNG,
  LIPS9EXVKW,
  LIPS9CMPRE_FLT,
  LIPS9KZPOD,
  LIPS9LFDEZ,
  LIPS9UMREV,
  LIPS9PODREL,
  LIPS9KZUML,
  LIPS9FKBER,
  LIPS9GRANT_NBR,
  LIPS9KZWSO,
  LIPS9GMCONTROL,
  LIPS9POSTING_CHANGE,
  LIPS9UM_PS_PSP_PNR,
  LIPS9PRE_VL_ETENS,
  LIPS9SPE_GEN_ELIKZ,
  LIPS9SPE_SCRAP_IND,
  LIPS9SPE_AUTH_NUMBER,
  LIPS9SPE_INSPOUT_GUID,
  LIPS9SPE_FOLLOW_UP,
  LIPS9SPE_EXP_DATE_EXT,
  LIPS9SPE_EXP_DATE_INT,
  LIPS9SPE_AUTH_COMPLET,
  LIPS9ORMNG,
  LIPS9SPE_ATP_TMSTMP,
  LIPS9SPE_ORIG_SYS,
  LIPS9SPE_LIEFFZ,
  LIPS9SPE_IMWRK,
  LIPS9SPE_LIFEXPOS2,
  LIPS9SPE_EXCEPT_CODE,
  LIPS9SPE_KEEP_QTY,
  LIPS9SPE_ALTERNATE,
  LIPS9SPE_MAT_SUBST,
  LIPS9SPE_STRUC,
  LIPS9SPE_APO_QNTYFAC,
  LIPS9SPE_APO_QNTYDIV,
  LIPS9SPE_HERKL,
  LIPS9SPE_BXP_DATE_EXT,
  LIPS9SPE_VERSION,
  LIPS9SPE_COMPL_MVT,
  LIPS9J_1BTAXLW4,
  LIPS9J_1BTAXLW5,
  LIPS9J_1BTAXLW3,
  LIPS9BUDGET_PD,
  LIPS9KBNKZ,
  LIPS9FARR_RELTYPE,
  LIPS9SITKZ,
  LIPS9CONS_ORDER,
  LIKP9ERDAT,
  LIKP9VBELN)
FROM LIPS AS LIPS9
 INNER JOIN LIKP AS LIKP9
 ON ( LIKP9~VBELN = LIPS9~VBELN )
WHERE ( ( LIKP9~ERDAT < $PARAM2 )
 AND ( LIKP9~ERDAT >= $PARAM1 ) ).
ALTMP667 = LIPS9MANDT.
ALTMP668 = LIPS9VBELN.
ALTMP669 = LIPS9POSNR.
ALTMP670 = LIPS9PSTYV.
ALTMP671 = LIPS9ERNAM.
ALTMP672 = LIPS9ERZET.
ALTMP673 = LIPS9ERDAT.
ALTMP674 = LIPS9MATNR.
ALTMP675 = LIPS9MATWA.
ALTMP676 = LIPS9MATKL.
ALTMP677 = LIPS9WERKS.
ALTMP678 = LIPS9LGORT.
ALTMP679 = LIPS9CHARG.
ALTMP680 = LIPS9LICHN.
ALTMP681 = LIPS9KDMAT.
ALTMP682 = LIPS9PRODH.
ALTMP683 = LIPS9LFIMG.
ALTMP684 = LIPS9MEINS.
ALTMP685 = LIPS9VRKME.
ALTMP686 = LIPS9UMVKZ.
ALTMP687 = LIPS9UMVKN.
ALTMP688 = LIPS9NTGEW.
ALTMP689 = LIPS9BRGEW.
ALTMP690 = LIPS9GEWEI.
ALTMP691 = LIPS9VOLUM.
ALTMP692 = LIPS9VOLEH.
ALTMP693 = LIPS9KZTLF.
ALTMP694 = LIPS9UEBTK.
ALTMP695 = LIPS9UEBTO.
ALTMP696 = LIPS9UNTTO.
ALTMP697 = LIPS9CHSPL.
ALTMP698 = LIPS9FAKSP.
ALTMP699 = LIPS9MBDAT.
ALTMP700 = LIPS9LGMNG.
ALTMP701 = LIPS9ARKTX.
ALTMP702 = LIPS9LGPBE.
ALTMP703 = LIPS9VBELV.
ALTMP704 = LIPS9POSNV.
ALTMP705 = LIPS9VBTYV.
ALTMP706 = LIPS9VGSYS.
ALTMP707 = LIPS9VGBEL.
ALTMP708 = LIPS9VGPOS.
ALTMP709 = LIPS9UPFLU.
ALTMP710 = LIPS9UEPOS.
ALTMP711 = LIPS9FKREL.
ALTMP712 = LIPS9LADGR.
ALTMP713 = LIPS9TRAGR.
ALTMP714 = LIPS9KOMKZ.
ALTMP715 = LIPS9LGNUM.
ALTMP716 = LIPS9LISPL.
ALTMP717 = LIPS9LGTYP.
ALTMP718 = LIPS9LGPLA.
ALTMP719 = LIPS9BWTEX.
ALTMP720 = LIPS9BWART.
ALTMP721 = LIPS9BWLVS.
ALTMP722 = LIPS9KZDLG.
ALTMP723 = LIPS9BDART.
ALTMP724 = LIPS9PLART.
ALTMP725 = LIPS9MTART.
ALTMP726 = LIPS9XCHPF.
ALTMP727 = LIPS9XCHAR.
ALTMP728 = LIPS9VGREF.
ALTMP729 = LIPS9POSAR.
ALTMP730 = LIPS9BWTAR.
ALTMP731 = LIPS9SUMBD.
ALTMP732 = LIPS9MTVFP.
ALTMP733 = LIPS9EANNR.
ALTMP734 = LIPS9GSBER.
ALTMP735 = LIPS9VKBUR.
ALTMP736 = LIPS9VKGRP.
ALTMP737 = LIPS9VTWEG.
ALTMP738 = LIPS9SPART.
ALTMP739 = LIPS9GRKOR.
ALTMP740 = LIPS9FMENG.
ALTMP741 = LIPS9ANTLF.
ALTMP742 = LIPS9VBEAF.
ALTMP743 = LIPS9VBEAV.
ALTMP744 = LIPS9STAFO.
ALTMP745 = LIPS9WAVWR.
ALTMP746 = LIPS9KZWI1.
ALTMP747 = LIPS9KZWI2.
ALTMP748 = LIPS9KZWI3.
ALTMP749 = LIPS9KZWI4.
ALTMP750 = LIPS9KZWI5.
ALTMP751 = LIPS9KZWI6.
ALTMP752 = LIPS9SOBKZ.
ALTMP753 = LIPS9AEDAT.
ALTMP754 = LIPS9EAN11.
ALTMP755 = LIPS9KVGR1.
ALTMP756 = LIPS9KVGR2.
ALTMP757 = LIPS9KVGR3.
ALTMP758 = LIPS9KVGR4.
ALTMP759 = LIPS9KVGR5.
ALTMP760 = LIPS9MVGR1.
ALTMP761 = LIPS9MVGR2.
ALTMP762 = LIPS9MVGR3.
ALTMP763 = LIPS9MVGR4.
ALTMP764 = LIPS9MVGR5.
ALTMP765 = LIPS9VPZUO.
ALTMP766 = LIPS9VGTYP.
ALTMP767 = LIPS9RFVGTYP.
ALTMP768 = LIPS9KOSTL.
ALTMP769 = LIPS9KOKRS.
ALTMP770 = LIPS9PAOBJNR.
ALTMP771 = LIPS9PRCTR.
ALTMP772 = LIPS9PS_PSP_PNR.
ALTMP773 = LIPS9AUFNR.
ALTMP774 = LIPS9POSNR_PP.
ALTMP775 = LIPS9KDAUF.
ALTMP776 = LIPS9KDPOS.
ALTMP777 = LIPS9VPMAT.
ALTMP778 = LIPS9VPWRK.
ALTMP779 = LIPS9PRBME.
ALTMP780 = LIPS9UMREF.
ALTMP781 = LIPS9KNTTP.
ALTMP782 = LIPS9KZVBR.
ALTMP783 = LIPS9FIPOS.
ALTMP784 = LIPS9FISTL.
ALTMP785 = LIPS9GEBER.
ALTMP786 = LIPS9PCKPF.
ALTMP787 = LIPS9BEDAR_LF.
ALTMP788 = LIPS9CMPNT.
ALTMP789 = LIPS9KCMENG.
ALTMP790 = LIPS9KCBRGEW.
ALTMP791 = LIPS9KCNTGEW.
ALTMP792 = LIPS9KCVOLUM.
ALTMP793 = LIPS9UECHA.
ALTMP794 = LIPS9CUOBJ.
ALTMP795 = LIPS9CUOBJ_CH.
ALTMP796 = LIPS9ANZSN.
ALTMP797 = LIPS9SERAIL.
ALTMP798 = LIPS9KCGEWEI.
ALTMP799 = LIPS9KCVOLEH.
ALTMP800 = LIPS9SERNR.
ALTMP801 = LIPS9ABRLI.
ALTMP802 = LIPS9ABART.
ALTMP803 = LIPS9ABRVW.
ALTMP804 = LIPS9QPLOS.
ALTMP805 = LIPS9QTLOS.
ALTMP806 = LIPS9NACHL.
ALTMP807 = LIPS9MAGRV.
ALTMP808 = LIPS9OBJKO.
ALTMP809 = LIPS9OBJPO.
ALTMP810 = LIPS9AESKD.
ALTMP811 = LIPS9SHKZG.
ALTMP812 = LIPS9PROSA.
ALTMP813 = LIPS9UEPVW.
ALTMP814 = LIPS9EMPST.
ALTMP815 = LIPS9ABTNR.
ALTMP816 = LIPS9KOQUI.
ALTMP817 = LIPS9STADAT.
ALTMP818 = LIPS9AKTNR.
ALTMP819 = LIPS9KNUMH_CH.
ALTMP820 = LIPS9PREFE.
ALTMP821 = LIPS9EXART.
ALTMP822 = LIPS9CLINT.
ALTMP823 = LIPS9CHMVS.
ALTMP824 = LIPS9ABELN.
ALTMP825 = LIPS9ABELP.
ALTMP826 = LIPS9LFIMG_FLO.
ALTMP827 = LIPS9LGMNG_FLO.
ALTMP828 = LIPS9KCMENG_FLO.
ALTMP829 = LIPS9KZUMW.
ALTMP830 = LIPS9KMPMG.
ALTMP831 = LIPS9AUREL.
ALTMP832 = LIPS9KPEIN.
ALTMP833 = LIPS9KMEIN.
ALTMP834 = LIPS9NETPR.
ALTMP835 = LIPS9NETWR.
ALTMP836 = LIPS9KOWRR.
ALTMP837 = LIPS9KZBEW.
ALTMP838 = LIPS9MFRGR.
ALTMP839 = LIPS9CHHPV.
ALTMP840 = LIPS9ABFOR.
ALTMP841 = LIPS9ABGES.
ALTMP842 = LIPS9MBUHR.
ALTMP843 = LIPS9WKTNR.
ALTMP844 = LIPS9WKTPS.
ALTMP845 = LIPS9J_1BCFOP.
ALTMP846 = LIPS9J_1BTAXLW1.
ALTMP847 = LIPS9J_1BTAXLW2.
ALTMP848 = LIPS9J_1BTXSDC.
ALTMP849 = LIPS9SITUA.
ALTMP850 = LIPS9RSNUM.
ALTMP851 = LIPS9RSPOS.
ALTMP852 = LIPS9RSART.
ALTMP853 = LIPS9KANNR.
ALTMP854 = LIPS9KZFME.
ALTMP855 = LIPS9PROFL.
ALTMP856 = LIPS9KCMENGVME.
ALTMP857 = LIPS9KCMENGVMEF.
ALTMP858 = LIPS9KZBWS.
ALTMP859 = LIPS9PSPNR.
ALTMP860 = LIPS9EPRIO.
ALTMP861 = LIPS9RULES.
ALTMP862 = LIPS9KZBEF.
ALTMP863 = LIPS9MPROF.
ALTMP864 = LIPS9EMATN.
ALTMP865 = LIPS9LGBZO.
ALTMP866 = LIPS9HANDLE.
ALTMP867 = LIPS9VERURPOS.
ALTMP868 = LIPS9LIFEXPOS.
ALTMP869 = LIPS9NOATP.
ALTMP870 = LIPS9NOPCK.
ALTMP871 = LIPS9RBLVS.
ALTMP872 = LIPS9BERID.
ALTMP873 = LIPS9BESTQ.
ALTMP874 = LIPS9UMBSQ.
ALTMP875 = LIPS9UMMAT.
ALTMP876 = LIPS9UMWRK.
ALTMP877 = LIPS9UMLGO.
ALTMP878 = LIPS9UMCHA.
ALTMP879 = LIPS9UMBAR.
ALTMP880 = LIPS9UMSOK.
ALTMP881 = LIPS9SONUM.
ALTMP882 = LIPS9USONU.
ALTMP883 = LIPS9AKKUR.
ALTMP884 = LIPS9AKMNG.
ALTMP885 = LIPS9VKGRU.
ALTMP886 = LIPS9SHKZG_UM.
ALTMP887 = LIPS9INSMK.
ALTMP888 = LIPS9KZECH.
ALTMP889 = LIPS9FLGWM.
ALTMP890 = LIPS9BERKZ.
ALTMP891 = LIPS9HUPOS.
ALTMP892 = LIPS9NOWAB.
ALTMP893 = LIPS9KONTO.
ALTMP894 = LIPS9KZEAR.
ALTMP895 = LIPS9HSDAT.
ALTMP896 = LIPS9VFDAT.
ALTMP897 = LIPS9LFGJA.
ALTMP898 = LIPS9LFBNR.
ALTMP899 = LIPS9LFPOS.
ALTMP900 = LIPS9GRUND.
ALTMP901 = LIPS9FOBWA.
ALTMP902 = LIPS9DLVTP.
ALTMP903 = LIPS9EXBWR.
ALTMP904 = LIPS9BPMNG.
ALTMP905 = LIPS9EXVKW.
ALTMP906 = LIPS9CMPRE_FLT.
ALTMP907 = LIPS9KZPOD.
ALTMP908 = LIPS9LFDEZ.
ALTMP909 = LIPS9UMREV.
ALTMP910 = LIPS9PODREL.
ALTMP911 = LIPS9KZUML.
ALTMP912 = LIPS9FKBER.
ALTMP913 = LIPS9GRANT_NBR.
ALTMP914 = LIPS9KZWSO.
ALTMP915 = LIPS9GMCONTROL.
ALTMP916 = LIPS9POSTING_CHANGE.
ALTMP917 = LIPS9UM_PS_PSP_PNR.
ALTMP918 = LIPS9PRE_VL_ETENS.
ALTMP919 = LIPS9SPE_GEN_ELIKZ.
ALTMP920 = LIPS9SPE_SCRAP_IND.
ALTMP921 = LIPS9SPE_AUTH_NUMBER.
ALTMP922 = LIPS9SPE_INSPOUT_GUID.
ALTMP923 = LIPS9SPE_FOLLOW_UP.
ALTMP924 = LIPS9SPE_EXP_DATE_EXT.
ALTMP925 = LIPS9SPE_EXP_DATE_INT.
ALTMP926 = LIPS9SPE_AUTH_COMPLET.
ALTMP927 = LIPS9ORMNG.
ALTMP928 = LIPS9SPE_ATP_TMSTMP.
ALTMP929 = LIPS9SPE_ORIG_SYS.
ALTMP930 = LIPS9SPE_LIEFFZ.
ALTMP931 = LIPS9SPE_IMWRK.
ALTMP932 = LIPS9SPE_LIFEXPOS2.
ALTMP933 = LIPS9SPE_EXCEPT_CODE.
ALTMP934 = LIPS9SPE_KEEP_QTY.
ALTMP935 = LIPS9SPE_ALTERNATE.
ALTMP936 = LIPS9SPE_MAT_SUBST.
ALTMP937 = LIPS9SPE_STRUC.
ALTMP938 = LIPS9SPE_APO_QNTYFAC.
ALTMP939 = LIPS9SPE_APO_QNTYDIV.
ALTMP940 = LIPS9SPE_HERKL.
ALTMP941 = LIPS9SPE_BXP_DATE_EXT.
ALTMP942 = LIPS9SPE_VERSION.
ALTMP943 = LIPS9SPE_COMPL_MVT.
ALTMP944 = LIPS9J_1BTAXLW4.
ALTMP945 = LIPS9J_1BTAXLW5.
ALTMP946 = LIPS9J_1BTAXLW3.
ALTMP947 = LIPS9BUDGET_PD.
ALTMP948 = LIPS9KBNKZ.
ALTMP949 = LIPS9FARR_RELTYPE.
ALTMP950 = LIPS9SITKZ.
ALTMP951 = LIPS9CONS_ORDER.
 move ALTMP667 to ITAB3-MANDT.
 move ALTMP668 to ITAB3-VBELN.
 move ALTMP669 to ITAB3-POSNR.
 move ALTMP670 to ITAB3-PSTYV.
 move ALTMP671 to ITAB3-ERNAM.
 move ALTMP672 to ITAB3-ERZET.
 move ALTMP673 to ITAB3-ERDAT.
 move ALTMP674 to ITAB3-MATNR.
 move ALTMP675 to ITAB3-MATWA.
 move ALTMP676 to ITAB3-MATKL.
 move ALTMP677 to ITAB3-WERKS.
 move ALTMP678 to ITAB3-LGORT.
 move ALTMP679 to ITAB3-CHARG.
 move ALTMP680 to ITAB3-LICHN.
 move ALTMP681 to ITAB3-KDMAT.
 move ALTMP682 to ITAB3-PRODH.
 move ALTMP683 to ITAB3-LFIMG.
 move ALTMP684 to ITAB3-MEINS.
 move ALTMP685 to ITAB3-VRKME.
 move ALTMP686 to ITAB3-UMVKZ.
 move ALTMP687 to ITAB3-UMVKN.
 move ALTMP688 to ITAB3-NTGEW.
 move ALTMP689 to ITAB3-BRGEW.
 move ALTMP690 to ITAB3-GEWEI.
 move ALTMP691 to ITAB3-VOLUM.
 move ALTMP692 to ITAB3-VOLEH.
 move ALTMP693 to ITAB3-KZTLF.
 move ALTMP694 to ITAB3-UEBTK.
 move ALTMP695 to ITAB3-UEBTO.
 move ALTMP696 to ITAB3-UNTTO.
 move ALTMP697 to ITAB3-CHSPL.
 move ALTMP698 to ITAB3-FAKSP.
 move ALTMP699 to ITAB3-MBDAT.
 move ALTMP700 to ITAB3-LGMNG.
 move ALTMP701 to ITAB3-ARKTX.
 move ALTMP702 to ITAB3-LGPBE.
 move ALTMP703 to ITAB3-VBELV.
 move ALTMP704 to ITAB3-POSNV.
 move ALTMP705 to ITAB3-VBTYV.
 move ALTMP706 to ITAB3-VGSYS.
 move ALTMP707 to ITAB3-VGBEL.
 move ALTMP708 to ITAB3-VGPOS.
 move ALTMP709 to ITAB3-UPFLU.
 move ALTMP710 to ITAB3-UEPOS.
 move ALTMP711 to ITAB3-FKREL.
 move ALTMP712 to ITAB3-LADGR.
 move ALTMP713 to ITAB3-TRAGR.
 move ALTMP714 to ITAB3-KOMKZ.
 move ALTMP715 to ITAB3-LGNUM.
 move ALTMP716 to ITAB3-LISPL.
 move ALTMP717 to ITAB3-LGTYP.
 move ALTMP718 to ITAB3-LGPLA.
 move ALTMP719 to ITAB3-BWTEX.
 move ALTMP720 to ITAB3-BWART.
 move ALTMP721 to ITAB3-BWLVS.
 move ALTMP722 to ITAB3-KZDLG.
 move ALTMP723 to ITAB3-BDART.
 move ALTMP724 to ITAB3-PLART.
 move ALTMP725 to ITAB3-MTART.
 move ALTMP726 to ITAB3-XCHPF.
 move ALTMP727 to ITAB3-XCHAR.
 move ALTMP728 to ITAB3-VGREF.
 move ALTMP729 to ITAB3-POSAR.
 move ALTMP730 to ITAB3-BWTAR.
 move ALTMP731 to ITAB3-SUMBD.
 move ALTMP732 to ITAB3-MTVFP.
 move ALTMP733 to ITAB3-EANNR.
 move ALTMP734 to ITAB3-GSBER.
 move ALTMP735 to ITAB3-VKBUR.
 move ALTMP736 to ITAB3-VKGRP.
 move ALTMP737 to ITAB3-VTWEG.
 move ALTMP738 to ITAB3-SPART.
 move ALTMP739 to ITAB3-GRKOR.
 move ALTMP740 to ITAB3-FMENG.
 move ALTMP741 to ITAB3-ANTLF.
 move ALTMP742 to ITAB3-VBEAF.
 move ALTMP743 to ITAB3-VBEAV.
 move ALTMP744 to ITAB3-STAFO.
 move ALTMP745 to ITAB3-WAVWR.
 move ALTMP746 to ITAB3-KZWI1.
 move ALTMP747 to ITAB3-KZWI2.
 move ALTMP748 to ITAB3-KZWI3.
 move ALTMP749 to ITAB3-KZWI4.
 move ALTMP750 to ITAB3-KZWI5.
 move ALTMP751 to ITAB3-KZWI6.
 move ALTMP752 to ITAB3-SOBKZ.
 move ALTMP753 to ITAB3-AEDAT.
 move ALTMP754 to ITAB3-EAN11.
 move ALTMP755 to ITAB3-KVGR1.
 move ALTMP756 to ITAB3-KVGR2.
 move ALTMP757 to ITAB3-KVGR3.
 move ALTMP758 to ITAB3-KVGR4.
 move ALTMP759 to ITAB3-KVGR5.
 move ALTMP760 to ITAB3-MVGR1.
 move ALTMP761 to ITAB3-MVGR2.
 move ALTMP762 to ITAB3-MVGR3.
 move ALTMP763 to ITAB3-MVGR4.
 move ALTMP764 to ITAB3-MVGR5.
 move ALTMP765 to ITAB3-VPZUO.
 move ALTMP766 to ITAB3-VGTYP.
 move ALTMP767 to ITAB3-RFVGTYP.
 move ALTMP768 to ITAB3-KOSTL.
 move ALTMP769 to ITAB3-KOKRS.
 move ALTMP770 to ITAB3-PAOBJNR.
 move ALTMP771 to ITAB3-PRCTR.
 move ALTMP772 to ITAB3-PS_PSP_PNR.
 move ALTMP773 to ITAB3-AUFNR.
 move ALTMP774 to ITAB3-POSNR_PP.
 move ALTMP775 to ITAB3-KDAUF.
 move ALTMP776 to ITAB3-KDPOS.
 move ALTMP777 to ITAB3-VPMAT.
 move ALTMP778 to ITAB3-VPWRK.
 move ALTMP779 to ITAB3-PRBME.
 move ALTMP780 to ITAB3-UMREF.
 move ALTMP781 to ITAB3-KNTTP.
 move ALTMP782 to ITAB3-KZVBR.
 move ALTMP783 to ITAB3-FIPOS.
 move ALTMP784 to ITAB3-FISTL.
 move ALTMP785 to ITAB3-GEBER.
 move ALTMP786 to ITAB3-PCKPF.
 move ALTMP787 to ITAB3-BEDAR_LF.
 move ALTMP788 to ITAB3-CMPNT.
 move ALTMP789 to ITAB3-KCMENG.
 move ALTMP790 to ITAB3-KCBRGEW.
 move ALTMP791 to ITAB3-KCNTGEW.
 move ALTMP792 to ITAB3-KCVOLUM.
 move ALTMP793 to ITAB3-UECHA.
 move ALTMP794 to ITAB3-CUOBJ.
 move ALTMP795 to ITAB3-CUOBJ_CH.
 move ALTMP796 to ITAB3-ANZSN.
 move ALTMP797 to ITAB3-SERAIL.
 move ALTMP798 to ITAB3-KCGEWEI.
 move ALTMP799 to ITAB3-KCVOLEH.
 move ALTMP800 to ITAB3-SERNR.
 move ALTMP801 to ITAB3-ABRLI.
 move ALTMP802 to ITAB3-ABART.
 move ALTMP803 to ITAB3-ABRVW.
 move ALTMP804 to ITAB3-QPLOS.
 move ALTMP805 to ITAB3-QTLOS.
 move ALTMP806 to ITAB3-NACHL.
 move ALTMP807 to ITAB3-MAGRV.
 move ALTMP808 to ITAB3-OBJKO.
 move ALTMP809 to ITAB3-OBJPO.
 move ALTMP810 to ITAB3-AESKD.
 move ALTMP811 to ITAB3-SHKZG.
 move ALTMP812 to ITAB3-PROSA.
 move ALTMP813 to ITAB3-UEPVW.
 move ALTMP814 to ITAB3-EMPST.
 move ALTMP815 to ITAB3-ABTNR.
 move ALTMP816 to ITAB3-KOQUI.
 move ALTMP817 to ITAB3-STADAT.
 move ALTMP818 to ITAB3-AKTNR.
 move ALTMP819 to ITAB3-KNUMH_CH.
 move ALTMP820 to ITAB3-PREFE.
 move ALTMP821 to ITAB3-EXART.
 move ALTMP822 to ITAB3-CLINT.
 move ALTMP823 to ITAB3-CHMVS.
 move ALTMP824 to ITAB3-ABELN.
 move ALTMP825 to ITAB3-ABELP.
 move ALTMP826 to ITAB3-LFIMG_FLO.
 move ALTMP827 to ITAB3-LGMNG_FLO.
 move ALTMP828 to ITAB3-KCMENG_FLO.
 move ALTMP829 to ITAB3-KZUMW.
 move ALTMP830 to ITAB3-KMPMG.
 move ALTMP831 to ITAB3-AUREL.
 move ALTMP832 to ITAB3-KPEIN.
 move ALTMP833 to ITAB3-KMEIN.
 move ALTMP834 to ITAB3-NETPR.
 move ALTMP835 to ITAB3-NETWR.
 move ALTMP836 to ITAB3-KOWRR.
 move ALTMP837 to ITAB3-KZBEW.
 move ALTMP838 to ITAB3-MFRGR.
 move ALTMP839 to ITAB3-CHHPV.
 move ALTMP840 to ITAB3-ABFOR.
 move ALTMP841 to ITAB3-ABGES.
 move ALTMP842 to ITAB3-MBUHR.
 move ALTMP843 to ITAB3-WKTNR.
 move ALTMP844 to ITAB3-WKTPS.
 move ALTMP845 to ITAB3-J_1BCFOP.
 move ALTMP846 to ITAB3-J_1BTAXLW1.
 move ALTMP847 to ITAB3-J_1BTAXLW2.
 move ALTMP848 to ITAB3-J_1BTXSDC.
 move ALTMP849 to ITAB3-SITUA.
 move ALTMP850 to ITAB3-RSNUM.
 move ALTMP851 to ITAB3-RSPOS.
 move ALTMP852 to ITAB3-RSART.
 move ALTMP853 to ITAB3-KANNR.
 move ALTMP854 to ITAB3-KZFME.
 move ALTMP855 to ITAB3-PROFL.
 move ALTMP856 to ITAB3-KCMENGVME.
 move ALTMP857 to ITAB3-KCMENGVMEF.
 move ALTMP858 to ITAB3-KZBWS.
 move ALTMP859 to ITAB3-PSPNR.
 move ALTMP860 to ITAB3-EPRIO.
 move ALTMP861 to ITAB3-RULES.
 move ALTMP862 to ITAB3-KZBEF.
 move ALTMP863 to ITAB3-MPROF.
 move ALTMP864 to ITAB3-EMATN.
 move ALTMP865 to ITAB3-LGBZO.
 move ALTMP866 to ITAB3-HANDLE.
 move ALTMP867 to ITAB3-VERURPOS.
 move ALTMP868 to ITAB3-LIFEXPOS.
 move ALTMP869 to ITAB3-NOATP.
 move ALTMP870 to ITAB3-NOPCK.
 move ALTMP871 to ITAB3-RBLVS.
 move ALTMP872 to ITAB3-BERID.
 move ALTMP873 to ITAB3-BESTQ.
 move ALTMP874 to ITAB3-UMBSQ.
 move ALTMP875 to ITAB3-UMMAT.
 move ALTMP876 to ITAB3-UMWRK.
 move ALTMP877 to ITAB3-UMLGO.
 move ALTMP878 to ITAB3-UMCHA.
 move ALTMP879 to ITAB3-UMBAR.
 move ALTMP880 to ITAB3-UMSOK.
 move ALTMP881 to ITAB3-SONUM.
 move ALTMP882 to ITAB3-USONU.
 move ALTMP883 to ITAB3-AKKUR.
 move ALTMP884 to ITAB3-AKMNG.
 move ALTMP885 to ITAB3-VKGRU.
 move ALTMP886 to ITAB3-SHKZG_UM.
 move ALTMP887 to ITAB3-INSMK.
 move ALTMP888 to ITAB3-KZECH.
 move ALTMP889 to ITAB3-FLGWM.
 move ALTMP890 to ITAB3-BERKZ.
 move ALTMP891 to ITAB3-HUPOS.
 move ALTMP892 to ITAB3-NOWAB.
 move ALTMP893 to ITAB3-KONTO.
 move ALTMP894 to ITAB3-KZEAR.
 move ALTMP895 to ITAB3-HSDAT.
 move ALTMP896 to ITAB3-VFDAT.
 move ALTMP897 to ITAB3-LFGJA.
 move ALTMP898 to ITAB3-LFBNR.
 move ALTMP899 to ITAB3-LFPOS.
 move ALTMP900 to ITAB3-GRUND.
 move ALTMP901 to ITAB3-FOBWA.
 move ALTMP902 to ITAB3-DLVTP.
 move ALTMP903 to ITAB3-EXBWR.
 move ALTMP904 to ITAB3-BPMNG.
 move ALTMP905 to ITAB3-EXVKW.
 move ALTMP906 to ITAB3-CMPRE_FLT.
 move ALTMP907 to ITAB3-KZPOD.
 move ALTMP908 to ITAB3-LFDEZ.
 move ALTMP909 to ITAB3-UMREV.
 move ALTMP910 to ITAB3-PODREL.
 move ALTMP911 to ITAB3-KZUML.
 move ALTMP912 to ITAB3-FKBER.
 move ALTMP913 to ITAB3-GRANT_NBR.
 move ALTMP914 to ITAB3-KZWSO.
 move ALTMP915 to ITAB3-GMCONTROL.
 move ALTMP916 to ITAB3-POSTING_CHANGE.
 move ALTMP917 to ITAB3-UM_PS_PSP_PNR.
 move ALTMP918 to ITAB3-PRE_VL_ETENS.
 move ALTMP919 to ITAB3-SPE_GEN_ELIKZ.
 move ALTMP920 to ITAB3-SPE_SCRAP_IND.
 move ALTMP921 to ITAB3-SPE_AUTH_NUMBER.
 move ALTMP922 to ITAB3-SPE_INSPOUT_GUID.
 move ALTMP923 to ITAB3-SPE_FOLLOW_UP.
 move ALTMP924 to ITAB3-SPE_EXP_DATE_EXT.
 move ALTMP925 to ITAB3-SPE_EXP_DATE_INT.
 move ALTMP926 to ITAB3-SPE_AUTH_COMPLET.
 move ALTMP927 to ITAB3-ORMNG.
 move ALTMP928 to ITAB3-SPE_ATP_TMSTMP.
 move ALTMP929 to ITAB3-SPE_ORIG_SYS.
 move ALTMP930 to ITAB3-SPE_LIEFFZ.
 move ALTMP931 to ITAB3-SPE_IMWRK.
 move ALTMP932 to ITAB3-SPE_LIFEXPOS2.
 move ALTMP933 to ITAB3-SPE_EXCEPT_CODE.
 move ALTMP934 to ITAB3-SPE_KEEP_QTY.
 move ALTMP935 to ITAB3-SPE_ALTERNATE.
 move ALTMP936 to ITAB3-SPE_MAT_SUBST.
 move ALTMP937 to ITAB3-SPE_STRUC.
 move ALTMP938 to ITAB3-SPE_APO_QNTYFAC.
 move ALTMP939 to ITAB3-SPE_APO_QNTYDIV.
 move ALTMP940 to ITAB3-SPE_HERKL.
 move ALTMP941 to ITAB3-SPE_BXP_DATE_EXT.
 move ALTMP942 to ITAB3-SPE_VERSION.
 move ALTMP943 to ITAB3-SPE_COMPL_MVT.
 move ALTMP944 to ITAB3-J_1BTAXLW4.
 move ALTMP945 to ITAB3-J_1BTAXLW5.
 move ALTMP946 to ITAB3-J_1BTAXLW3.
 move ALTMP947 to ITAB3-BUDGET_PD.
 move ALTMP948 to ITAB3-KBNKZ.
 move ALTMP949 to ITAB3-FARR_RELTYPE.
 move ALTMP950 to ITAB3-SITKZ.
 move ALTMP951 to ITAB3-CONS_ORDER.
 append ITAB3.
 cntbuf = cntbuf + 1.
 if download = 'N'.
  if cntbuf > 5000.
    perform FORM4.
    clear cntbuf.
    refresh ITAB3.
    append_flag = 'A'.
  endif.
 endif.
 if download = 'S'.
  if cntbuf > P_PKGSZ.
    perform FORM4.
    clear cntbuf.
    refresh ITAB3.
  endif.
 endif.
ENDSELECT.
ENDFORM.

FORM FORM4.
data: outfile(512), ldfile(50).
ldfile = 'Z_SAPDS_Extract_LIPS'.
concatenate out_dir ldfile into outfile
  separated by '/'.
  IF DOWNLOAD = 'S'.
     DATA: error_message(700),mtext(800),iEOP(1).
     CALL FUNCTION P_SRVFM
          DESTINATION P_DEST
          KEEPING LOGICAL UNIT OF WORK
          EXPORTING
            EOS = last_batch
          IMPORTING
            EOP = iEOP
          TABLES
            E_TABLE = ITAB3
          EXCEPTIONS
            READ_ERROR = 1
            SYSTEM_FAILURE = 2
            MESSAGE error_message
            COMMUNICATION_FAILURE = 3
            MESSAGE error_message
            OTHERS = 4.

     IF sy-subrc ne 0.
        Case sy-subrc.
        when 1.
        CONCATENATE
        'Data Services read error. '
        'Check Data Services error log.'
        INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 2.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 3.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 4.
        MESSAGE  E240(S#) WITH
'Other SAP System Failure while calling DS remote function.'.
        endcase.
      ENDIF.
      IF iEOP = 'X'.
         PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
         LEAVE PROGRAM.
       ENDIF.
  ELSE.
data  dlmtlen type i value '1'.
data xdlmtlen type i value '1'.
data:
  ht(1) type c,
  xht(1) type x,
  conv type ref to cl_abap_conv_in_ce.
xht = '7F'.
conv = cl_abap_conv_in_ce=>create(
  encoding = '1100'
  input = xht
).
call method conv->read(
  exporting n    = xdlmtlen
  importing data = ht
            len = dlmtlen
).
data return_code type i.
 perform write_delimited_file
           tables   ITAB3
           using    outfile
                    append_flag
                    ht
                    dlmtlen
                    download
           changing return_code.

  case return_code.
    when 1.
      IF EXECMODE = 'D'.
        WRITE: /5 'No line selected'.
      ELSE.
        MESSAGE E047(S#).
      ENDIF.
    when 2.
      IF EXECMODE = 'D'.
        WRITE: /5 'Open File Error -- ', 25 OUTFILE.
      ELSE.
        MESSAGE  E084(E0) WITH OUTFILE.
      ENDIF.
    when 3.
      IF EXECMODE = 'D'.
        WRITE: /5 'Data exceed length limit (8192) '.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Data exceed length limit (8192) '.
      ENDIF.
    when 4.
      IF EXECMODE = 'D'.
        WRITE: /5 'Call function WS_DOWNLOAD error'.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Call function WS_DOWNLOAD error'.
      ENDIF.
  endcase.
 ENDIF.
ENDFORM.

FORM SUBSTRING USING SRC BEG LEN CHANGING RET.

DATA: VA1 TYPE I.
DATA: VA2 TYPE I.
DATA: VA3 TYPE I.

VA3 = STRLEN( SRC ).

IF  BEG = 0.   VA1 = 0.
ELSE.
  IF  BEG < 0.
    VA1 = VA3 + BEG.
    IF  VA1 < 0.   VA1 = 0.
    ENDIF.
  ELSE.          VA1 = BEG - 1.
  ENDIF.
ENDIF.

IF  LEN < 0.   VA2 = 0.
ELSE.          VA2 = VA3 - VA1.
ENDIF.

IF  VA2 > LEN. VA2 = LEN.
ENDIF.

IF  VA2 < 1.   MOVE ''           TO RET.
ELSE.          MOVE SRC+VA1(VA2) TO RET.
ENDIF.

ENDFORM.

form write_delimited_file
           tables   datatab
           using    file
                    append
                    delimit
                    dlength
                    dwnload
          changing rc.

  data: type1,
        appd(1),
        temp(32),
        time1(8),
        date1(10),
        output(8192),
        rcount type i,
        offset type i,
        tablen type i,
        maxlen type i value '8192'.

  data: begin of clientab occurs 0,
             output(8192),
          end of clientab.

  field-symbols: <f>.
  field-symbols <delim1>.
  data delim2(16).
  data l_filename type string.

  appd = append.
  if appd is not initial.
     appd = 'X'.
  endif.
  move file to l_filename.
  describe table datatab lines tablen.


  if dwnload = 'Y'.
     clear clientab. refresh clientab.
     rcount = 0.
  else.
     if appd = space.
   open dataset file for output in text mode ENCODING UTF-8.
     else.
    open dataset file for appending in text mode ENCODING UTF-8.
     endif.
     if sy-subrc <> 0.
         rc = 2. exit.
     endif.
  endif.

  loop at datatab.
    clear: tablen, offset, output.
    do.
      assign component sy-index of
         structure datatab to <f>.
      if sy-subrc <> 0. exit. endif.
      if sy-index > 1.
         assign delimit(dlength) TO <delim1> CASTING TYPE C.
         delim2 = <delim1>.
         write delim2(dlength) to output+offset(dlength).
         add dlength to offset.
      endif.

      describe field <f> type type1.

      if type1 = 'I' or type1 = 'N'.
          type1 = 'P'.
      endif.

      case type1.
        when 'D'.
          if <f> = '00000000'.
             <f> = ' '.
          else.
             move <f> to time1.
             assign time1 to <f>.
          endif.
        when 'F'.
          if <f> = '0.0'.
            temp = '0.0'.
          else.
             write <f> to temp exponent 0.
          endif.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
        when 'P'.
          if <f> < 0.
             write '-' to output+offset(1).
             add 1 to offset.
             <f> = <f> * ( -1 ).
          endif.
          move <f> to temp.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
      endcase.

      sy-fdpos = strlen( <f> ).

      tablen = offset + sy-fdpos.
      if tablen > maxlen.
         rc = 3. exit.
      endif.
      write <f> to output+offset(sy-fdpos).
      add sy-fdpos to offset.
    enddo.

    if dwnload = 'Y'.
       clientab-output = output.
       append clientab.
       rcount = rcount + 1.
       if rcount >= 50.
          SY-BATCH = SPACE.
          CALL FUNCTION 'GUI_DOWNLOAD'
            EXPORTING
              FILENAME = l_filename
              FILETYPE = 'ASC'
              CODEPAGE = '4110'
              APPEND   = appd
              WRITE_FIELD_SEPARATOR = 'X'
*            IMPORTING
*              FILELENGTH =
            TABLES
              DATA_TAB = clientab
            EXCEPTIONS
              OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
          clear clientab. refresh clientab.
          rcount = 0. appd = 'A'.
       endif.
    else.
       transfer output to file.
    endif.
  endloop.

  if dwnload = 'Y'.
       SY-BATCH = SPACE.
       CALL FUNCTION 'GUI_DOWNLOAD'
         EXPORTING
           FILENAME = l_filename
           FILETYPE = 'ASC'
              CODEPAGE = '4110'
           APPEND   = appd
           WRITE_FIELD_SEPARATOR = 'X'
*         IMPORTING
*           FILELENGTH =
         TABLES
           DATA_TAB = clientab
         EXCEPTIONS
           OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
  else.
       close dataset file.
  endif.
endform.

FORM CONNECT_RFCDEST_TO_PROGID.
 INCLUDE rfctypes.

 DATA: len     type i,
       R3NAME(4),
       SYSTNR(2),
       uid     LIKE SYS_UID,
       options LIKE RFCOPT,
       isunicode  TYPE n.

 DATA: NTOTAL     LIKE GWY_STRUCT-NOREG,
       GWY_GWHOST LIKE GWY_STRUCT-GWHOST,
       GWY_GWSERV LIKE GWY_STRUCT-GWSERV,
       GWY_TPNAME LIKE GWY_SYSTEM-TPNAME.

 TABLES: RFCSI.

* Check program ID
 IF P_PROGID = SPACE.
    RAISE INVALID_PROGRAM_ID.
 ENDIF.

* determine if the RFC destination authority
  CALL FUNCTION 'RFC_READ_TCPIP_DESTINATION'
       EXPORTING destination = P_DEST
                 authority_check = 'X'
  IMPORTING rfcunicode = isunicode.

* Use current gateway if no info exits
 IF P_GWHOST = SPACE OR P_GWSERV = SPACE.
  CALL FUNCTION 'RFC_SYSTEM_INFO'
      IMPORTING
          RFCSI_EXPORT = RFCSI.

  len = strlen( rfcsi-rfcdest ) - 2.
  systnr = rfcsi-rfcdest+len.
  len = len - 1 - 3.
  r3name = rfcsi-rfcdest+len(3).
  len = len - 1.
  options-rfcgwhost = rfcsi-rfcdest(len).
  CONCATENATE 'sapgw' SYSTNR INTO options-rfcgwserv.
 ELSE.
   options-rfcgwhost = P_GWHOST.
   options-rfcgwserv = P_GWSERV.
 ENDIF.

* Parameters for GWY function call
  GWY_GWHOST = OPTIONS-RFCGWHOST.
  GWY_GWSERV = OPTIONS-RFCGWSERV.
  GWY_TPNAME = P_PROGID.

  DO 10 TIMES.

* Check gateway and server program registered
  CALL FUNCTION 'GWY_GET_NO_REG_PROGRAMS'
     EXPORTING
        GWHOST      = GWY_GWHOST
        GWSERV      = GWY_GWSERV
        TPNAME      = GWY_TPNAME
     IMPORTING
        NOREG_TOTAL = NTOTAL
     EXCEPTIONS
        OTHERS      = 1.

  IF sy-subrc NE 0.
     raise CONNECT_TO_GATEWAY_FAILED.
  ENDIF.

  IF NTOTAL GT 0.
     EXIT.
  ENDIF.

  CALL FUNCTION 'ENQUE_SLEEP'
     EXPORTING
        SECONDS     = 15.

  ENDDO.

  IF NTOTAL = 0.
     raise SERVER_NOT_REGISTERED.
  ENDIF.

  IF NTOTAL GT 1.
     raise DUPLICATE_REG_PROGRAMS.
  ENDIF.

* build new connection to a registered server
  options-rfcexec   = gwy_tpname.
  options-rfcgwhost = gwy_gwhost.
  options-rfcgwserv = gwy_gwserv.
  options-rfchost   = '%%RFCSERVER%%'.
  IF P_SNC_ON = 'X'.
    options-rfcsnc  = 'X'.
  ENDIF.

  CALL 'RFCControl' ID 'CODE' FIELD 'O'
                    ID 'DESTINATION' FIELD P_DEST
                    ID 'TYPE' FIELD rfctype_external_tcp
                    ID 'OPTIONS' FIELD options.

  IF sy-subrc NE 0.
     RAISE CONNECT_TO_REG_SERVER_FAILED.
   ENDIF.

* and set exclusive mode to keep server owned
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
      EXPORTING  destination = P_DEST
                 exclusiv    = 'Y'
      EXCEPTIONS connect_to_reg_server_failed = 1
                 exclusiv_not_supported       = 2.

  IF SY-SUBRC NE 0.
     CASE SY-SUBRC.
          WHEN 1.
              RAISE CONNECT_TO_REG_SERVER_FAILED.
          WHEN 2.
              RAISE EXCLUSIV_NOT_SUPPORTED.
     ENDCASE.
  ENDIF.

ENDFORM.

FORM DISCONNECT_RFCDEST_FROM_PROGID.
* set exclusive mode to E to end the session
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
     EXPORTING
         destination = P_DEST
         exclusiv    = 'E'
     EXCEPTIONS
         connect_to_reg_server_failed = 1
         exclusiv_not_supported       = 2.
ENDFORM.
